### ISSUE TITLE
Blinking lens flare at Luna

### ISSUE THREAD

**Issue by CansecoDev** [Starfield-Community-Patch/Starfield-Community-Patch#10]
There is a visible lens flare blinking happening at least at Luna, it might happen in another places too.

Clip of the issue: [Blinking lens flare at Luna](https://www.youtube.com/clip/UgkxNchBH5swH6-BPTMd_HJ-W6THOHe1BhO4)

## Game Version

1.7.23.0

## New Game

No

## Reproduction Steps

Travel to Luna and land in a place where it's either the "morning", or the afternoon (close to the dark area of the moon, but not inside of it).
Look at the sky and move the camera a bit.

Alternative; I'm uploading both a save right on the spot and used graphic settings for a quicker reproduction.

[Save11_DBDBB2D9_4B68616E_000348_20230901051151_4_0_4.zip](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/files/12494617/Save11_DBDBB2D9_4B68616E_000348_20230901051151_4_0_4.zip)
[StarfieldPrefs.zip](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/files/12494629/StarfieldPrefs.zip)

**Comment by CansecoDev** [comment]
I thought this was related to some mesh overlapping but after loading the save again the issue is nowhere to be found. This one will be a bit harder to track down.

**Comment by Deebz96** [comment]
Closing as invalid, as this issue does not seem to be possible to reproduce.
