### ISSUE TITLE
item weights

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1000]
In not sure if this would be considered a bug or not but a lot of item that have a weight on their texture don't match their inventory weight.

---

## Details 
The foods seem to be a good example of this.

## Game Version
1.8.86.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Compare item weight on the model texture to the inventory weight

**Comment by Deebz96** [comment]
I'd consider this one to be a balancing decision. Out of scope of the SFCP.
