### ISSUE TITLE
UC Exchange Cydonia uses hospital map marker icon

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1001]
What the title said

---

## Details 
Here's a self explanatory screenshot

https://imgur.com/xvYACHy

## Game Version
1.12.30.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Go to cydonia and check the place

**Comment by Deebz96** [comment]
This has been fixed officially.
