### ISSUE TITLE
Hunter encounter in Akila City English subtitles have typo

### ISSUE THREAD

**Issue by tcranor** [Starfield-Community-Patch/Starfield-Community-Patch#101]
![Screenshot_41](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/assets/10421909/2f04858f-c0bd-4aa4-86d2-d4e6ea0f64a8)
"Choosing to act is what puts you in conflict with others. It's not about how the pure the intentions are."
There's an extra "the" in the subtitles. The audio line is correct. 
Steam/PC, English version, latest release.

**Comment by Pickysaurus** [comment]
https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/commit/a51cf6dbb83968aa19b2ab8b3bb16811260bd46d
