### ISSUE TITLE
NPC Ambient Occlusion eye glow

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1012]
This mod seems to fix this bug, but inclusion into the SCP would probably be neat: https://www.nexusmods.com/starfield/mods/2718
Basically, "The baked AO maps for crowd NPCs that were in the game seem incomplete. Only two of them had any amount of shading applied to the eyes and the rest had none. I merely went in and painted in AO into all the maps so that there's an appropriate amount of shading around their eyes so they no longer seem to glow." 
The above taken from the description of the bugfix mod. 

---

## Details 
I don't have any deets, just looking at all the individual bug fix mods floating around and wondering if more of them can be combined into the SCP. 

## Game Version
1.12.30.0

## Language
English (EN)

## New Game
No

## Reproduction Steps
AFAIK, it's just a problem with the vanilla Ambient Occlusion maps for NPCs in the vanilla game.

**Comment by Deebz96** [comment]
This isn’t really a bug per se, but rather an artistic difference.
