### ISSUE TITLE
10/11 Fauna Beta Marae I

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1013]
I am pretty certain you all are aware of the 11th fauna not spawning at Beta Marae I. But if you could fix this, my OCD would greatly appreciate it so I can get 100% scan on the final planet that is incomplete.

---

## Details 
Unfortunately I cannot look up creature id's on Xbox, from what I've read on reddit, it is an aquatic fauna that is suppose to spawn in the lakes/ponds of the swamp biome in Beta Marae I

## Game Version
1.8.86.0

## New Game
Yes

## Reproduction Steps
Searching for glitchesd aqua fauna outside the bodies of water in the swamp biome.

**Comment by Deebz96** [comment]
You may be able to find it if you go to a coastal swamp biome, and look in the ocean.

**Comment by Deebz96** [comment]
Fixed officially by Bethesda as of August update.
