### ISSUE TITLE
UC Vigilance Missing

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1015]
I've seen many people have encountered this bug, so this is probably unfixable or no one really ever mentioned it. I know you could probably find the UC Vigilance looking hard enough, but that is just a pain. I'd rather know exactly where the ship instead of going galaxy to galaxy for hours until I finally stroll upon it. It happens near the end of the UC SysDef side line of things for many people, mine occurred around the 'The Best There Is' quest specifically. The quest has me going to the Aranae planet where the ship is nowhere to be found.  

---

## Game Version
1.8.86.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Getting exactly where I did previously on the same quest line.

**Comment by GWdd** [comment]
I just hit this today ... 

Instead of going direct after picking up the ComSpike from the key, I did some evidence pick up runs. Now the UCV is missing.
