### ISSUE TITLE
Particle Weapons Annihilator Always Applied

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1017]
When using any particle weapon, the effect from Annihilator Rounds weapon mod are always applied, and inevitably damage friendly NPC's or companions. 

---

## Details 
0026D963 (Big Bang), 0026D967 (Novalight), 0026D8A0 (Va'ruun Inflictor), 0026D8A4 (Va'ruun Starshard)

## Game Version
1.12.32.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Find any particle weapon and shoot NPC's with it, the effect will occur within 10-15 shots

**Comment by Deebz96** [comment]
This effect applies on critical hits. It seems to be an intended mechanic, not a bug.
