### ISSUE TITLE
Resources respawn under outpost 

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#102]
Was building an Outpost on top of some resources, one of them poisoned gas. Directly after placing the buildings the resources disappeared like intended.
I then left the planet and returned later, just to see that the resources respawned within or underneath my buildings. 

---

## Game Version
1.7.23.0

## New Game
Yes

## Reproduction Steps
Build an outpost with poisoned gas underneath it, leave the planet and return later, to see if the gas node respawned.

**Comment by Deebz96** [comment]
This one has been officially fixed by Bethesda.
