### ISSUE TITLE
Frozen

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1021]
Latest update to day SCP 1-0-1-6-171854816 frozen the game in the launch window .. if I uncheck the patch in MO2 game starts....

---

## Details 
above

## Game Version
1,12,320

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Start game no go ... uncheck patch in MO2 game starts

**Comment by Deebz96** [comment]
This would be an issue on your end. This mod does not cause the game to fail to start up.
