### ISSUE TITLE
EM Weapon Systems outdated challenge

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1030]
The SFCP reverts the challenge on EM Weapon Systems to an older one.

---

## Details 
The challenge for EM Weapon Systems has changed from "Deal X damage to enemy ships with EM weapons" to "Dock with X enemy ships", which needs to be corrected in the patch.

## Game Version
1.8.86.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Self-explanatory

**Comment by Deebz96** [comment]
The changes to record 002C53B2 appear to be obsolete now. This record will be removed in the next SFCP release.

**Comment by Deebz96** [comment]
Also remove 002c5558
