### ISSUE TITLE
Critical bug with UC Sysdef mission line.

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1033]
Players (including myself) have had a recurring issue with the quest marker for the UC Vigilance in the Sysdef/Pirate questline being misplaced, and the UC vigilance ship not being located on the quest marker or any previous locations.
The soft fix is to force players to side with pirates by firing at the Sysdef guard ships at Procyon-B I, but prevents players from siding with UC Sysdef.

My marker for the UC vigilance is located at Aranae II-A, however no ship is present. The guard ships that typically surround it are located at Procyon-B I, and the ship is nowhere to be seen at Phobos in the Sol System.

---

## Details 
0000D350 appears to be commander ikande’s ID.

To teleport to the vigilance, I saw something mentioning having to input the command “coc ssLC082Vigilance02” 

## Game Version
1.12.32.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Play through the UC Sysdef/Pirate questline. This bug can occur when the quest requires you to “Proceed to the UC vigilance” after “Breaking the Bank” or “The best there is” quests.

**Comment by Constellation-VASCO** [comment]
encountered same bug yesterday, objective return to vigilance at the end of the best there is, marker pointing to aranae, nothing to be found

going to procyon B, the UC ships are there alright, but NOT the vigilance

**Comment by GWdd** [comment]
Just hit this bug today. Instead of going straight from the Key to the UC Vigil I went to pick up the last few evidence locations. Then tried to go the turn them in.  Vigilence marker and ship not working -- so no clue where the UCV is ...

**Comment by nighthawkunit1** [comment]
ohhh nooooo, I have the same problem... 

Any other way around?

**Comment by Deebz96** [comment]
This is reportedly fixed officially in update 1.14.
