### ISSUE TITLE
Player camera shakes because of NPC

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1035]
The player camera shakes (not the normal camera shake caused from shooting/attacking) when an NPC dies near you (even through other means like companions) or gets staggered by beeing shot at. It is not happening with every shot/attack, only when they die or get staggered after enough hits, even when not dying. It is happening with every NPC, even essential.

---

## Game Version
1.8.86.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Shoot/hit NPCs near you.

**Comment by Deebz96** [comment]
I think this one may be caused by a mod on your end. This does not happen normally, unless you're shooting an NPC who happens to have gear with an enchantment that staggers attackers.
