### ISSUE TITLE
Crafting error

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1037]
When crafting at any workbench the quantity slider stops.

---

## Details 
When crafting at any workbench the quantity slider stops at random anywhere between 1 and 99. I’m using the left thumb stick and/or Dpad right to increase the amount and it just stops. The right bumper button still works to move slider to 99. I have 999+ of all the materials needed. I’m level 165 and on first play throughout. Been playing since game came out. I don’t remember this happening earlier in the game.

## Game Version
B6CUCAEA V1.12.32.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
The same thing happens at every workbench, in any outpost, and also at the Lodge.

**Comment by Deebz96** [comment]
Unable to replicate, may be an issue with your controller.
