### ISSUE TITLE
SSNN mission possibly not finishable in NG+

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1039]
The SSNN quest "A light in the darkness" has the player report various quests that he finished and they will start be reported in the SSNN broadcasts. In NG+, due to [Starborn] dialogue options, it is possible to skip at least one of these quests, making this quest linger forever in the log.

---

## Details 
This happens when
- you are in a NG+ that is not a variant universe
- you are not skipping the MQ
- you have finished "Further into the unknown"
- you use the dialogue option that lets you skip the Hunter's attack at the Lodge/the Eye

This will start the NG+ alternative quest "Foreknowledge", which as the nice effect of preventing the Hunter's murder of one of the four Constellation companions. However, this will also skip "Shortsighted" and its follower "No sudden moves" (NSM) (because the Hunter will now kill Petrov and the Scow off-screen, taking his artifact with him) which is one of the quests you need to turn in to finish "A light in the darkness", making the SSNN quest unfinishable.

I am aware that NG+ allows too many options to make things happen differently (i.e. skipping the main quest does imply that you will not do certain quests), but choosing to save Constellation does not foreshadow anything about NSM being skipped.

In theory, one might hook into the script that turns in a report, and check if waiting for NSM would be pointless, but this would not work if you turned in the other quests before doing the Main Quest, since at this point, NSM is still a possibility.

Quest IDs:
- Further into the Unknown: MQ201
- Short Sighted: MQ201B
- No sudden moves: MQ202
- Foreknowledge: MQ404
- A Light in the Darkness: RAD02

## Game Version
1.12.32

## Language
German (DE)

## New Game
Yes

## Reproduction Steps
- Finish the game.
- Enter a NG+ with a regular Main Quest.
- Start "A Light in the Darkness"
- Optional: finish and turn in the other turn-in-able quests (requires entire Crimson Fleet questline / entire Freestar Rangers questline / UC questline until the Terrormorph attack at New Atlantis)
- Play the Main Quest until you are allowed to skip the Hunter's attack at the Lodge, finish "Foreknowledge"
-> The quest with the Scow will unexpectedly not start (and therefore not finish), making the SSNN quest linger in your quest log forever

Since this is really lenghthy to reproduce, I can try to provide a save where the situation occurs based on my own (lightly modded) save.

**Comment by Deebz96** [comment]
Fix attached.

The ending scene for this quest now has additional triggers to start at the end of your 5th interview, if you warned Vlad during Further Into the Unknown. Additionally, if you have previously completed all 5 possible interviews available from this path in NG+, I added a dummy scene to retroactively kickstart the end of the quest the next time you talk to Nadia.

[SFCP_1039.zip](https://github.com/user-attachments/files/16955207/SFCP_1039.zip)
