### ISSUE TITLE
Location of the ECS Constant bugged

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#104]
After completing the questline leading to the ECS Constant obtaining their own grav drive. The quest marker for "Location of the ECS Constant" bugs out and only points to Paradiso, where the ship doesn't appear to be anywhere. Here is a thread from others who ran into this issue as well. https://steamcommunity.com/app/1716740/discussions/0/3824173464663527171/

---

## Details 
N/A

## Game Version
Vanilla

## New Game
No

## Reproduction Steps
Complete quest with the ship obtaining a grav drive on their own. Then over the course of the playthrough, eventually the quest marker will be bugged.

**Comment by Constellation-VASCO** [comment]
https://www.reddit.com/r/Starfield/comments/16bna6l/ecs_constant_location_bug/ Another thread mentioning the same issues.

**Comment by Deebz96** [comment]
#431
