### ISSUE TITLE
New Atlantis Elevator Well - Spaceport - Waterfall

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1040]
After terramorph attack on New Atlantis spaceport, the elevator to the well no longer functions

---

## Game Version
1.12.32.0

## New Game
Yes

## Reproduction Steps
Complete Vanguard quest, though it happens after terramorphs attack new Atlantis, sometime after the spaceport area is back to normal, the elevator stops working

**Comment by Deebz96** [comment]
Dupe of #839
