### ISSUE TITLE
Stroud-Ecklund Staryard missing

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1042]
Stroud-Eckland Staryard is missing. I could visit Stroud-Ecklund in Neon City, but the “Overdesigned” quest requires I visit the Staryard. 

---

## Details 
Good afternoon.  Thanks for your time. 
I am attempting to complete a quest called Overdesigned which requires me to travel to the Stroud-Ecklund Staryard. 
I attempted to travel there numerous way to no effect. 
I tried selecting the quest and using the option to travel directly there. I also tried opening the map and travel directly to the location in orbit. Either way, the Staryard is missing. 
There is however, an icon for the Stroud-Eckland Staryard. But the icon for the Staryard is over 10,000km away. 
I could could hail them and get a response “Welcome to Stroud-Ecklund”. But I am unable to see, travel to, or dock at the Staryard. 
I’ve tried using ships boost to travel the 10,000km distance. Whenever I get halfway there, icon disappears, and then icon reappears behind me. 
I’ve saw on Reddit a number of people encountered this same bug after docking there. Like me, modified their ship while docked, reentered their ship, and saw the ship was clipping the Staryard. They undocked and traveled to another system. Once they returned they experienced the same issue. Some players said the Staryard reappeared after a number of game days. Some shit down the XBOX Series X, cleared cache, and it may reappear. I’ve tried both. Neither worked. 
A little about myself.  I have over 150 hours in playtime. I’m am a grinder and completionist. I am currently level 148.

## Game Version
1.8.86.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Dock at the Staryard is a small ship. Modify your ship. Take it from Class A to Class C, make it much bigger. Re-enter your ship. You will find the ship will clip the Staryard. Undock. Travel away. Then return to the Staryard. It was gone.

**Comment by Constellation-VASCO** [comment]
Sorry for the typo.  Some “SHUT”down the XBOX Series X. Not “sh!t”down. Fat fingers. Forgive me.

**Comment by Deebz96** [comment]
I was able to break it eventually after using the ship builder there multiple times last night. Station was gone, and the hull of my ship was positioned incorrectly. Seems that using ship vendors aboard star stations is still unsafe. I imagine this would be an engine-level bug.

**Comment by Deebz96** [comment]
Out of scope for the SFCP. Will need an official fix by Bethesda.
