### ISSUE TITLE
Main quest one giant leap won't start 

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1044]
Quest One Giant Leap didn't show up after I completed Quest Revelation

---

## Details 
Quest One Giant Leap (Quest MQ 305, ID:0024EF9C)
I tried to use the console command StartQuest 0024EF9C, but it says "Failed to start quest MQ 305"

## Game Version
1.8.86.0

## Language
English (EN)

## New Game
No

## Reproduction Steps
Jump to quest Revelation, upon finishing, if the quest One Giant Leap doesn't show up, then try the console commands...

**Comment by DJLegends1011** [comment]
![Screenshot 2024-06-21 144006](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/assets/70036572/4a9474dc-493c-4e27-b763-7814cb3fb4db)
did you got an error such as this if so then it may be due to an alias not filling up correctlly

**Comment by DJLegends1011** [comment]
some reason there is a bug in the game in which alias not filling up correctly hence why quest like Eyewitnesses just break unless you make all alias optional

**Comment by Deebz96** [comment]
Unable to replicate this one. Unless more specific reproduction steps can be provided, marking this one as invalid or likely caused by another mod.
