### ISSUE TITLE
loss of soundeffects

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1048]
This may not be something that you can help me with, it is a common problem that happens occasionally when you die when the game reloads there is no sound and you have to quit the game and reload to cure it since creations I have to quit, disable creations, load, Quit, reenable and reload to cure it. It is making the game hardwork. Am i doing something wrong and is it possible to put right.

---

## Game Version
1.8.86.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Just die

**Comment by Deebz96** [comment]
This would not be fixable within the scope of the SFCP.
