### ISSUE TITLE
Missing UC Vigilance

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1053]
During the faction quest breaking the bank it says to report mission progress on the UC Vigilance and directs you to Phobos but when you jup to Phobos the UC Vigilance and the quest marker are not there and the starmap shows the location of the UC Vigilance in the Aranae star system between Aranae II and Aranae II-A but when you jump the it's just a bunch of UC sysdef ships and no UC Vigilance make it impossible to complete the UC sysdef side of the quest line

---

## Game Version
V1.12.32.O

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
This is my 6th universe on my original save game and the 1st time i'm replaying the main story without telling Constellation i'm starborn but other Xbox and PC players are experiencing this same issue during this quest and even earlier in the questline

**Comment by Deebz96** [comment]
This is a random issue, but it may be fixed officially in 1.14. Different quest, but same issue:

The Best There Is: Addressed an issue that could make the UC Vigilance difficult to locate because it was very far away
