### ISSUE TITLE
Ground is fully missing in New Atlantis. 

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1054]
The ground is fully gone in new atlantis and in all buildings located in new atlantis, including the lodge. Any objects with physics and players and npcs are falling eternally.

---

## Details 
N/A. The issue persists without any creations enabled.

## Game Version
1.8.86.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Go to new Atlantis.

**Comment by Deebz96** [comment]
This would be caused by one of the other mods you are using, or by having too many mods. This is not an issue with the base game, or the SFCP.
