### ISSUE TITLE
Echoes of the Past Delgado bugged

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1058]
While landed at the lock prison, Delgado doesn't move from his position unless you melee him to his position.

---

## Details 
Each time I start the mission Echoes of the Past and land at the prison The Lock, the npc Delgado doesn't move from his spot until I melee him to the door he's supposed to open. Once inside I have to melee Delgado off the ledge and into the center of the room for the next parts to happen. After escaping off the planet and back to The Key, Delgado is no where to be found and I can't progress through the rest of the crimson fleet missions.

## Game Version
1.12.36.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Just starting the mission Echoes of the Past seems to bug the scripting.

**Comment by Deebz96** [comment]
Unable to replicate this one. Unless more specific reproduction steps can be provided, marking this one as invalid or likely caused by another mod.

**Comment by Constellation-VASCO** [comment]
Did you find a solution to this one? I am having same issue.

**Comment by Constellation-VASCO** [comment]
Same issue happened to me as well. He just stands there after finishing the initial dialog.
