### ISSUE TITLE
Can't open Creations anymore

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1060]
My Creations menu line has stopped working on my premium edition Starfield. 

---

## Details 
"Creations" has worked flawlessly until 3 days ago (June 4th. 2024). I have purchased a number of Addons that all works without any problems and I have bought credits to use for further purchases, but without any changes or indications the menu-line in the opening part of Starfield (first menu) I can no longer use "Creations" - if I do the program crash and Win11 only give me the option to wait for the app to respond or terminate, I have tried to wait for more than 15 minutes and over 3 days have I now tried to make the Creations work again. I have used steams file verification to validate that I haven't lost or corrupted any file, but the check came out without any flaws. But to be sure I deinstalled the whole game and did a brand new install from Steam. The result was as I expected, that the problem persist. So I can use the currently installed Addons, but have no access to further content on the Creation platform.

## Game Version
V1.12.36.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
If I do a clean installation of Starfield from Steam on my win11 PC. The menu item "Creations" don't work any more the whole program crashe and only windows CTRL ALT DEL Terminate App will bring control over my PC again. So now I can't access the addons available on this platform any more - only usee the already installed ones.. This also mean that I don't have access to the credits bought on this platform for further purchases.

**Comment by Constellation-VASCO** [comment]
Quick fix: 
Goto explorer and type C:\users\yourname\appdata\local then find starfield subdir and remove contentcatalog.txt and then start the starfield app. It will now work, but on my PC it only works as long as the game is running. Here after, I have to redo this procedure. This is a fix, but I still haven't found the main problem.

**Comment by Constellation-VASCO** [comment]
Happens of Game Pass PC too,the above fix works though

**Comment by Deebz96** [comment]
Out of scope for the SFCP. Will need fixed on the engine level by Bethesda.

**Comment by johnlafon** [comment]
I have tried removing the contentcatalog.txt file, but didn't work,  The only thing working form me is completely uninstalling the game and creation kit, and re-installing.   I am using the Gamepass version.  I would buy Starfield on steam if I thought that would fix the issue, but I doubt it would.

Anyone have any other suggestions?
