### ISSUE TITLE
Space combat chatter overlaps with banter

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#107]
When engaging in space combat, your crew will call out things disabled or repaired systems on the enemy or your own vessel. This will often overlap with companion banter if you have multiple on board, making the dialogue both very hard to understand and to follow. This happens particularly often when jumping straight into an active combat.

---

## Game Version
1.7.23.0

## New Game
No

## Reproduction Steps
- Have companions with banter dialogue on your vessel (Barrett seems particularly prone, combine with Sam, Andreja, or Sarah)
- Jump/travel to a location where space combat immediately commences

**Comment by Deebz96** [comment]
This is fixable (I have a mod to do this), but this is less of a bug and more of a design decision. Not s good one though, mind you.
