### ISSUE TITLE
RI08 Alexis and Sarah Morgan Scene

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1072]
If you choose the [Sarah Morgan] dialogue option while persuading Alexis, Sarah's dialogue does not play. Alexis just talks to herself.

---

## Details 
Enabling the Run Only Scene packages flag on the 035 Companion alias, within RI08_0300_Alexis_SarahMorganScene, fixes this issue.

## Game Version
1.12.36.0

## New Game
Yes

## Reproduction Steps
Choose the [Sarah Morgan] dialogue option while persuading Alexis during RI08.

**Comment by Deebz96** [comment]
Fix attached.
[AlexisSarahSceneFix.zip](https://github.com/user-attachments/files/16229825/AlexisSarahSceneFix.zip)
