### ISSUE TITLE
Shock Charge Band (Mag weapon) not applying Tesla 

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1073]
Based on how its coded in xEdit, and how its set up in game, Shock Charge Band should be a crafted version of Tesla that has the shock effect, similar to how Ignition Beams is a crafted fire effect. Nothing in how the effect is coded suggests 

---

## Details 
Based on xEdit and in-game, Shock Charge Band weapon modification like on the MAG weapons should apply the Tesla Effect 69dfa the same way ignition beams cause fire.

It simply doesn't work, even though the way its set up in xEdit, it should be working.

## Game Version
1.8.86.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Apply shock charge band to a gun, shoot it, no zap zap.

**Comment by Deebz96** [comment]
This does not seem to be an issue with the base game.
