### ISSUE TITLE
Location of the ECS Constant -- ship NEVER leaves

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1074]
Location of the ECS Constant -- ship NEVER leaves Porrima, no matter how much in game time has passed since you hailed the ship and told them it's time for them to move on before the Paradiso Group gets upset. Not sure if this is a script bug or a quest design bug. This has been the case since game launch has not yet been fixed by Bethesda. If side quests are necessary to make the ship leave Porrima, there are no in-game hints to make it progress.

---

## Game Version
1.12.36.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Do the Paradiso quest, and once you get the "Location of the ECS Constant" activity, hail the ship and tell it to move on. No matter how much in-game time passes, the activity will forever be in your quest log and the ship will never leave Paradiso.

**Comment by Deebz96** [comment]
#431
