### ISSUE TITLE
Ryujin mission Sabotage cannot be completed due to missing neuroamp prototype

### ISSUE THREAD

**Issue by Dark-Thoughts** [Starfield-Community-Patch/Starfield-Community-Patch#1077]
During the mission Sabotage on the step of "Optain the neuroamp prototype" you're supposed to steal the amp from the holding chamber, but the amp is not actually there, blocking you from progress and the achievement.

![20240630153606_1](https://github.com/user-attachments/assets/3fe967b0-8674-42dd-b690-db3aa45cfacd)

### Details

Quest ID: RI07

### Game Version

1.12.36

### Language

English (EN)

### Have you recreated this issue on a new game?

No, I cannot recreate this issue.

### Reproduction Steps

Sneak through the facility, disable the alarm of the holding chamber, open the holding chamber, fail to find the neuroamp...

**Comment by Deebz96** [comment]
Unable to replicate this one. Unless more specific reproduction steps can be provided, marking this one as invalid or likely caused by another mod.
