### ISSUE TITLE
Lost and Found - no wedding ring

### ISSUE THREAD

**Issue by Dark-Thoughts** [Starfield-Community-Patch/Starfield-Community-Patch#1078]
From the four items you have to find, the wedding is not in the location where it should be. I've looked the exact same spot up to make sure, I tried using the low gravity power to maybe lift it up since some people claimed it is stuck between the rocks but for me it simply is not there, at all.

### Details

Quest ID: FFparadisoZ02

### Game Version

1.12.36

### Language

English (EN)

### Have you recreated this issue on a new game?

No, I cannot recreate this issue.

### Reproduction Steps

Go to Paradiso, find the second cabana on the left, walk behind the stairs and look on the ground between the plants & rocks to not find anything at all.

**Comment by Deebz96** [comment]
Unable to replicate this one. Unless more specific reproduction steps can be provided, marking this one as invalid or likely caused by another mod.
