### ISSUE TITLE
A Light In The Darkness - Muffaz outside of map bounds

### ISSUE THREAD

**Issue by Dark-Thoughts** [Starfield-Community-Patch/Starfield-Community-Patch#1084]
The SSN reporter NPC Muffaz that you have to talk to in New Atlantis to hand in news stories seems to eventually be not at her place anymore. For me this happened after I was done doing the Key for SysDef. I found similar reports but they seemed to be after the attack of the Hunter, which I'm long past, and she was definitely still there since then.

![image](https://github.com/user-attachments/assets/2896456f-f432-4b24-b220-fe3dedb2834a)

Note: The map marker is far below the map here. So she's not in the lake, it's just where I moved it for visibility.

### Details

ID: 	RAD02 (29EF60) 

### Game Version

1.12.36

### Language

English (EN)

### Have you recreated this issue on a new game?

No, I cannot recreate this issue.

### Reproduction Steps

Visit SSN. Don't find Muffaz where she should be?

**Comment by Dark-Thoughts** [comment]
Workaround for now: Go to the SSN building in New Atlantis, open the console and use: "00014E4E.moveto player"

**Comment by Deebz96** [comment]
This is a more widespread issue which seems to be able to affect a number of NPCs. Not specific to this one.
