### ISSUE TITLE
Red Mile not starting

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1088]
Mei is not making the announcement that you are running the red mile, leading to a freeze in the mission

---

## Details 
freestar ranger questline completed, have done 2 succesful runs already, when I prompt her to start the red mile it looks like her script is resetting and she will be going to the guard besides the stairs in all occassions I tested it out. 

## Game Version
1.12.36.0

## Language
English (EN)

## New Game
No

## Reproduction Steps
truly unknown, I have tried reloading a few times, going to different planets and back, nothing works, I still have a save file before it starts thankfully. A possible fix would be to skip her announcement and have the doors instantly open upon asking her to run the red mile?

**Comment by Deebz96** [comment]
#480
