### ISSUE TITLE
Stroud Living Quarters Audio Occluders

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1089]
The 2x1 Stroud Living Quarters hab has audio occluder objects placed in its interior cell. These are not typically present in ship modules, and can cause issues with audio while you are in the ship. In my case, one door in my ship had muffled audio, and the engine audio was muffled during takeoff cutscenes.

---

## Details 
Setting these occluder objects to Initially Disabled will remove them from the game, making this module match others in this regard, and fixing the audio issues that this module causes.

## Game Version
1.12.36.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
In my case, I modified the Kepler S to have a living quarters module directly connected to the landing bay at the back of the ship, on the bottom deck. After doing this, audio issues with one of the doors up the ladder, and with engines during takeoff cutscenes began.

**Comment by Deebz96** [comment]
Fix attached.
[Stroud Living Quarters Audio Fix.zip](https://github.com/user-attachments/files/16484428/Stroud.Living.Quarters.Audio.Fix.zip)
