### ISSUE TITLE
Stutter when swapping legendary weapons

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#109]
When you assign a legendary weapon on the numbered favorites hotkey on PC, the game micro-stutters whenever you swap in and out of it. The stutter pause gets worse the more stuff you have in your inventory. 

---

## Details 
It has happened on all my legendary weapons as far as I have tested.

## Game Version
1.7.23.0

## New Game
Yes

## Reproduction Steps
You will need at least one legendary weapon assigned in your numbered favorites hotkeys along with another weapon also assigned on a different hotkey. Have a frame time graph displayed on your monitor and swap between the legendary weapon to another weapon. You will notice stutters in the graph. In my experience, the stutter spikes get worse the more stuff you have in your inventory.

**Comment by Constellation-VASCO** [comment]
People have also stated the issue to occur in rare weapons such as Heller's cutter:

https://www.reddit.com/r/Starfield/comments/169i8w1/bug_scannerweapon_switch_stutter/

**Comment by Constellation-VASCO** [comment]
This mod fixed weapon stutter for me: https://www.nexusmods.com/starfield/mods/2830

From description:
Each weapon modifier caused an inventory read. The more modifiers a weapon and items in the inventory had, the longer it took to swap weapons.

**Comment by Constellation-VASCO** [comment]
Same bug as https://www.starfieldpatch.dev/issues/112 and has already been fixed by Bethesda in the Sept 25th patch. The stutter fix mod somewhat recklessly removes a deliberate optimisation put in place by Bethesda and thus shouldn't be considered for inclusion in the Community Patch.

**Comment by Constellation-VASCO** [comment]
The fix linked is an SFSE plugin which is not in scope for this project.

**Comment by Deebz96** [comment]
This has been officially fixed by Bethesda.
