### ISSUE TITLE
Nova Galactic Large Ship Doors Missing Handle

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1091]
The large ship doors on Nova Galactic habs are missing a handle and in effect have a one way handle. Only one side has the handle and from an immersion perspective, I cannot see a handle on the 'interior' side of the door.

---

## Details 
The large ship doors on Nova Galactic habs are missing a handle and in effect have a one way handle. Only one side has the handle and from an immersion perspective, I cannot see a handle on the 'interior' side of the door.
[11:24:35] SKK_ConsoleUtilityScript.GetInfo Object .......................... [ObjectReference < (FF029FD0)>]
[11:24:35] SKK_ConsoleUtilityScript.GetInfo BaseObject ...................... [Form < (002AC94D)>]
[11:24:35] SKK_ConsoleUtilityScript.GetInfo GetFormID ....................... 2804045

## Game Version
1.12.36.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Play vanilla game, go to Nova Galactic ship hab with a large hatch door.

**Comment by Deebz96** [comment]
I know what you are referring to, but I don’t believe this one counts as a bug. The door was intentionally designed in this way. Making this one as out of scope.
