### ISSUE TITLE
HopeTech 2x2 All-In-One Berth missing.

### ISSUE THREAD

**Issue by Dark-Thoughts** [Starfield-Community-Patch/Starfield-Community-Patch#1094]
Based on Inara, which is likely datamined, it is supposed to be available at HopeTown - either the ship technician or Inaya Rehman inside of the building. However, neither of them have it available, and a mod removing the location restrictions for modules also does not reveal it. The asset itself is definitely in the game though, as it is used in a ship POI of a derelict ship filled with maggots that killed the smuggler crew (see screenshots).

![20240810195252_1](https://github.com/user-attachments/assets/49fee2d2-47ea-44bc-a8de-afc2cd6ee2be)
![20240810195358_1](https://github.com/user-attachments/assets/72b203c1-b19a-4807-ba0d-cf1685c078c4)

### Details

-

### Game Version

1.12.36

### Language

English (EN)

### Have you recreated this issue on a new game?

Yes, I can recreate this issue.

### Reproduction Steps

Go to a HopeTown ship vendor, edit your ship, fail to find the 2x2 hab.

**Comment by Deebz96** [comment]
Confirmed. This is caused by the AIO hab having a conflicting ShipModuleVariant value with the Battle Stations hab. Fix attached.
[HopeTech2x2AIOFix.zip](https://github.com/user-attachments/files/16571102/HopeTech2x2AIOFix.zip)

**Comment by Deebz96** [comment]
Confirmed. This is caused by the AIO hab having a conflicting ShipModuleVariant value with the Battle Stations hab. Fix attached.
[SFCP_1094.zip](https://github.com/user-attachments/files/16571116/SFCP_1094.zip)

**Comment by Dark-Thoughts** [comment]
> Confirmed. This is caused by the AIO hab having a conflicting ShipModuleVariant value with the Battle Stations hab. Fix attached. [SFCP_1094.zip](https://github.com/user-attachments/files/16571116/SFCP_1094.zip)

Thanks. However, this fix only adds the empty version and the interior design is that of the cleaner & brighter Taiyo variant.

**Comment by Deebz96** [comment]
The empty AIO hab is there by default. No bug is preventing it from showing up.

The attached fix does work on my end. Make sure it's installed and activated in plugins.txt correctly, and perhaps also check with xEdit to see if there are any records conflicting on your end with this fix's version of: SMS_Hab_HopeTech_BattleStations_2L2W1H_A [GBFM:003EC621]
![aio](https://github.com/user-attachments/assets/629feace-1267-406f-b412-3e2a44469d9b)

**Comment by Dark-Thoughts** [comment]
Yeah, shows that I rarely ever use the empty habs, as I did not realize that they even remove the piping which made the empty one look much different than the furnished one. Such a failure... Anyway... The hab is not showing up for me, MO2 shows the .esm as enabled.

![image](https://github.com/user-attachments/assets/a9592734-e518-4467-9dee-33f1d0fdb236)
![image](https://github.com/user-attachments/assets/794a47e7-3418-4258-b65a-98a274203957)

**Comment by Deebz96** [comment]
Not sure what to tell you. It's a simple issue in its nature, with an equally simple fix. You will need to investigate why it isn't working on your end.

I have heard of MO2 not working reliably with this game. You can manually check your Plugins.txt file at: C:\Users\<you>\AppData\Local\Starfield\Plugins.txt

To rule out conflicts, I'd check to make sure that this line is at the very bottom of your file, with the asterisk:
*SFCP_1094.esm

**Comment by Deebz96** [comment]
Actually, based on some of your other reports, I am wondering if you are hitting the "mod index" limit. That may be why random things aren't appearing for you, and why this fix isn't working. Try disabling all of your mods and only enabling this fix, see if it works then.

**Comment by Dark-Thoughts** [comment]
It's within the Plugins.txt, though I want to point out that with MO2 this file sits within its various profiles folders that you may or may not have. And currently that mod manager is the only somewhat working thing we have for Bethesda games on Linux, until maybe Nexus makes more progress with their new native app.

Anyway, I did the ole 50/50 mod testing and it seems that the culprit was the rather unexpected Companion and Crew Advanced Overhaul mod. I'll contact the mod author for this.

**Comment by Dark-Thoughts** [comment]
Oh and to clarify, I'm below the mod index. I use the mod index warning on save load to keep track of that. Cacao changes some ship module stats too so I assume it potentially overwrites the changes made by the fix.

**Comment by Deebz96** [comment]
If you had that mod under this fix in your load order, then yes that would be the reason.

**Comment by Dark-Thoughts** [comment]
The .esm load order in MO2 is weird to be honest and can't be directly changed for some reason. The mod list itself had the fix right after all the base mods like achievement enablers but as said, changing the actual plugin list just keeps resetting to whatever MO2 wants. I disabled Cacao for now as I am pushing through NG+ anyway.
