### ISSUE TITLE
Legacy's End

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1095]
Upon grav jumping back to the Key after defending the 3 turret locations all ships, Sysdef - including the Vigilance - and Crimson Fleet are invisible. The can be targeted and shot at / destroyed, but are not visible.

---

## Details 
Crimson fleet questline. Sided with the Fleet. Final Grav jump back to the key after defending the turrets. repeatable.

## Game Version
1.12.36.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Tested by disabling all mod and adding one at a time until the concern returned. With only the Community Patch enabled the bug is present and without it is not.

**Comment by Deebz96** [comment]
Unable to replicate with my usual load order, or with only the SFCP enabled and no other mods.
![vigilance](https://github.com/user-attachments/assets/17d5fc97-29d6-4e79-bfd5-8ee9e0e54a6a)
