### ISSUE TITLE
Gerhard preventing Sarah & Amoli Dialogue

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1096]
Sarah has a dialogue with Amoli at Jemison Mercantile. When you take her to Jemison the first time, it triggers and she walks towards Amoli. If Gerhard is present, however, his dialogue trigger with Amoli activates instead, preventing Sarah and Amoli from talking. Gerhad's dialogue trigger is already too active, and he'll constantly cycle through the dialogue with Amoli. 

---

## Details 
Amoli, Editor ID: UC_NA_AmoliBava; Amoli, Ref ID: 0005FA9E; Gerhard, Editor ID: UC_NA_GerhardPohl ; Gerhard, Ref ID: 0005FA9F

## Game Version
1.12.36.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Just take Sarah to Jemison Mercantile for the first time. As soon as she enters the store, the dialogue trigger will activate and she will walk towards Amoli.

**Comment by Deebz96** [comment]
This isn't really a bug, just a result of those two being configured to talk frequently. I don't believe changing this would be within the scope of the SFCP.
