### ISSUE TITLE
LOD texture or mesh up close

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#11]
Centaurian Arsenal in Jemison Alpha Centauri System inside the furthest weapon rack on the left has pistols that seem to be using low poly or LOD meshes or textures.

---

## Details 
WEAP " (00003266)
WEAP " (00003273)
WEAP " (00003277)

## Game Version
V1.7.23.0

## New Game
No

## Reproduction Steps
Walk into Centaurian Arsenal in Jemison Alpha Centauri System issue should be on the far left side with three pistols

**Comment by jcaldwell02** [comment]
![image](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/assets/49729119/984a57ef-0227-409a-854b-04e8d21f15e1)

**Comment by CansecoDev** [comment]
Can confirm.

The LOD seems to be transitioning normally, zooming in with the scanner will bring the detailed mesh but at a normal distance looks like the report picture.

Looks as if it were missing at least one step and going directly to a further LOD level.

**Comment by Aurelianis** [comment]
As of v1.11.36.0 when testing this issue, it seems to be fixed. 
![Photo_2024-05-18-155408](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/assets/109992824/60e2a456-c7d1-40c7-bd8b-813a05b0069a)
