### ISSUE TITLE
Jacquotte Laguerre (Paradiso gift shop) vendor fix

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1105]
Covered already in https://www.starfieldpatch.dev/issues/301 and https://www.starfieldpatch.dev/issues/185, this vendor stops working due to an incorrect condition after speaking with another NPC.

---

## Details 
Fix available here: https://www.nexusmods.com/starfield/mods/11056
There are supposed to be two sets of dialogue responses for her depending on whether the player has spoken with Emilian Vasilescu about her. But both condition checks are set "equal to 0", so they all play before speaking with Emilian, and none play after. The fix is to change the condition set on 0004844A so it is "equal to 1", that corresponds with the more "friendly" set of responses. Her vendor dialogue then works as it should.

## Game Version
1.13.61.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Talk with Emilian Vasilescu at the Hotel Paradiso reception about Jacquotte Laguerre's attitude, then return to her and try to buy/sell something.

**Comment by Deebz96** [comment]
#185
