### ISSUE TITLE
Landing in Citys CDT

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1109]
When i try to land in New Atlantis or other Citys like Akila or Cydonia and Neon, the game crashes.

---

## Details 
i used LOOT to make sure its in the right load order

## Game Version
1.13.61

## Language
German (DE)

## New Game
Yes

## Reproduction Steps
install the patch and the game crashes when try to land in a star port. On outposts, it works fine.

**Comment by Deebz96** [comment]
This is not an issue with the SFCP or the game. You will need to figure out the issue on your end. Likely a mod conflict, or too many mods.

**Comment by Constellation-VASCO** [comment]
Are there any known mods who are conflicting with the SFCP?
