### ISSUE TITLE
New Atlantis Ship Services Technician Problem

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#111]
The Technician is not restocking his credits after going reaching 0 credits and me waiting a few hundred universal hours.

---

## Game Version
1.7.23.8

## New Game
Yes

## Reproduction Steps
Get the Technician down to 0 credits, then wait.

**Comment by Deebz96** [comment]
Unable to reproduce over multiple playthroughs. Marking as invalid, unless more specific reproduction steps can be provided.
