### ISSUE TITLE
lookup failed error

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1112]
I get a lookup error in inventory and ship vendor some come from a string folder some is something else not yet found it seems

---

## Details 
weapon inventory, and ship vendor at new Atlantis with 132 esm mods the strings folder does cause some mods to not work correctly also so might be broken files that didn't update when Bethesda updated starfield

## Game Version
1.13.61.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
just playing the game it and it pops up in the dialog and inventory boxes

**Comment by Deebz96** [comment]
This is never an issue with the mod itself. It will be an issue on your end. With 132 esm files, you are almost certainly over the master index limit.

**Comment by Constellation-VASCO** [comment]
wait 132 is over the limit i had more mods in fallout 4 and that is including 7 that look like they are normal starfield files now that I look at them and it is running fine just the occasional look up failed error?
