### ISSUE TITLE
City Map locations not 'discovering'

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1113]
After installing SFCP 0.1.7 (did not have a previous version installed) the map icons in various cities that I had not already unlocked, will not unlock. 

---

## Details 
 I had earlier today unlocked some locations so I know it was working, and then after installing this mod (and nothing else) the others wont unlock. I have a few on Neon, The Well and Akila City that are undiscovered and wont unlock.

## Game Version
1.8.86.0

## Language
English (EN)

## New Game
No

## Reproduction Steps
Just walk near a location that should unlock one of the map icons

**Comment by Deebz96** [comment]
Unable to replicate. Was there any specific location that didn't get marked for you?
![image](https://github.com/user-attachments/assets/59d0a984-057f-446f-88b5-7a9153776b4e)
