### ISSUE TITLE
ITMs in 1.0.1.7 patch version

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1114]
There are 30 ITMs in the latest patch release

---

## Details 
Looks like 30 ITMs snuck into the latest patch per xEdit 4.1.5h.

Some examples (can't paste all because of the character limit):
Removing: MQ301EarthTerminal03SubMenu "Access Station Logs" [TMLM:000B11CF]
Removing: [INFO:002C33C5] ('Oh, I'm sorry. Here I am. Arguing with my partner, and you're just standing right here.' in GRUP Topic Children of [DIAL:002C334A])
Removing: [DIAL:002C334A]
Removing: [INFO:0022722D] ('No, I can't handle this. Dad... Dad is....' in GRUP Topic Children of [DIAL:00227278])
Removing: [DIAL:00227278]
Removing: [INFO:00208E54] ('What kind of operation are you running here?' in GRUP Topic Children of [DIAL:00208E60])
Removing: [DIAL:00208E60]
Removing: [INFO:0021B154] ('Blend needs Aurora. And Aurora is totally illegal outside of the Astral Lounge. And really really illegal off-world.' in GRUP Topic Children of [DIAL:0021B170])
Removing: [DIAL:0021B170]
Removing: [INFO:0012C618] ('Amp is... steroid. Very strong, very powerful. Legal for the moment.' in GRUP Topic Children of [DIAL:0012C632])
Removing: [DIAL:0012C632]
Removing: [INFO:0022D907] ('I've spoken to the people at Reliant Medical Corporate, I've talked to the Freestar Rangers... I've even gone to the Freestar Collective Council.' in GRUP Topic Children of [DIAL:0022DAC4])
Removing: [DIAL:0022DAC4]

## Game Version
1.12.36.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
1) Download mod.
2) Launch xEdit in quickclean mode.
3) Select community patch ESM.
4) Review ITMs.

**Comment by Pickysaurus** [comment]
Please check the FAQ before reporting this 
https://www.nexusmods.com/starfield/articles/7

> ## Why does StarfieldCommunityPatch.esm contain Identical to Previous Override/Identical to Master (ITPO/ITM) records?
> 
> These "ITMs" are usually false positives. They exist because the patch provides text-based fixes for multiple locales. The SF1Edit tool - a
> t time of writing - does not distinguish these and only compares the text shown for your current locale. In short, you may see an ITM in English because this record has been fixed in German/Spanish/French/etc. You may clean these records and it will not break your own personal game, but there is really no reason to do so. If you do clean them, please ensure you don't forward these edits in a Collection/Wabbajack list as it will cause problems for users in the language the fix is intended for.

**Comment by Pickysaurus** [comment]
Please check the FAQ before reporting this 
https://www.nexusmods.com/starfield/articles/7

> ## Why does StarfieldCommunityPatch.esm contain Identical to Previous Override/Identical to Master (ITPO/ITM) records?
> 
> These "ITMs" are usually false positives. They exist because the patch provides text-based fixes for multiple locales. The SF1Edit tool - a
> t time of writing - does not distinguish these and only compares the text shown for your current locale. In short, you may see an ITM in English because this record has been fixed in German/Spanish/French/etc. You may clean these records and it will not break your own personal game, but there is really no reason to do so. If you do clean them, please ensure you don't forward these edits in a Collection/Wabbajack list as it will cause problems for users in the language the fix is intended for.
