### ISSUE TITLE
Companions comment on outside temperature indoors

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1116]
Companions will still make comments about extreme heat/cold while they are inside of a sealed interior.

---

## Details 
This is because COM_CREW_CND_Comment_TemperatureCommentsAllowed [CNDF:000CBAA8] only checks for ship interiors, settlements, and outposts. In theory, this can be improved by also checking for sealed environments.

## Game Version
1.13.61

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Go to a planet which is very hot or very cold. Find a random POI with a sealed environment, and go inside of it. Companions will still occasionally comment on the outside temperature, as if they are out there.

**Comment by Deebz96** [comment]
Fix attached. This should correct this issue, but some testing is needed to be sure.
[SFCP_1116.zip](https://github.com/user-attachments/files/16741567/SFCP_1116.zip)
