### ISSUE TITLE
Stache only gives Laredo legendaries

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1117]
Stache in the Tracker's Alliance will only give the player Laredo firearms if you have joined the Freestar Rangers (other types of gear, including armor and melee weapons, are unaffected).

---

## Details 
This issue is explained in depth here: https://www.reddit.com/r/Starfield/comments/1ebfh9y/psa_stache_the_astra_vendor_laredo_weapons_bug/

The fix provided puts a condition on the ByNPCFaction leveled lists to exclude the player from them, which ensures that joining the Freestar Rangers does not change the items you get from Stache.

## Game Version
1.13.61

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Join the Tracker's Alliance and the Freestar Rangers, and shower Stache in Astras. The firearms he gives you will only be from Laredo.

**Comment by Deebz96** [comment]
Fix provided by h495: https://next.nexusmods.com/profile/h495/
[SFCP_1117.zip](https://github.com/user-attachments/files/16741617/SFCP_1117.zip)

**Comment by Deebz96** [comment]
Seems like this one may actually no longer be needed... I get gear of any type now, without any fix.
