### ISSUE TITLE
Eye attack marker enabled if skipping the attack.

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1126]
The Eye can appear that it has suffered an attack after warning Vlad about The Hunter, despite an attack never occurring if you do this.

---

## Details 
In NG+, if you warn Vlad about the Hunter's attack, this skips a couple of main quests. For some reason though, High Price to Pay is still started and stopped in the background. This causes the MQ204EyeAttackEnableMarker to get enabled, which enables a layer of strewn about props in The Eye to make it look like it suffered an attack. This layer is normally disabled during Missed Beyond Measure after Vlad mentions he’s fixed up the station, but unlike High Price to Pay, that quest never actually runs if you skip the attack. This means that despite The Eye never actually having suffered an attack, it looks like it has, and it will never get repaired later.

## Game Version
1.13.61

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
In NG+ during Further Into the Unknown, warn Vlad about The Hunter's attack. Complete the Foreknowledge quest. Then go to The Eye. It will appear as if it has suffered an attack.

**Comment by Deebz96** [comment]
This one's bugged me for awhile. Finally got around to fixing it.

Modified QF_MQ204_002C6D74 to only enable this layer if MQ201 has NOT reached stage 2000 (Starborn ending). This will handle anyone who hasn't already reached this point in the story.

To make the fix retroactive for players who have passed this point, I have amended our UpdateHandler script to add a one-time check which disables this layer if the player loads a save where MQ201 has reached stage 2000. This fix is immediate, and will also work if loading a save on The Eye.

Also had to update the MQ204 and SFCP_Hotfix QUST records with added properties for MQ201, to be able to check it in these scripts.

[SFCP_1126.zip](https://github.com/user-attachments/files/16823304/SFCP_1126.zip)
