### ISSUE TITLE
Guards refer to attack that never happened

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1127]
In NG+, if you skip The Hunter's attack, guards will still mention seeing you running away from "that crazy guy", despite this never happening.

---

## Details 
This is because this line of dialogue only checks to see if High Price to Pay has been completed, which is still true even if you skipped the attack. By adding an extra condition to also check that Further Into the Unknown has NOT reached stage 2000 (the Starborn ending), we can prevent this line from playing if you've skipped the attack.

## Game Version
1.13.61

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Warn Vlad about the Starborn to skip The Hunter's attack, and complete Foreknowledge. Then spam the talk button on any guard in New Atlantis. Eventually, they will mention seeing you "running away from that crazy guy".

**Comment by Deebz96** [comment]
Fix attached.
[SFCP_1127.zip](https://github.com/user-attachments/files/16823349/SFCP_1127.zip)
