### ISSUE TITLE
Roach dialogue always shows player has completed 0 bounties

### ISSUE THREAD

**Issue by EgoBallistic** [Starfield-Community-Patch/Starfield-Community-Patch#1130]
When talking to Roach in the Trackers Alliance HQ, your dialogue always shows "I've completed 0 bounties. How do we stack up?" regardless of the actual number you have completed.

### Details

This occurs because the dialogue uses the text substitution <Global=SFBGS003_Bounties_Total> but the quest never calls UpdateCurrentInstanceGlobal() on that variable, so the quest's instance of that global remains at zero forever.

The solution I came up with is to add this simple script to the Roach alias on SFBGS003_DialogueTAHQ:
```
Scriptname RoachAliasScript extends ReferenceAlias

Quest Property SFBGS003_DialogueTAHQ Auto Const Mandatory
GlobalVariable Property SFBGS003_Bounties_Total Auto Const Mandatory

Event OnLoad()
	SFBGS003_DialogueTAHQ.UpdateCurrentInstanceGlobal(SFBGS003_Bounties_Total)
EndEvent
```
This forces the quest to update its variable instance every time Roach loads. I would have preferred to fix this in the dialogue itself, but the text gets displayed before the scene script fragments run.

### Game Version

Version 1.13.61

### Language

English (EN)

### Have you recreated this issue on a new game?

Yes, I can recreate this issue.

### Reproduction Steps

Talk to Roach after completing the first bounty quest.

**Comment by Deebz96** [comment]
Fix confirmed, thank you! Do you have a preferred name and Nexus Mods profile you'd like us to mention in the changelog?
[SFCP_1130.zip](https://github.com/user-attachments/files/16825973/SFCP_1130.zip)

**Comment by EgoBallistic** [comment]
Just use EgoBallistic, I don't have a Nexus account under this name.  Thanks!
