### ISSUE TITLE
Vasco follows you into the unity.

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1131]
If you jump to the unity while Vasco is your active companion, he will follow you in. No follower is supposed to do this.

---

## Details 
This is because the sq_playershipscript will specifically teleport Vasco to you when you exit your ship, if he is your follower, and if you are not currently in space. Since the unity is not a space cell, it's not considered by that condition.

## Game Version
1.13.61.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Have Vasco as your current follower. Build the armillary and jump to the unity. Vasco will be right behind you.

**Comment by Deebz96** [comment]
Fix attached.
[SFCP_1131.zip](https://github.com/user-attachments/files/16825791/SFCP_1131.zip)
