### ISSUE TITLE
SY-920 disguises marked as quest items.

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1134]
During the quest "The Best There Is", the ensign and engineering outfits you can use as disguises are marked as quest objects. This forces them to stay in your inventory for the duration of the mission, which prevents you from giving a second outfit to a companion for immersion purposes. There is no reason for these outfits to be marked as quest objects, as dropping any of them at any point during the mission (or never picking them up, as they are optional) will not softlock or break anything.

---

## Details 
I have unmarked the following aliases as quest objects, and tested the mission to ensure that everything works as expected: CF05_EnsignUniformQT, CF05_EnsignUniformQT01, CF05_EnsignUniformQT02, CF05_Helmet, CF05_EngineeringUniform01, CF05_EngineeringUniform02, CF05_EngineeringUniform03

## Game Version
1.13.61.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
On SY-920, pick up a disguise outfit, and attempt to either drop it or trade it with a companion. You will be unable to, despite there being no reason for these outfits to be locked to your inventory.

**Comment by Deebz96** [comment]
Fix attached:
[SFCP_1134.zip](https://github.com/user-attachments/files/16830145/SFCP_1134.zip)
