### ISSUE TITLE
Skittle planets 

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1135]
All my planets look like skittles 
Says I’m not supposed to see this,tried all the fixes I could find online but none work for me 

---

## Details 
Same as above all planets say i should not be seeing this and look like skittles 

## Game Version
1.13.61

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
None just start as normal

**Comment by Constellation-VASCO** [comment]
Why is this saying invalid

**Comment by Deebz96** [comment]
This is not an issue we can fix with a mod. You will need to troubleshoot the cause on your end.
