### ISSUE TITLE
LC180World - Opposing Turrets

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1138]
Reliant Medical - Turrets 0015DECA, 0015DECB are LvlTurretShort_aggro 0015DECC & LvlTurretShort_HostileCreature 00133353 making them hostile towards each other.

---

## Details 
Reliant Medical - Turrets 0015DECA, 0015DECB are LvlTurretShort_aggro 0015DECC & LvlTurretShort_HostileCreature 00133353 making them hostile towards each other and immediately fight each other on cell load instead of the hostile creatures. These are the ones right in front of the entrance. I was wondering why these seemed to battle it out every time I landed. Both have the same settings including XLRT and the same terminal LR.

## Game Version
1.8.86.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Description

**Comment by Deebz96** [comment]
Fix attached. Requires a new game or NG+ to take effect.
[SFCP_1138.zip](https://github.com/user-attachments/files/17085073/SFCP_1138.zip)
