### ISSUE TITLE
Can't compare bounties with Caf

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1141]
Caf has a dialog option where you can compare the amount of bounties you collected with his. However, the bounty counter of the player stays at 0 no matter how many bounties you completed.

---

## Game Version
1.13.61

## Language
French (FR)

## New Game
Yes

## Reproduction Steps
Complete the first tracker alliance quest to become a member, complete 1 or 2 bounties then speak to caf at the Tracker's alliance HQ and choose the second option.

**Comment by Deebz96** [comment]
#1130
