### ISSUE TITLE
Suit protection regenerates at improper times

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1142]
This bug affects the Normal setting for the Environmental Damage & Afflictions gameplay setting. Has been in the game since at least the August update, but perhaps as early as the May update. If you are in a location which is considered safe from ambient environmental effects (Cydonia, New Homestead, etc), OR if you are on a planet that is not cold, hot, or corrosive/toxic, hazardous weather will deplete your suit protection as expected. However, once suit protection reaches 0, it will begin to regenerate for a second before depleting again. This repeats over and over, spamming your HUD with these notifications.

---

## Details 
This is because the ENV_Weather spells [001639EB], [001639F8], [001639F9], [00163A00], [00163A02], [00163A03], [00163A05], [00163FE7], [00281ECB], [00281ECD] all have a condition of 'Subject.IsTrueForConditionForm(ENV_CND_InHazardousEnvironment [CNDF:0011F365]) = 1' on the 'ENV_DMG_*_Weather_SoakDepleted_NonExtremePlanet_Effect' effects for these spells. This condition prevents these effects from applying in the locations mentioned above, which causes suit protection to begin to regenerate once it reaches 0. This condition is unnecessary, because these effects are already properly controlled by two other conditions which only allow them to apply if the player's suit protection is <= 1, and the player is not in a sealed area. Additionally, as they are set up, these magic effects only end up applying keywords to the player (one of which keeps suit protection at 0). Afflictions are still gained because they are controlled by another effect, which does not have the condition mentioned above.

## Game Version
1.13.61.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Set the Environmental Damage & Afflictions gameplay setting to Normal. Stand in a location such as Cydonia during a sandstorm. Watch the HUD, and listen to the suit protection alert, as it fully depletes. You will see it regenerate for a second before depleting again. This will repeat until you leave the affected location, or the weather ends.

**Comment by Deebz96** [comment]
Fix attached. The 'Subject.IsTrueForConditionForm(ENV_CND_InHazardousEnvironment [CNDF:0011F365]) = 1' condition has been removed from the 'ENV_DMG_*_Weather_SoakDepleted_NonExtremePlanet_Effect' effects in the following weather spells: [001639EB], [001639F8], [001639F9], [00163A00], [00163A02], [00163A03], [00163A05], [00163FE7], [00281ECB], [00281ECD]

[SFCP_1142.zip](https://github.com/user-attachments/files/16883498/SFCP_1142.zip)
