### ISSUE TITLE
Enemy Starborn Ships Permanently Cloaked

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1143]
Occasionally during combat, enemy Starborn ships can remain permanently cloaked after they finish boosting.

---

## Details 
Looking at the AbStarbornShipCloaking spell, it has a condition to only allow the cloaking magic effect to be active if the player's ship boost fuel is > 10%. This spell is also used by NPC ships, which makes this a bad condition to use in this spell. It also appears to be redundant, as the perk which adds this spell to the player also has a condition that the ship's boost fuel must be >= 10%. Watching the behavior of this bug, and a video I have of a previous battle with Starborn ships where this bug occurred, it may very well be caused by the player's boost fuel being below 10% while an enemy Starborn ship is cloaked.

## Game Version
1.13.61.0

## New Game
Yes

## Reproduction Steps
Get into some battles with Starborn ships, and make liberal use of boost each time. Eventually, you'll see at least one ship remain permanently cloaked.

**Comment by Deebz96** [comment]
I have removed this condition from the AbStarbornShipCloaking, and the issue appears to no longer be happening on my end. It's possible that this condition was causing some weird interaction with enemy Starborn ships, making the magic effect remain active permanently.

Further testing needed of course, but the removal of this condition will not cause any issues. It will, at minimum, improve the behavior of enemy ships' cloaking abilities by untying it from the player's boost fuel level.

[SFCP_1143.zip](https://github.com/user-attachments/files/16901260/SFCP_1143.zip)
