### ISSUE TITLE
Sneak attack damage stacking incorrectly scoped

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1144]
Sneak attack damage scoped vs unscoped is wildly inconsistent, with an over 5x difference.

---

## Details 
Looks like the sneak damage scoped is not being applied properly, maybe being overwritten by something? I have max level Sniper Certification, Rifle Certification, Stealth, and Concealment perks. I used a legendary silenced hard target with Instigating, Shattering, and Hitmans when I noticed. Here's an imgur link to screenshots https://imgur.com/a/starfield-sneak-attack-scoped-dmg-WTUJ6O1?third_party=1
When recreating with a non legendary silenced hard target, the scoped damage was more than unscoped.

## Game Version
1.13.61.0

## Language
English (EN)

## New Game
No

## Reproduction Steps
Max level Sniper Certification, Rifle Certification, Stealth, Concealment perks. Doesn't need to be silenced, but a legendary rifle with Instigating Shattering Hitmans will show the biggest difference in damage. Even without though, you can see a large difference, but scoped will do more damage instead.

**Comment by Constellation-VASCO** [comment]
I just learned the game can only display a max of 4 digit damage and it cuts off the first digit if you go past 9999? I'll look more into it but that may be the problem

**Comment by Constellation-VASCO** [comment]
I don't know if someone could close this, but if they can I would appreciate it, I believe I was just thrown off because the damage does 4 digits max

**Comment by Deebz96** [comment]
Thank you for the additional information. Interesting that you could manage to do that much damage.
