### ISSUE TITLE
EM Weapons Don't Damage Robots & Turrets

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1145]
Reporting on behalf of JaeDLmods. Since the June update, EM weapons no longer deal health damage to robots and turrets. They will still deal EM damage, but this damage type is ineffective against those enemies. Robots will "regain consciousness" after only a few seconds, and turrets never "lose consciousness" in the first place.

---

## Details 
This is because, as of the June update, PlayerCommonWeaponModPerk [PERK:00101CB2] has an effect which multiplies weapon attack damage by 0 if the player has equipped a weapon with the WeaponTypeEM keyword. On the surface level, this effect appears to be redundant, as attack damage is ALSO multiplied by 0 by Mod_Weapon_EMShock [PERK:001D5D53], which is a perk given to the player when they equip an EM weapon.

However, when removing this effect from PlayerCommonWeaponModPerk, an EM-converted Novastrike sniper will suddenly also deal lethal damage. I'm not entirely sure why, as that object modification applies the same template that other EM weapon conversion mods get. However, it's safe to assume that the inclusion of this effect in PlayerCommonWeaponModPerk was a hack, specifically for this rifle.

The problem is that the effect in PlayerCommonWeaponModPerk lacks target conditions which exclude robots and turrets. The original effect in Mod_Weapon_EMShock DID have those conditions. By applying the same conditions here, the EM-ified Novastrike sniper remains non-lethal against living targets, but all EM weapons can properly damage robots and turrets once again.

## Game Version
1.13.61.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Equip an EM weapon, shoot at robots or turrets. Their health remains at 100%.

**Comment by Deebz96** [comment]
Fix attached.

[SFCP_1145.zip](https://github.com/user-attachments/files/16919955/SFCP_1145.zip)

**Comment by Deebz96** [comment]
Fix no longer required, will be fixed officially in 1.14.
