### ISSUE TITLE
missing name

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1149]
In polish localisation of the game on a planet "Tirna X-a" in a "Alfa Tirna" system. There is a creature that has a blank name.

---

## Details 
In polish localisation of the game on a planet "Tirna X-a" in a "Alfa Tirna" system. There is a creature that has a blank name. I have made lot's of screenshoots, but i can't send it here. So if you want them, i have nickname "Heidi" in your discord, i can send them there.

## Game Version
1.13.61.0

## Language
Polish (PL)

## New Game
Yes

## Reproduction Steps
just fly to this planet

**Comment by Constellation-VASCO** [comment]
i triple checked, and the creature suddenly has a name... i think that was on my side...

**Comment by Deebz96** [comment]
This is an occasional bug with any creature across any language. I don’t believe it can be fixed via an ESM, as there is nothing wrong with these records. Likely an engine issue.
