### ISSUE TITLE
Companion Weightlifting Perk w/ Leadership

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1150]
Reporting on behalf of Pyrexo, who found and fixed the bug here: https://www.nexusmods.com/starfield/mods/10712

I will include his description below.

---

## Details 
This mod fixes the Weight Lifting skill that the Adoring Fan and Mathis Castillo use. The crew version of the skill, not the player version.
When the player has Leadership Rank 4, the bonus of their companion's Combat and Physical skills should double.
This means that the Adoring Fan's Weight Lifting Rank 2 skill, a Physical skill that gives him 30kg more carrying capacity, should now give him 60kg more carrying capacity when the player has Leadership Rank 4.
But this doesn't happen.
The carrying capacity does double, but only at Leadership Rank 1, not Rank 4.
Once you go to Leadership Rank 2, it no longer stays doubled. In fact, it's deactivated altogether. This is because the skill is incorrectly coded to only check for Leadership Rank 1.
This is most noticeable on Adoring Fan, whose carrying capacity will go from 195kg to 185kg when ranking up Leadership from Rank 1 to Rank 2. This is because his Weight Lifting skill is now completely deactivated, so his carrying capacity is now 135kg like every other companion, but he is benefitting from the player's Leadership Rank 2, which gives companions 50kg more carrying capacity, thus he ends up with 185kg, instead of 215kg, which is what it should be. 
So this mod fixes the coding. Now, Adoring Fan and Mathis Castillo's Weight Lifting skill will be doubled only at Leadership Rank 4, as it is meant to be.

## Game Version
1.13.61

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Take the Leadership perk, check the carry weight of a companion with the weightlifting perk as you level up your perk from 1 to 4.

**Comment by Deebz96** [comment]
Fix by Pyrexo is attached:
[SFCP_1150.zip](https://github.com/user-attachments/files/16954255/SFCP_1150.zip)
