### ISSUE TITLE
Rev-8

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1153]
Since I updated the mod I can actually see my Rev-8 but now I can't get out once I'm in it.also unsure if this was the correct spot/ topic to report this.

---

## Details 
Tried restarting, changing the bind for it. Nothing seems to work on my end.

## Game Version
1.8.86.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Made a new character no mods worked fine. Loaded Community Patch broke it. The disabled and ran other mods worked again. My load order consist of like 7-10 mods so quick and easy to figure it out which was responsible.

**Comment by Deebz96** [comment]
The community patch has nothing which would cause this. You have an outdated HUD mod, most likely the Data\Interface\hudmenu.gfx file.
