### ISSUE TITLE
Master Location References missing in Starstations

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1154]
For many Starstation Location references, the Master Persist Location References and Master Special References are removed.

For instance: 0002E373 LC175StationRE939Location

I cannot find any changelog mentioning these changes -- is it intentional and why?

---

## Details 
0002E373 LC175StationRE939Location

## Game Version
 1.13.61 

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Open in xEdit or CreationKit, examine Starstation Location records.

**Comment by Deebz96** [comment]
These references get re-arranged automatically by the CK. It’s not an issue, and makes no difference in the game that I have seen.
