### ISSUE TITLE
New Homestead Brownout quest/mission

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1156]
The mission for the brownouts in New Homestead is not starting.

---

## Details 
 The brownout mission/quest in New Homestead is not triggering/being added to my mission log. I spoke with the Joyce Osaka npc, went through all the dialogue, and the quest did not start when I finished speaking with her. I do not have any mods that would or should interfere with this quest.

## Game Version
1.8.86.0

## Language
English (EN)

## New Game
No

## Reproduction Steps
Enter New Homestead and speak with Joyce Osaka.

**Comment by Deebz96** [comment]
Not able to replicate the bug on my end, but looking it up online, this seems like quite a common one. Can you perhaps send your save file?

**Comment by Deebz96** [comment]
This is reportedly fixed officially in 1.14.
