### ISSUE TITLE
Impact grenade projectile using frag grenade model

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1157]
Impact grenades are using the frag grenade model when thrown instead of the correct impact grenade projectile model.

---

## Details 
ImpactGrenadeProjectile [PROJ:0005516E] is using "Weapons\FragGrenade\GrenadeFrag_Projectile.nif" when it should be using "Weapons\impact_shrepnelgrenade\GrenadeImpact_Projectile.nif". Made the switch and tested in-game and it's working as expected. Other grenades seem to be correct, it's just this one. See the #community-patch channel in the discord for an esm.

## Game Version
1.13.61.0

## New Game
Yes

## Reproduction Steps
Throw an impact grenade, enter photo mode while it's still in the air, and verify the model used.

**Comment by Deebz96** [comment]
Confirmed, thank you! 0.1.8 is already being prepped for release, but this one will be in 0.1.9 if it isn't fixed officially by Bethesda in the next update.

[SFCP_1157.zip](https://github.com/user-attachments/files/17004313/SFCP_1157.zip)

**Comment by Constellation-VASCO** [comment]
0.1.8 is being revised for compatibility with the next update, so I'll include this one now.
