### ISSUE TITLE
REV-8 ride straibght and fall under map

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1158]
Sometimes, when I'm driving in a vehicle (rev-8), I happen to suddenly fall into a hole and fall deep into the map, seeing everything from the "inside". You can't pause the game, get out of the vehicle, the game crashes later. Sometimes you can magically jump out and reset the position already at the "top"

---

## Game Version
1.8.86.0

## Language
Polish (PL)

## New Game
No

## Reproduction Steps
Ride fast, use turbo hunl(space) few times, or ride straibght without turbo

**Comment by Deebz96** [comment]
Do you have any more specific replication steps? Perhaps a video of this happening?
