### ISSUE TITLE
Companion Conversations Eventually Stop Working

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1159]
A set of 24 conversations between the Constellation companions can stop working eventually in any given playthrough. These conversations can be heard anywhere they are together, including your ship. These are separate from the conversations that play specifically in the Lodge.

---

## Details 
This is because of the quest: COM_Companion_SamCoe_Convo_SarahMorgan03 "Sam Coe / Sarah Morgan Conversation 03" [QUST:000DF319]

This quest contains no actual conversation. When it runs, it will never actually end, and will permanently hold up the other conversations. By removing this quest from CompanionConversationsQuests [SMQN:003E9710], it is no longer an obstacle for the other conversations, and they will resume normally. The empty quest for Sam and Sarah will remain running in the background, but this won't actually harm anything. 

## Game Version
1.13.61.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Get Sam and Sarah together in one room for long enough. Eventually they will stop talking to each other, and the awkward tension will be so severe that nobody else in Constellation will ever break the silence.

**Comment by Deebz96** [comment]
Fix attached.

[SFCP_1159.zip](https://github.com/user-attachments/files/17052928/SFCP_1159.zip)
