### ISSUE TITLE
Unbearable Freezing

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#116]
Most of my time in my 8 hour playthrough was spent in the display menu trying to configure the best settings so that I could play without constant frame freezing or stuttering. I tried just about everything to fix this but to no avail. The game would freeze for up to 8 seconds by doing just about anything. From speaking to NPCs or entering a new area or even just wandering around the game would just freeze. Even opening a menu was an unbearable task.

---

## Game Version
1.10.0

## New Game
Yes

## Reproduction Steps
Complete the first part and start exploring. I have a pretty beefy computer so I doubt it's that.

**Comment by purplepity** [comment]
What PC specs do you have? I had a friend with really bad freezing problems and we learned that it stemmed from not using an SSD.
