### ISSUE TITLE
Viking Cockpit get up animation bug

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1160]
Once a vanilla ship acquired that has Viking cockpit (Stroud-Eklund), when a change made to ship, the Get Up animation from pilot seat soft-bugs.

---

## Details 
Any Viking cockpit.

## Game Version
1.8.86.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
1. Acquire any vanilla ship that has Viking cockpit.
2. Get In the pilot seat, then hold E again to Get Up.
3. The player character will Get Up from right side with a nice animation.
4. Go to any ship vendor and make a change to the ship in Ship Builder (except rename since it doesn't cause this bug).
5. Get In the pilot seat again and Get Up.
6. The character will Get Up (always) from left side with a common animation like other cockpit seats using.

Additional notes,
1. The Get Up animation isn't randomized. I tested Getting Up 10 times each before and after I modify ship to be absolutely certain. As long as it stays vanilla the character will always get up from right side, and once modified will always get up from left side.
2. Photo references (just in case);
- Getting Up from right side if the ship isn't modified and completely vanilla: https://imgur.com/a/9rqKn9i
- Getting Up from left side if the ship is modified: https://imgur.com/a/Jq6fJAt

**Comment by Constellation-VASCO** [comment]
I had marked this as Animation issue but perhaps it would have been better and more accurate to mark it as Ship issue, since the animation itself isn't wrong, it's just the game using the wrong animation instead.

**Comment by Deebz96** [comment]
This is the correct animation for this pilot seat. However, it does appear that using the ship builder causes some sort of change which makes the seat default to using LeftExitToStand instead of RightExitToStand.

You can still see the RightExitToStand animation if you place objects on the left side of the seat, like so.
![image](https://github.com/user-attachments/assets/a2c5e062-cf63-41bc-a093-5b4fddf1821f)

The only thing to potentially do here is randomize which side you stand up from if both are unobstructed, but this wouldn't strictly be a bug fix. Also unsure how to accomplish this. I'll mark this one as Wont Fix for now, unless someone can find a safe way to randomize the animations here.

**Comment by Constellation-VASCO** [comment]
I understand, thank you so much. Actually I haven't added anything to either side, still waiting to get some plushies and other nice looking stuff to start decorating the ship's interior so both sides are vanilla. Only the ship is modified from Ship Technician.

I will try adding obstructions to left side, but I think this will then block the entering animation from left side as well :( No rush of course but if you could happen to find a way to restore it to original again or just randomize, I would be so much grateful if you could fix :) but again, no rush at all.

**Comment by Constellation-VASCO** [comment]
Hey there again Deebz, I wanted to add an update.

I have tried adding obstructing stuff to the left of the cockpit, while it is preventing me from getting in from left side, it is still forcing my character to get up from the left side 🥺🥺

I feel like at this point this is a bug, since even after this it is forcing LeftExitToStand anim despite for the getting in, it is forcing RightExitToEnter 🥺 Attached a video as well.

https://streamable.com/zmawrk

**Comment by Deebz96** [comment]
Works fine on my end. I guess your chairs weren't blocking the exit point correctly.
https://www.youtube.com/watch?v=JoiIuJGWhh0

**Comment by Constellation-VASCO** [comment]
Oh oh, I realized now the position where your character stops walking after getting up needs to be blocked, not the path the character walking through.

Thank you so much :))
