### ISSUE TITLE
Stroud 2x1 Living Quarters NPC Lean Marker

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1161]
In the rear end of this hab, there is a furniture marker letting NPCs lean against a countertop. If you have a doorway on the rear end of the hab, the countertop gets disabled, but the lean marker remains. This can lead to them leaning against nothing, in the way of the door.

---

## Details 
This is because REFR:001D617C, which places this marker, lacks the same linked ref as the rest of the objects which get disabled when the back wall is removed. Adding it fixes this issue.

## Game Version
1.13.61.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Build a ship with the Stroud 2x1 living quarters hab, put a door or window on the aft side, and wait for an NPC to eventually sandbox over to this marker and appear to lean against nothing.

**Comment by Deebz96** [comment]
Fix attached.
[SFCP_1161.zip](https://github.com/user-attachments/files/17080260/SFCP_1161.zip)
