### ISSUE TITLE
Starsap Tour [Starborn] Dialogue Appears Too Early

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1162]
The [Starborn] dialogue option, which is supposed to only appear before taking his tour if you have completed it in a previous universe, will appear after taking it. This can lead to dialogue that doesn't make sense.

---

## Details 
By adding an extra condition of Subject.GetQuestCompleted(FFNewHomesteadZ01 [QUST:0021710B]) = 0 to DialogueNewHomestead_Bill_Top_Starborn [SCEN:0000B555], this option is blocked if you have completed his tour in your current universe, but not beforehand.

## Game Version
1.13.61.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Be Starborn, complete Bill's tour, and talk to him again afterwards. You can tell him you've already taken his tour, and he'll claim otherwise.

**Comment by Deebz96** [comment]
Fix attached:
[SFCP_1162.zip](https://github.com/user-attachments/files/17082403/SFCP_1162.zip)
