### ISSUE TITLE
Family Reunion & Location of ECS Constant

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1163]
The ECS Constant location marker reverts back to Porrima 2 but the ship isn't there. 

---

## Details 
With two different characters I could do a few Family Reunion quests... Then after a few at the "return to Abe" part the location glitches and only shows the original location of the ship at Porrima 2 instead of whatever system it currently is at. And the "location of ECS Constant" activity is also wrong. 

## Game Version
V1. 13.61.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Just did the quest. Gave the colonists the grav drive and they start system hopping. Then the game just glitches on their actual location.

**Comment by Deebz96** [comment]
Same general issue as #431
