### ISSUE TITLE
Companions scold you for using cutter

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1164]
Companions have comments to scold you for using a weapon within settlements. These make sense for the most part, but they also happen when you fire a cutter. This is more of a tool than a weapon, and it is used in multiple quests that take place within settlements. Examples include, but may not be limited to: mining in Cydonia, clearing ice in New Homestead, clearing rocks in Akila City.

---

## Details 
SQ_Companions [QUST:002A567C] controls these lines. The script property 'DischargeWeapon_WeaponKeywordExceptions' contains a list of keywords for weapon types that are excluded from triggering these comments. It already has exceptions for melee and unarmed weapons, based on their WeaponType keywords. The Cutter does not have a unique WeaponType keyword, but the ma_Cutter [KYWD:001F70DF] keyword serves as a suitable alternative. The only weapons which reference it are the player and NPC versions of the Cutter. By adding it to the list, the Cutter no longer triggers these comments.

## Game Version
1.13.61.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Have companion, go to settlement, equip Cutter, fire Cutter.

**Comment by Deebz96** [comment]
Fix attached.
[SFCP_1164.zip](https://github.com/user-attachments/files/17085459/SFCP_1164.zip)
