### ISSUE TITLE
Sarah doesn't realize she's on Mercury

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1165]
The old meme from launch. Sarah Morgan will say "Not exactly the surface of Mercury, but this certainly is hot" while you are standing on the surface of Mercury.

---

## Details 
By adding a condition of 'Subject.GetIsCurrentLocation(SSol_PMercury_Surface [LCTN:0001B72A]) <> 1' to line 0033A089, this no longer happens.

## Game Version
1.13.61.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Bring Sarah to Mercury, wait for awhile, and observe as she begins to display signs of heatstroke-induced confusion.

**Comment by Deebz96** [comment]
Fix attached:
[SFCP_1165.zip](https://github.com/user-attachments/files/17085721/SFCP_1165.zip)
