### ISSUE TITLE
Cannot rename ships

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#117]
Registered first captured ship "Space Raven", saved and exited game. Loaded save and captured new ship. When going to sell the space raven had a name of "UC cargo hauler". Tried renaming back, it looked like it took it but when back on build screen it was still the hauler name. I was also not able to rename the new ship either.

---

## Game Version
1.7.23

## New Game
Yes

## Reproduction Steps
Once in the frontier,  captured a new ship. Registered and noted the name.  Flew it to another ship and captured it. When going to the space port to register the previous ship had a different name. Could not rename either

**Comment by Constellation-VASCO** [comment]
The most common place I have seen this happen is with the "Crimson Fleet Captain" ships off the Freestar Ranger mission board. I also had this happen recently with a captured House Va'ruun ship.

**Comment by Constellation-VASCO** [comment]
FYI every time I am unable to rename a stolen ship, what I do (on PC at least) is: 
1) Go into the popup for renaming, even though you can't type any characters
2) Just delete characters. Any amount; this still works for me.
3) Save the shorter name, exit that menu, exit ship builder while saving the modification (moving everything to cargo).
4) Re-enter ship builder, and try to rename again. I can now add characters to the ship name.

**Comment by Deebz96** [comment]
This is an engine-level issue related to stealing ships. Out of the scope of the SFCP to fix.
