### ISSUE TITLE
Missing advanced weapon levels

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1172]
Some weapons are missing the advanced tier

---

## Details 
The Eon, Rattler, Sidestar, Equinox, Auto Rivet, Cutter and Arc Welder are all missing the advanced tier. As a result the highest level a player can have in the game at present is Refined.

## Game Version
1.13.61

## Language
English (EN)

## New Game
No

## Reproduction Steps
I don't need to recreate this issue. Anyone playing the game will see that the Advanced tier does not exist in game for these weapons.

**Comment by Deebz96** [comment]
This is not within the scope of the SFCP to fix.
