### ISSUE TITLE
Neon Map Markers Wrong Name

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1173]
Euphorika and Madam Sauvage show up as "Chunks" and "Sleepcrates" respectively

---

## Details 
In SFBGS008.ESM under Worldspace, in 0027CF9E (NeonCity), in Cell 00294F1A [Persistent] the CityMapMarkers for "EuphorikaNeonOrigin" and "MadamSauvage" are incorrectly labeled as "Chunks" and "Sleepcrates" respectively. They show up this way in the game as well.

## Game Version
1.13.61.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Just go to Neon and to those locations. Check the local map after the location is discovered and check the names.

**Comment by Deebz96** [comment]
This should be fixed officially in the update on Monday.
