### ISSUE TITLE
Negotiator Recon Laser Missing Model

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1174]
The Recon laser Sight modification for the Negotiator is missing a model. This means that it doesn't actually have a working laser with this modification attached.

---

## Details 
Just need to add a model file name of Weapons\Rocketlauncher\Lazersight.nif to mod_Rocketlauncher_Laser_ReconSight "Recon Laser Sight" [OMOD:00132A36]

## Game Version
1.13.61.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Get a Negotiator rocket launcher, attach a Recon Laser Sight to it. There is no laser attachment model, and no laser as a result.

**Comment by Deebz96** [comment]
Fix attached:
[SFCP_1174.zip](https://github.com/user-attachments/files/17177480/SFCP_1174.zip)
