### ISSUE TITLE
SSNN Broadcast subtitle issue

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1176]
There is an SSNN broadcast where the subtitle says "A perspective LIST colonist..."  It should say a "prospective"

---

## Details 
There is an SSNN broadcast where the subtitle says "A perspective LIST colonist..."  It should say a "prospective"

## Game Version
1.8.86.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Listen to random SSNN broadcasts.

**Comment by Deebz96** [comment]
This will be fixed in the next release of the mod.
