### ISSUE TITLE
SFCP apparently breaks xlat file for some skills

### ISSUE THREAD

**Issue by ebkarlson404** [Starfield-Community-Patch/Starfield-Community-Patch#1179]
Installing SFCP into the Shattered Space update apparently breaks the xlat files for some of the skills.

### Details

  I'm seeing the problem with Automated Weapon Systems, targetting ControlSystems, Armor Penetration, Targetting, Rapid Reloading Particle beams, Psitol Leadership, Certification, Cellular Regeneration, Decontamination and Martial Arts.  Hovering the mouse over any of those skills reports a "Lookup Failed" error.

### Game Version

1.14.70.0

### Language

English (EN)

### Have you recreated this issue on a new game?

Yes, I can recreate this issue.

### Reproduction Steps

Install the SFCP mod, then start a game, hit 'P' to go to skills and then hover the mouse over any of the skills mentioned above.  One will get "Lookup failed".  Remove SFCP and repeat, and everything is fine.

**Comment by Deebz96** [comment]
We'll be removing the translation files for the next release. Currently, the tools to do these translations are not updated.
