### ISSUE TITLE
Companion conversations + Leadership

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1180]
Same exact issue as the vanilla storygate conversations. If you have the Leadership perk, the two new ones with Shattered Space will never play.

---

## Details 
xx084782 and xx12CCD2. The "WantsToTalk" actor value checks must be changed from ==1 to >=1.

## Game Version
1.14.70.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Bring Andreja to Dazra, or completed the Shattered Space quests and talk to companions.

**Comment by Deebz96** [comment]
Fix attached... sigh.
[SFCP-SS_1180.zip](https://github.com/user-attachments/files/17198303/SFCP-SS_1180.zip)

**Comment by Constellation-VASCO** [comment]
@Deebz96 Wait is that zip an early version of a community patch for Shattered Space? I wasn’t aware one was being made yet.

**Comment by Deebz96** [comment]
It’s only a fix for this bug. A separate shattered space plugin may come later.

**Comment by Constellation-VASCO** [comment]
@Deebz96 On, Thanks for the heads up.

**Comment by Constellation-VASCO** [comment]
Is there a way to get this attached fix on xbox, or will it eventually make its way there? Sorry, just an eager player who took the leadership perk like the night before shattered space launched without being aware of this issue, and ive already put in over a dozen hours since then before realizing this was an issue. Now I am waiting for a fix before beginning shattered space :(

**Comment by Constellation-VASCO** [comment]
Fix appears to work mid-game with Andreja in Dazra. Not checked in Shattered Space or with other companions.

**Comment by Constellation-VASCO** [comment]
I’d like to echo the request for making this Shattered Space dialogue patch available on Xbox.   Is this possible?   Or, if you plan an overall Shattered Space patch with this in it, be happy to wait.   Thoughts?   
P.S. - Many thanks to the SFCP team for your great work!

**Comment by Deebz96** [comment]
Fixed officially.
