### ISSUE TITLE
Vehicle

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1189]
Your mod is not allowing the vehicle to appear and be used that is our purchased from the kiosk

---

## Details 
No technical details other than the vehicle shows after disabling your mod. 

## Game Version
1.14.70.0

## Language
English (EN)

## New Game
No

## Reproduction Steps
Haven't made a new game to see if this can be recreated

**Comment by Deebz96** [comment]
You have an outdated version of the SFCP via the Creations platform. Fully uninstall the mod, then reinstall it.
