### ISSUE TITLE
NPCs have missing clothing

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1195]
Sometimes, clothing will start to disappear.  Hitting F5 and then F9 seems to fix it.  I saw a number of reports that this mod may be the culprit.
Unfortunately, I can't remove it because other mods depend on it.
Not sure about the initial levels, I've been seeing this since I ws at least level 5

---

## Game Version
1.8.86.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Play the game, after a while, it starts to happen randomly

**Comment by linuxgurugamer** [comment]
@Deebz96 Can you explain why you closed this and added the invalid tag?

**Comment by Deebz96** [comment]
This is a commonly reported issue, but it is unrelated to this mod directly, or any other specific mod. It is also not an issue with the vanilla game. This would be an engine-level issue with how the game handles loading content in general.

The exact cause isn’t known, but it seems to correlate with large enough load orders. Or perhaps load orders with mods that do enough of one certain thing. For example, a lot of vram-intensive mods.

Aside from that, this report also lacks specific enough details for any investigation to be done. I can personally play the game indefinitely without seeing this issue, and so can most people. We would need more specific details for any report in general.

**Comment by linuxgurugamer** [comment]
Ok, thank you.
