### ISSUE TITLE
All NPC companion comes with you

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1197]
If you go into allness and have Vasco or the fan as a companion, he comes with you into allness and is there to support you.
I haven't noticed this with other companions.

---

## Game Version
1.14.70.0

## Language
Deutsch (DE)

## New Game
Yes

## Reproduction Steps
If you go into allness and have Vasco or the fan as a companion, he comes with you into allness and is there to support you.
I haven't noticed this with other companions.

**Comment by Deebz96** [comment]
This was a bug specific to Vasco, and it was fixed in SFCP 1.0.0.
