### ISSUE TITLE
Painting in Matteo's room disappears

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#12]
Go to Matteo's room in Constellation upon first visit. There is a painting on the wall that initially appears but if you go too close to it it disappears. I initially wondered if this was a hologram or evidence of a hidden container but I think it's just a textural loading issue.

---

## Details 
Unknown

## Game Version
Base Release

## New Game
No

## Reproduction Steps
Go to Matteo's room
Observe painting
Move closer to painting
Observe painting

**Comment by Constellation-VASCO** [comment]
https://steamuserimages-a.akamaihd.net/ugc/2013726599794798016/2AFDABB56A3B24490C59A4A0BC7BD88199ABDD6F/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false

**Comment by Constellation-VASCO** [comment]
Images attached showing close/far.

Also maybe a separate bug but is it expected that all of my user posts get converted to constellation-VASCO and hence nothing shows up under the "My Issues List" tab? 

-Fletchreborn

**Comment by halgari** [comment]
Embedding images from external source:

![missing](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/assets/654621/94728a39-4cfa-441b-849a-30b45a6f7f61)
![not-missing](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/assets/654621/13bdd7cb-6e8f-4110-8339-a697743b6ebc)

**Comment by TESWartortle** [comment]
Can reproduce. If you get at the right spot, appears to have z-Fighting. Would come back to this once CK available.

![image](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/assets/124397758/466aae19-ce54-4db9-84b3-e3bd1afc67d2)

**Comment by Constellation-VASCO** [comment]
It's possible the painting just needs moving 0.0001 unit away from the wall, or the mesh needs it's bounds recalculating. Neither of which are easy to test without the CK

**Comment by Deebz96** [comment]
No longer an issue as of game version 1.10.32
