### ISSUE TITLE
It is impossible to upgrade the perk

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1205]
It is impossible to upgrade the perk of rifle 2 , all conditions are met, 20 out of 20. After removing the patch, I upgraded the perk .

---

## Game Version
1.14.70

## Language
Английский (EN)

## New Game
Yes

## Reproduction Steps
Start the game, shoot a lot with a rifle .

**Comment by Constellation-VASCO** [comment]
Этот баг появился после установки SFCP

**Comment by Deebz96** [comment]
This would not be an issue with the SFCP. The rifle certification perk is not touched by this mod.

**Comment by Constellation-VASCO** [comment]
Checked the game files. Disabled all my mods(Easy Digipick.esm SeizureOfShips.esm Ship Power Fix.esm Richer Merchants - Credits.esm ). Reinstalled the patch from Nexus. It is impossible to upgrade the rifle perk 2 (cannot be pressed). I remove the patch and the perk is available for upgrade.
