### ISSUE TITLE
Weapon workbench builds glitched into the ground

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1209]
Whenever I build a Weapon Workbench in my ship or at the Dream Home, the legs are in the ground. Trying to use it after being placed results in a "this object is obstructed" error.

---

## Details 
+Affects Weapon Workbench in Build Mode on ships and in the Dream Home
+Using StarUI Outpost Builder

## Game Version
1.8.86.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
1. Go into build mode in ship or Dream Home
2. Select Weapon Workbench from the menu
3. Try to place it anywhere

**Comment by Deebz96** [comment]
#1122
