### ISSUE TITLE
The Heart of Mars Activity Quest

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1211]
Unable to extract / mine The Heart of Mars

---

## Game Version
1.14.70.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Created a new character. Played enough of the game to get the mission. Went to the cave. Still unable to mine the Heart of Mars

**Comment by Deebz96** [comment]
This isn’t a vanilla issue. If you use a cutter, it will work. You may have a mod breaking it.
