### ISSUE TITLE
Компаньоны заслоняют обзор 

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1213]
Companions obscure the view of the player sitting in the pilot 's seat of the ship .

---

## Details 
https://fastpic.org/view/124/2024/1019/_5e6cac91b39300b392322a74f69004de.png.html - Screenshot of the problem

## Game Version
 1.14.70.0

## Language
Английский (EN)

## New Game
Yes

## Reproduction Steps
Take a flight on a ship several times .

**Comment by Deebz96** [comment]
I'm aware of the nature of this bug, but it's not something we can fix. It's an engine level bug. I have detailed what I believe is going on, and sent the report to Bethesda.
