### ISSUE TITLE
Can't rotate items in inventory 

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1218]
With latest update a new has appeared. 

Basically it's impossible to rotate items (which support both axes / 360 rotation) in inventory when using a controller. It will work just a little (with jittery animation) and only in direction. It works normally with items which support only x axes / left-right rotation.

For some reason a whole thing works just fine when vertical sync is on, but then frame generation won’t be available and game will have much lower fps. 
Not to mention vertical sync is off by default.

---

## Game Version
1.8.86.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
1. Have controller connected (I used xbox 4th gen one)
2. Load the game
3. Open inventory
4. Try to rotate any items which support both axes / 360 rotation (basically any guns, food, decorations etc.)

**Comment by Deebz96** [comment]
This would be an engine issue, and is out of the scope of the SFCP to fix.
