### ISSUE TITLE
'Shadows in Neon' quest does not start after 'Where Hope Is Built' quest is finished

### ISSUE THREAD

**Issue by barsuna** [Starfield-Community-Patch/Starfield-Community-Patch#122]
It seems it may have something to do with starting 'Audition' quest - as some reported that restoring to before starting this quest avoids the issue. Talking to ranger on Neon before finishing 'Where Hope Is Built' doesn't seem to be related.

Related thread
https://www.reddit.com/r/Starfield/comments/1687sg8/shadows_in_neon_not_starting_after_finishing/

It is PC/steam version 1.7.23.0

**Comment by Deebz96** [comment]
This seems to no longer be an issue.
