### ISSUE TITLE
Ricardo Bosch's notes not removed after quest

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1222]
Ricardo Bosch's notes not removed after quest from player inventory. Can't be moved anywhere since tagged as quest item

---

## Details 
ID	xx0x0000CCCB (52427)
Editor ID	FFNewAtlantis03_Slate
Type	Slate

Its a New Atlantis intro quest to get the slate for Ricardo from Station RE-939. But after you bring him slate quest finishes but slate not removed from player inventory

## Game Version
1.8.86.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Take quest from Ricardo at MAST.
Go to Station RE-939 at Voss.
Get slate.
Go back to Ricardo and finish quest.
Slate stays in inventory

**Comment by Deebz96** [comment]
#799
