### ISSUE TITLE
Food damage/energy resistance issue.

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1229]
If you eat food with any type of damage resistance, save the game and reload it, the stat occasionally will stay. Or to paraphrase – the effect itself instantly disappears from active effects screen and transforms into DR modified by this effects's value.

---

## Details 
Last tested with food item "Galaxy Lo Mein", ID: 00122E94;

Restores 25 Health;
+300 Damage Resistance for 12m;
+300 Energy Resistance for 12m;

This time, after loading a save, Damage Resist effect transferred into the base value, but Energy Resist remained as effect. However the bug affects all resists, it all seems to be random, but must have some mechanism behind it.

## Game Version
1.14.70.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
1. Sleep in a bed.
2. Eat food with Fortify DR effect.
3. Save.
4. Load.

**Comment by Deebz96** [comment]
This affects any magic effect, period. Seen it apply to the XP boost effect of one of the craftable food items. Also saw a “repulsing” effect get permanently stuck to a companion via a magic effect once.

This is not a bug we can fix, it will need to be addressed on the engine level.
