### ISSUE TITLE
The hammer falls doesnt not begin

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1230]
after speaking with paxton/recieving slate then killing again the hammer falls quest does not start

---

## Details 
fc08 is the previous quest first to the fight first to die fc09 is for the hammer falls
setstage 50(travel to hope town) is the first step

## Game Version
1.14.70

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
complete ryujin faction first then begin fc quest

**Comment by Deebz96** [comment]
Did not experience this on any playthrough, and I always did the FC questline last. We'll need more detailed reproduction steps to investigate.
