### ISSUE TITLE
The Den is added to player inventory

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#132]
When the player registered a new home ship at the Den, then in the same dialogue changes the Home Ship, then sells the newly registered ship - The Den is added to the players inventory. 

---

## Game Version
1

## New Game
Yes

## Reproduction Steps
Pre-req: Player has an unregistered ship as their home ship.

1. Fly to The Den
2. Talk to the Starship Technician
3. Register the ship referenced in the pre-req
4. Change the Home Ship
5. Sell the ship from step 3
6. Modify a ship 
7. Close dialogue 
Actual: The Den is added to the player inventory as Home Ship; User can’t change Home Ship or leave station; requires loading previous save

**Comment by Deebz96** [comment]
This was fixed by Bethesda.
