### ISSUE TITLE
Typo in Penetrator Rounds description

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#136]
In the English language, there is a typo in the description for the Hard Target's penetrator rounds; the word "Incredibly" is misspelt as "Increadibly". This may also affect other weapons that can be given Penetrator Rounds.

---

## Details 
546CC - HardTarget WEAP
128C4C, 128C6C, 1298AE, 12A0B0, 12A784, 12D03D, 133A6B - Penetrator Rounds OMOD

## Game Version
1.7.23.0

## New Game
Yes

## Reproduction Steps
1. Head to any weapon workbench, such as one in Laredo Arms by using the console command "coc CityAkilaCityLaredoFirearms"
2. Obtain a Hard Target, you can do so with the command "player.additem 546CC 1"
3. Use the nearby weapon workbench and select the Hard Target
4. Click on "Magazine and Battery" and hilight the Penetrator Rounds option

**Comment by Pickysaurus** [comment]
This typo applies to:
- co_gun_mod_HardTarget_Mag_Penetrator[000454B2]
- co_gun_mod_Lawgiver_Mag_Penetrator[00057561]
- co_gun_mod_MagSniper_Mag_Penetrator[00045BAF]
- co_gun_mod_Razorback_Mag_Penetrator[00044C30]
- co_gun_mod_Regulator_Mag_Penetrator[00057579]
- co_gun_mod_Tombstone_Mag_Penetrator[00044C4D]
- co_gun_mod_UrbanEagle_Mag_Penetrator[0007C747]

**Comment by Pickysaurus** [comment]
https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/commit/a51cf6dbb83968aa19b2ab8b3bb16811260bd46d
