### ISSUE TITLE
Multitude of Outpost Issues

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#140]
A list of things ive noticed so far.

I would keep going but I think details has a character limit? 
You guys might want to remove that for this website site because I cant type anymore, So I had to start removing pronunciations just to get that much to fit

---

## Details 

Snapping certain storage containers wont/dont always just stack they like to off center or try to stack on lower placements. They clearly have to many snap positions with this Build UI the controls are horrible you have to WASD to pan around which means doing finer input is hard af to do, you cant zoom out very far, you cant select more then one object. Rotating things is next to impossible it just wants to snap to stack and not spin especially when you have more then one item placed. Storage Containers will read 6% or some value of capacity even though THERES NOTHING IN THEM!  You cant place Objects that you should clearly be able to put ontop of Habs or Air Lock steps ontop of like Powered Switches, Theres no way to connect a powered Switch to anything! Like it just doesn't have functionality it was added and forgotten? The whole Wiring of Lights and or turrets is just dumb some times you have to and some times you dont I dont know if its because of solar arrays vs nuclear power? aaaaaaaaaaaaaaaaaaaaaaaaaa

## Game Version
1.1

## New Game
Yes

## Reproduction Steps
go build a base and start playing with with stuff?
Im sure you know that landing pads for outposts are bugged af too. Ships wont land on them. If you had a post close to where you first land in that 5000x5000 square plot. Decide you dont like that spot, delete the outpost and move to another location within that same 5000x5000plot. Your ship will Always land at that first spot! Regardless if you have built a landing pad; It will not land on a pad even if you made one some 1400 units. It doesn't matter which landing pad you use either or ship size ( to my knowledge ) atleast thats been my experience.

**Comment by bWildcard** [comment]
Some times when you pull up the build menu your cursor sits and spins and navigating menu options becomes impossible.
You must build in 1st person, or start building in first person before you can use 3rd person camera.

The cursor has a dot in the center and two half circles one at the top and one at the bottom that will slowly fill Right-To-Left.


![image](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/assets/43270488/9fc9389d-78cc-46a1-930c-c2522ea90744)
