### ISSUE TITLE
Max Rejuvenation Skill Doesn't Work in Combat

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#141]
Max Rejuvenation Skill is not working as intended.
It should heal you while in combat, but it doens't. 

---

## Details 
Rejuvenation Skill

## Game Version
1 (11.09.23)

## New Game
Yes

## Reproduction Steps
Just level up your Rejuvenation Skill like normal.

**Comment by Pickysaurus** [comment]
https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/commit/a51cf6dbb83968aa19b2ab8b3bb16811260bd46d
