### ISSUE TITLE
ECS Constant Disappeared

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#147]
The orbit location for the ECS Constant remains but the ship itself disappears making it unable to be docked to and any quests to be completed.
I have had attacking ships from the [Wanted] background events not appear in space, but still be referenced and their start position targeted by my turrets despite the ships not being there one time, and that may be related. 

---

## Game Version
Full Release Version

## New Game
No

## Reproduction Steps
Start the quests on the ECS Constant, go to Hopetown and organise to repair the grav drive on the ECS Constant, complete that quest, pick up the quest from Abe to contact family and Janet to leave the Constant, leave the Constant and deliver the message to Abe's relative at The Red Mile, return to find the ECS Constant missing.

**Comment by CErratum** [comment]
The ECS Constant moves around after you have the grav drive installed. There should be a mission item in your list with the current location of the Constant; check if that points to the correct location.

**Comment by Deebz96** [comment]
#431
