### ISSUE TITLE
Rapid Reload Skill Bug

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#159]
Whenever you have any throwable item equipped (i.e. a grenade or a mine), it deactivates the skill.

---

## Details 
This has been reported on Reddit by multiple users. It affects all ranks of the Rapid Reload skill. If you take the skill, you should see a 30% reduction in your reload time. However, if you have a throwable item also equipped (grenades) the skill does not function. If you unequip your grenade, you will immediately notice the improved reload time.

## Game Version
1.7.23.0

## New Game
No

## Reproduction Steps
Simply time your reload, on the same gun, with and without the skill (noting: each rank affects a different type of gun). If you have a throwable equipped, you will see they are identical. If you unequip your throwable, you will see the 30% reload speed improvement.

**Comment by Bobbyclue** [comment]
Looks like conditions on the "Mod Weapon Reload Speed" perk entry point when set to run on index 1 has the throwable slot may take precedence over other weapons, with index 1 likely being the weapon itself. For a potential fix I'd try setting the index to the actor holding the weapon and seeing if there are conditions that can grab the correct weapon from there (eg. does IsWeaponInList still exist?)
