### ISSUE TITLE
Ship Services Technitian Spawning Underwater -Neon

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#163]
After recieving a quest to deliver a parcel to Neon's SST they were stuck underwater far from the landing area and was inaccessable. Restarting game/console/save did not resolve this issue

---

## Game Version
1.7.23.0

## New Game
No

## Reproduction Steps
unknown but likely relates to parcel mission (Deliver Star Parcel package to Neon)

**Comment by Pickysaurus** [comment]
Fixed in game update 1.8.83.0
