### ISSUE TITLE
Nova Galactic Staryard Missing

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#165]
The Nova Galactic Staryard is not in orbit around Luna and cannot continue main story mission "The Old Neighborhood"

---

## Details 
I am stuck on the main quest "The Old Neighborhood". The problem is that the Nova Galactic Staryard is missing. When I arrive in Luna, the station is not there. I have its symbol in the HUD but it reads as 3630 km away. If I fly towards it for about 20 km, it appears behind me at 18 km, but that icon is not targetable. The original one is still there at 3600+ km, but there is no visible representation of the station at all.

Also, on the missions log it shows a green check mark next to "Dock with Nova Galactic Staryard" like I have already completed that step even though I have not. My current objective is "Find any clues about Moara".

I have tried restarting, landing on different planets in various different systems, loading a previous save game, returning with different ships and just about anything else I could think of. Nothing has worked. I attempted to fly the 3600+ km in real time but was only able to get within 2475 km and then the distance started increasing again.

## Game Version
E235D2B4 v1.7.23.0

## New Game
Yes

## Reproduction Steps
It cannot be reliably re-created every time, but it seem highly likely to occur if you visit the Nova Galactic Staryard before you are on the actual step in the quest "The Old Neighborhood" that requires you to dock there.  However, when attempting to recreate it several times from saves, it did happen once without me ever having visited the station at all.

**Comment by Deebz96** [comment]
This is a general issue with space POIs, and seems to be on the engine level. Out of scope for the SFCP to fix.
