### ISSUE TITLE
The game starts minimized and won't maximise.

### ISSUE THREAD

**Issue by Tovrin** [Starfield-Community-Patch/Starfield-Community-Patch#168]
The game starts minimized and won't maximise for any reason ... except just persisting with shortcut options.  

Reproduction: Seems to be related to full-screen optimising and high DPI settings, but I've had it persist even after I've checked those boxes too.  It only seems to happen during the first run of the day and just works after that.

Platform: Steam (PC)

Sorry, but teh main website doesn't display the form, so this is the best I can do.

**Comment by Constellation-VASCO** [comment]
Could raise this though the site now, but there is no category for this issue.  It's more like a "general executable" issue.  It prevents you getting into the game itself.
