### ISSUE TITLE
Error Code when using terminal

### ISSUE THREAD

**Issue by eckonode** [Starfield-Community-Patch/Starfield-Community-Patch#17]
## Details
Game throws error code: STAT "(FF01B287).

This code changes randomly depending on the action you were performing when entering the terminal.
## Game Version
1.7.23.0

## New Game
No

## Reproduction Steps

1. Must be in game and not on main menu.
2. Open terminal using Tilda Key  _"~"_
3. Click Right mouse button.
4. To get a different code, perform an action then open terminal and right click mouse button.

**Comment by dragonjet** [comment]
Usually we call it the console, and that is not an error message.
It just says when you are currently selecting.

sometimes you have to get near the object you want to select before it gets recognized
at far away it might select someone invisible in between, mostly mists and other effects

you can also try using your mousewheel while still hovering on the item you want to select, this will scroll past what the cursor raycast hits.

**Comment by eckonode** [comment]
Guess i will close this then. Thanks!
