### ISSUE TITLE
Dropped items vanishing as soon as being dropped

### ISSUE THREAD

**Issue by CansecoDev** [Starfield-Community-Patch/Starfield-Community-Patch#171]
Dropping items from the inventory vanish out of existence instead of being dropped in the floor.

## Details

I specifically noticed this happening while dropping items at the Dream Home, but it must be related to something else because it keeps happening, even after leaving that area, passing time and in other places.

## Game Version

1.7.23.0

## New Game

No

## Reproduction Steps

I have not being able to reproduce the trigger of this issue on a new game, but I'm attaching the save where it is happening, and the closest previous save from that play through where the bug is not happening.

Load the attached save from cant_drop_items.zip, then drop an item to the floor.

[cant_drop_items.zip](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/files/12581530/cant_drop_items.zip)
[can_drop_normaly.zip](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/files/12581535/can_drop_normaly.zip)

**Comment by Alex-Ashfold** [comment]
[Save71.zip](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/files/12651544/Save71.zip)

Having the same issue with this save
