### ISSUE TITLE
Massive FPS drop when exiting menus or quicksaving

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#172]
Massive FPS drops when exiting in game menus, main menu, dialog menu, or sometimes after quicksaving. Game runs on the usual 40-60fps then drops to an unplayable 10-15fps. Game rendering seems to be even blurrier than usual. Happens like 30% of the time in my case. It doesn't matter if I just started the game or playing long.
Only consistent "fix" so far is restarting the game.
System specs is negligible it seems, happens on PC high end or low end.
Issue is described further in several reddit threads:

https://www.reddit.com/r/Starfield/comments/1675u41/terrible_menu_lag/
https://www.reddit.com/r/Starfield/comments/16867zc/performance_issues_after_entering_the_menu_screens/
https://www.reddit.com/r/Starfield/comments/167aud6/when_quicksaving_or_opening_the_menu_sometimes_my/
https://www.reddit.com/r/Starfield/comments/16a7930/character_menu_frame_dropping/
https://www.reddit.com/r/Starfield/comments/169c9z6/fps_bug_opening_and_closing_my_menu_is_causing_a/

---

## Game Version
v1.7.23.0

## New Game
Yes

## Reproduction Steps
Play normally then open a menu or quicksave. Game drops in FPS. Happens like 30% of the time in my case.

**Comment by haywirephoenix** [comment]
The engine scales the base resolution up to max when in the pause menu.

In normal gameplay, it indicates 1080 -> 3840, hit pause and it goes up to 3840 -> 3840

See for yourself:

https://www.pcgamer.com/nvidia-dlss-indicator/

Dynamic Resolution setting doesn't affect this behaviour.

The only ini setting I've found relating to this is bTempMenusCanDisableFSR2 but it doesn't seem to do anything.

**Comment by CarrotM15** [comment]
> The engine scales the base resolution up to max when in the pause menu.
> 
> In normal gameplay, it indicates 1080 -> 3840, hit pause and it goes up to 3840 -> 3840
> 
> See for yourself:
> 
> https://www.pcgamer.com/nvidia-dlss-indicator/
> 
> Dynamic Resolution setting doesn't affect this behaviour.
> 
> The only ini setting I've found relating to this is bTempMenusCanDisableFSR2 but it doesn't seem to do anything.

What ini file can I see or edit this bTempMenusCanDisableFSR2? I wanna try it. Thanks

**Comment by Constellation-VASCO** [comment]
One observation I can make of this issue is that: Are the users hitting their VRAM limit when they open the menu?

I notice that anytime the inventory/pause menu is open, there is a significant VRAM hit in the game.

**Comment by haywirephoenix** [comment]
> > The engine scales the base resolution up to max when in the pause menu.
> > In normal gameplay, it indicates 1080 -> 3840, hit pause and it goes up to 3840 -> 3840
> > See for yourself:
> > https://www.pcgamer.com/nvidia-dlss-indicator/
> > Dynamic Resolution setting doesn't affect this behaviour.
> > The only ini setting I've found relating to this is bTempMenusCanDisableFSR2 but it doesn't seem to do anything.
> 
> What ini file can I see or edit this bTempMenusCanDisableFSR2? I wanna try it. Thanks

StarfieldCustom.ini:

```

[Display]
bTempMenusCanDisableFSR2 = 0
```

**Comment by haywirephoenix** [comment]
> One observation I can make of this issue is that: Are the users hitting their VRAM limit when they open the menu?
> 
> I notice that anytime the inventory/pause menu is open, there is a significant VRAM hit in the game.

Yes my VRAM fills up when in that menu. At first I thought it was the player model but check the DLSS indicator, it's upscaling. And I can see why they did it - without it upscaling the menu, the character and weapon render textures flicker at the lower resolution. 

If the upscaling during pause is prevented the VRAM won't fill up and the game wont begin to lag and black out.

**Comment by CarrotM15** [comment]
> > The engine scales the base resolution up to max when in the pause menu.
> > In normal gameplay, it indicates 1080 -> 3840, hit pause and it goes up to 3840 -> 3840
> > See for yourself:
> > https://www.pcgamer.com/nvidia-dlss-indicator/
> > Dynamic Resolution setting doesn't affect this behaviour.
> > The only ini setting I've found relating to this is bTempMenusCanDisableFSR2 but it doesn't seem to do anything.
> 
> What ini file can I see or edit this bTempMenusCanDisableFSR2? I wanna try it. Thanks

Yeah, all it does is disabling FSR on menus which didn't help at all.

> > > The engine scales the base resolution up to max when in the pause menu.
> > > In normal gameplay, it indicates 1080 -> 3840, hit pause and it goes up to 3840 -> 3840
> > > See for yourself:
> > > https://www.pcgamer.com/nvidia-dlss-indicator/
> > > Dynamic Resolution setting doesn't affect this behaviour.
> > > The only ini setting I've found relating to this is bTempMenusCanDisableFSR2 but it doesn't seem to do anything.
> > 
> > 
> > What ini file can I see or edit this bTempMenusCanDisableFSR2? I wanna try it. Thanks
> 
> StarfieldCustom.ini:
> 
> ```
> 
> [Display]
> bTempMenusCanDisableFSR2 = 0
> ```

Yeah, all it does is enable/disable FSR on menus which didn't help at all.

**Comment by CarrotM15** [comment]
> One observation I can make of this issue is that: Are the users hitting their VRAM limit when they open the menu?
> 
> I notice that anytime the inventory/pause menu is open, there is a significant VRAM hit in the game.

I wonder If this can be fixed through modding through? Not sure BGS is even aware of this issue so I'm not expecting a fix in a near future patch. But who knows? Fingers crossed.

**Comment by haywirephoenix** [comment]
There must be a method that triggers the change when the game is paused. As SFSE matures I'm hoping it will be uncovered but the offset could be found
