### ISSUE TITLE
Matters at Hart Bug

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#175]
Matters at Hart Bug

---

## Details 
Matters At Hart (Sam Coe Companion Mission) - Mission lands me on the Landing Pad if I am using the Razorleaf. My ships are also currently bugged. Sam Coe and His Daughter are completely inseparable from the Razorleaf (The Mantis). Even when the ship has been sold and no longer exists Cora is stuck on the ship indefinitely so I have to keep this ship out for this mission. It lands me with the cargo bay closed. The correct place to land during this mission is in a field outside of the syndicate camp, this is where Sam Coe is. Cora walks through the camp from the landing pad inside the camp and you are forced to prematurely fight the syndicate. You then have to walk to the actual landing point in the field to star the quest. Quest then runs fine until you agree with Lillian to meet you at your ship where she will not be, Cora has also disappeared. The quest can no longer progress, sam is stuck as a companion.

## Game Version
12051365

## New Game
No

## Reproduction Steps
n/a i am 70 hours in.

**Comment by Aurelianis** [comment]
Same as https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/issues/885
This was fixed in v1.10.31.0
"Matters of the Hart: Fixed an issue that could cause the player to arrive in the middle of the Victor compound."
