### ISSUE TITLE
Breaking The Bank Bug

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#176]
Breaking The Bank Bug

---

## Details 
Breaking The BANK (SysDef Undercover Crimson Fleet Mission) - The First Step of this Quest is travel to 'The Siren of The Stars'. No matter how many times you travel to it it will not prompt the next quest step to dock with it. You can dock with it but the game tells you to get back on your ship to travel to the very ship you are docked with. Quest will not progress past this point.

## Game Version
12051365

## New Game
No

## Reproduction Steps
n/a i am 70 hours in

**Comment by Deebz96** [comment]
Not enough details to troubleshoot.
