### ISSUE TITLE
The Hammer Falls Bug

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#180]
The Hammer Falls Bug

---

## Details 
The Mission itself is fine, but once you mission completes you are meant to receive ranger gear, a ship and the achievement for finishing the story line. I receive the ranger gear but not the ship nor the achievement. All quest steps are complete according to mission log, final step being to 'Talk to Marshall Blake'.

## Game Version
12051365

## New Game
No

## Reproduction Steps
n/a

**Comment by Deebz96** [comment]
More info on #183
