### ISSUE TITLE
Unable to purchase items from Jacquotte Laguerre in Paradiso

### ISSUE THREAD

**Issue by DorsalAxe** [Starfield-Community-Patch/Starfield-Community-Patch#185]
When initially talking to Jacquotte Laguerre at the Paradiso gift shop, all of her dialogue works fine and you can purchase items normally. Afterwards, you can ask Emilian at the front desk about why she is so rude to guests. This changes Jacquotte's dialogue to slightly soften her tone towards the player. Unfortunately this also seems to completely break the ability to purchase items from her as selecting the option "Lets see what you have for sale" simply does nothing other than reset the list of dialogue topics.

**Comment by atmichalak** [comment]
This breaks the side Mars/Cydonia quest _Media Sponge_ given by Mitch Benjamin. I've tried resetting the NPC's AI using ```resetai``` and both ```disable``` and ```enable```. The quest item in question, the book Dragonstar Force 01 is in her personal inventory rather than the vendor storage box located under the floor, so it cannot be looted as a temporary measure. Using ```showinventory``` and ```removeitem``` does not move the quest along.

**Comment by Constellation-VASCO** [comment]
I've just fixed this: [https://www.nexusmods.com/starfield/mods/11056]
 
The condition set on 0004844A was supposed to be equal to 1, as this is the more "friendly" set of responses, but the game has this as equal to 0, the same as the other set of responses. That meant there were no possible responses after speaking with Emilian Vasilescu about Jacquotte Laguerre and her vendor dialogue was broken.
 
Trying to make this change in the CK resulted in a crash for some reason, but xEdit worked.

**Comment by Deebz96** [comment]
Noticed this one awhile back too, and forgot about it. Space Karens rejoice. :P

Fix provided by: https://next.nexusmods.com/profile/xtcrefugee/
