### ISSUE TITLE
Quest-bricking

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#187]
Executive Level for Ryujin Industries will NOT start, and "All That Money Can Buy" Quest for Constellation will NOT start. Multiple Reddit threads, steam forums posts about these quests being bugged. "Into The Unknown" also is bugged. 

My instances were; I completed the second to last mission for Ryujin Industries "Sabotage" I should have been immediately granted "Executive Level" I was not, instead I was granted with NONE of the NPCs talking to me at all, they would just stare at me and look away. I tried reloading my save, closing my game, restarting my PC, and even attempted to use Console Commands to force the quest, I was met with "Unable to start quest". For Constellation, I completed Back To Vectera, The Empty Nest, then "Into The Unknown", after completing "Into The Unknown" I was suppose to be granted with "All That Money Can Buy" Instead I was not, and trying the same trouble shooting tips from my previous encounter with this bug, those two lines are now broken.  

---

## Details 
All That Money Can Buy Quest ID: 002c1c9b 
Executive Level Quest ID: 0018B717 

## Game Version
12051365

## New Game
No

## Reproduction Steps
I haven't been able to recreate the issue as I have since just stopped playing the game. From community posts, even though mine was the opposite of the report from steam user: Hermann. His issue revolved around Ularu and killing her in the quest Sabotage, which locked him out of "Executive Level" mine was the opposite as no one died, and I still got locked out of Executive Level. As far as "Into The Unknown" and "All That Money Can Buy" quests from Constellation its a mixed bag of different things from multiple community posts.

**Comment by Constellation-VASCO** [comment]
If more information is required please let me know

**Comment by itsdinkd** [comment]
+1 stuck on not getting either of these quests as well.

**Comment by itsdinkd** [comment]
running setStage does nothing. startQuest for either returns 'failed' message.

**Comment by BBBBAface** [comment]
having the same issue described, 'Sabotage' just ends and no other quests are started, console commands do nothing to remedy the issue

**Comment by Constellation-VASCO** [comment]
This quest is very buggy when you kill Ularu prior to Sabotage - there seems to be a check to make sure she is alive before allowing the following quests to start, even with console commands.  What worked for me was finding her with [prid 2BA8A1] and resurrecting her - then the quest flows properly even acknowledging her "death."  After I was done I just killed her a 2nd time :-P

**Comment by Aurelianis** [comment]
This was fixed in v1.10.31.0
"All That Money Can Buy: Fixed an issue that could prevent this from starting if all of Ryujin Industries questline was previously completed."
