### ISSUE TITLE
Ship Disappearing post Edit

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#188]
Multiple times now, Anytime I edit a ship and finish building, my ship will not load on the landing pad at all. Additionally, this would disable Fast Travel/flying to other planets. "you cannot fast travel at this time." Swapping parts, swapping ships, moving instances, nothing rectifies the issue. Only option is revert to previous save.

---

## Details 
Occurs/Can occur on any platform, notably for me occurred on Hopetech, personal and New Atlantis landing pads

## Game Version
1.7.23.0

## New Game
Yes

## Reproduction Steps
Edit the ship at a station numerous times as you play, it will eventually happen.

**Comment by Constellation-VASCO** [comment]
https://www.reddit.com/r/Starfield/comments/16c7asb/help_ship_disappeared/ video of what i mean

**Comment by Constellation-VASCO** [comment]
Can confirm this happened to me as well. Current theory is this only happens when you modify a "captured" enemy ship. It's not clear but it seems like even moderate changes like upgraded weapons, shields etc... can trigger this bug. In my case I captured an enemy ship, completely tore it down refunding all existing parts for a small starting budget.
After completing the ship and setting it as my home ship, I was unable to see it on the launch pad. I tried swapping home ship with other ships that were visible in several different places: staryard, outpost, New Atlantis. Nothing worked. Also tried various actions that should make the game reset and render the entire ship such as changing parts, moving parts etc... Nothing has worked. Additional discussion on this issue here:

https://steamcommunity.com/app/1716740/discussions/0/3824174193423630546/?ctp=2

Absolutely frustrating bug. I spent ~800k or more on the ship I cannot now use. Primary suggestion to avoid this bug seems to be to only modify and build new custom ships on a ship you have purchased.

**Comment by Constellation-VASCO** [comment]
I'll buy you drinks all night for this alone !!!!

**Comment by Constellation-VASCO** [comment]
I had the same experience as THeFireBirdMan, I was forced to roll back to a much earlier save.   I have another captured ship in respect of which I fixed the invisible problem by simple editing. But ever since then, when I make that not my home ship I get glitches like the inventory has disappeared ,  I dont have the "R Cockpit" option at the entry hatch,  and when I return to the "Modify My Ships" screen the modded stolen ship is still shown as my home ship.  So captured ships have lots of issues.

**Comment by Deebz96** [comment]
This would be an engine issue. Unfortunately, out of the scope of the SFCP to fix.
