### ISSUE TITLE
Pre-order bonus's missing

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#189]
Pre-order skins missing from applicable items

---

## Game Version
1.7.23.0

## New Game
Yes

## Reproduction Steps
Just make a new character and try to apply your pre-order bonus skins.

**Comment by Constellation-VASCO** [comment]
I have my pre-order bonuses... And I'm playing on steam... Have you tried to change the skin of the deep mining pack/helmet/laser cutter to the Old Mars skin on a suitable workbench?

**Comment by Aurelianis** [comment]
This is really not anything that SFCP can help with. You would need to contact the place of purchase if you did not receive what you paid for.
