### ISSUE TITLE
Sleeping Vasco blocks doorways

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#193]
In two instances with my ship design "sleeping" Vasco has been blocking doorways on board.

In one instance he has repeatedly blocked the doorway to the docking port, which made exiting on foot impossible (work-around through the pilot seat).
In another instance he has blocked access to the small compartment inside the armory.

---

## Game Version
1.7.23.0

## New Game
No

## Reproduction Steps
- Have Vasco as companion 
- Design a ship with a 2x1 armory behind the cockpit and maybe a docking port (top) behind that.
- Be in space or dock at a docking location.
- Vasco will likely be in the way.

**Comment by Constellation-VASCO** [comment]
I've found this is really common for me. Armory or command station seem to be worse offenders. Though not sure if that's a red herring and it's something else triggering it.

**Comment by Constellation-VASCO** [comment]
This is an issue for me as well. Vasco will spawn inside the ship into his sleeping area to what looks like the floor one level up from the dock entrance. If a double-decker bridge is constructed he will almost always spawn in the floor in front of the doorway and block the entrance to the second deck.

**Comment by Constellation-VASCO** [comment]
Absolutely. I don't know what console players do but on the PC I sometimes have to use TCL (toggle collision) to get past him.

**Comment by Constellation-VASCO** [comment]
This should be fixed in game version 1.10.30. Vasco should now stay in the landing bay where he belongs. At least in theory.

**Comment by Aurelianis** [comment]
Fixed in v1.10.31
"Fixed an issue that could cause Vasco to appear incorrectly in the player's ship."
