### ISSUE TITLE
Items in containers disappear on ship re-design

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#194]
Weapons/Suits disappear and are lost completely from cosmetic ship containers when the ship is modified.

---

## Game Version
1.7.23.0

## New Game
No

## Reproduction Steps
- Have a ship with an armory or a computer core.
- Place items in the armory container/mannequins or the computer core storage crate.
- Fly to another location with ship engineer (in this case the Red Mile).
- Re-design the ship and save it.
- Some Items are moved to your inventory, but items placed inside these containers can go missing forever.

**Comment by Constellation-VASCO** [comment]
Supposedly this was fixed in Bethesda's latest patch

**Comment by Constellation-VASCO** [comment]
Make sure they haven't been moved to your cargo bay.

**Comment by Pickysaurus** [comment]
Fixed in 1.7.33 of the base game:
> Displays: Fixed an issue that would cause displayed items to disappear when applied to in-ship mannequins.
> Displays: Fixed an issue that would cause items stored in Razorleaf Storage Containers and Weapon Racks to disappear after commandeering another ship.
