### ISSUE TITLE
VASCO often missing when active companion

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#197]
When traveling to planets, if VASCO is the player's active companion, he will often not show up to accompany the player. Possibly related to https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/issues/86

---

## Game Version
1.7.23.0

## New Game
No

## Reproduction Steps
- Take VASCO as active companion
- Fast travel to different planet surfaces

**Comment by Deebz96** [comment]
This was fixed officially by Bethesda.
