### ISSUE TITLE
Legacy's End - UC Side - Quest unable to proceed

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#198]
I am running the Legacys End questline and chose to side with the UC. Upon making it to the Command Center in the Key, the quest marker is in the middle of the room on the floor, while delgado is in a room above behind a locked door that I can't open. It appears I can look at Delgado and the UI appears to think its possible to talk with him, but pressing E doesn't start any conversation.

---

## Details 
Researching this issue, it appears to be widespread.

It appears that some people have been able to resolve this issue several ways, including Clearing a bounty with the Crimson Fleet and returning to this location and reloading the instance.  Unforetunately, I do not have a bounty with the CF and I have reloaded the instance several times to no avail.  Still broken!

Things I have tried:
-Selecting a new quest and then reselecting the Legacys End.
-Getting in my starship and jumping to another system, then back.
--While doing this I tried to unselect and reselect the legacys end questline

I am stuck! Help!

## Game Version
PRODUCTION

## New Game
No

## Reproduction Steps
This quest is extremely long and has a ton of Roleplay regarding it.  I would assume some combination of the role-play I have done has broken this quest some how.  Which steps I took specifically, I am unsure, nor am I sure how to identify the specific tree that I have traveled down.

**Comment by Aurelianis** [comment]
Fixed in v1.97.4.0
"Legacy’s End: Fixed an issue that could prevent interacting with Delgado when he was behind the glass inside in the command center of The Key."

**Comment by Constellation-VASCO** [comment]
I don't think this is actually resolved. I am still running into this exact same issue.
