### ISSUE TITLE
Should there be a LICENSE?

### ISSUE THREAD

**Issue by nickgerace** [Starfield-Community-Patch/Starfield-Community-Patch#2]
Expanding upon the title a bit, should there be a [LICENSE](https://opensource.org/licenses/) for this project? If so, might it be better to wait to learn more about Starfield's licensing, community, legal, etc. information upon release?

For context, I have been a _user_ of similar patches for BGS games in the past, so these might be rudimentary questions.

EDIT: It looks like [MIT may have been used in testing](https://github.com/Starfield-Community-Patch/skyrim-community-patch/blob/main/LICENSE) and likely for the Skyrim-equivalent patch as well.

**Comment by Pickysaurus** [comment]
Yes, the license will be added a bit later on, there's no content yet so there's nothing to license.

**Comment by Pickysaurus** [comment]
https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/blob/main/LICENSE
