### ISSUE TITLE
Security dialogue has wrong condition checks

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#200]
Both Neon Security and Paradiso Security share their respective unique arrest dialogue, so a Neon guard can announce themselves as Paradiso Security and vice versa. It seems there are no recordings for the guards to speak the wrong dialogue, so when it fires there is no audio and the guard's lips remain sealed.

---

## Game Version
1.7.23

## New Game
Yes

## Reproduction Steps
Get arrested in Neon or Paradiso. It's one of several possible dialogues, so may take several attempts to hear it.

**Comment by Constellation-VASCO** [comment]
Just to add that it looks like all the other security groups are affected too. I've had UC Security silently announce themselves as Neon Security, and Ryujin Security say "Protect the guests at all costs!" when refusing to yield.

**Comment by Deebz96** [comment]
This seems to be fixed officially.
