### ISSUE TITLE
Unexpected NPC Hostility and Bounty During Ryujin Mission

### ISSUE THREAD

**Issue by obrunopolo** [Starfield-Community-Patch/Starfield-Community-Patch#201]
While playing through a mission where I had to attend a meeting in Ryujin Tower, I encountered an issue where NPCs suddenly turn hostile without any clear reason. This happens after a distant explosion sound, followed by a red damage indicator around the crosshair, and a 15,000 bounty added to my character. This issue has been consistent across multiple reloads of the same save.

Specifically, I've noticed that I need to be close to the NPC Masako for the event to trigger. I tried troubleshooting using console commands to identify the source of the explosion, but couldn't find anything. If I stay near Masako for a few minutes on that save, the security team eventually kills me. I suspect this issue could potentially happen in other scenarios as well.

SPOILER AHEAD

I believe this could be related to the mission where you have to break into Ryujin office. I may have left some ground mine somewhere. This is pure speculative tho.

**Comment by Aurelianis** [comment]
Closing this as unable to reproduce. Completed this mission at least a dozen times and never encountered hostility. If you had left a mine from the previous mission, then it makes complete sense that they would turn hostile when the mine detonated.
