### ISSUE TITLE
Poor Air Quality status not going away

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#21]
Character was exploring in a poor air quality environment. After returning to a clean air environment (ship) the warning did not disappear, although does not result in the player risking diseases and the warning does not cause the player suit to beep. Once exiting the ship in New Atlantis with the warning still active, the warning constantly beeps and results in periodic diseases/ailments. I have not yet found a way to fix it outside of console commands

---

## Details 
Permanently stuck with the "Poor Air Quality" warning (spell 00163FE7). Appeared after completing the Lab mission on Kreet. I was exploring a compound not too far from the lab and ended up with the environmental warning. Boarding my ship, travelling, going to Atlantis, visiting a doc, reloading the save in question has no impact on removing the warning.

## Game Version
1.7.23.0

## New Game
No

## Reproduction Steps
I've not encountered the weather conditions again on Kreet (I reloaded an earlier save) to be able to replicate it. Recalling the activities I was doing at the time, I think I did switch helmets at one point during the portion of play when the bug occurred, which may or may not be relevant.

**Comment by Constellation-VASCO** [comment]
I've not been able to recreate this exactly, but partially by being aboard my ship while on the surface of Kreet. A sandstorm hit outside but I was getting the poor air quality warning inside the ship. When I stepped out into the actual sandstorm the warning disappeared. When I re-entered my ship, the warning returned. Leaving Kreet and going to New Atlantis fixed it

**Comment by Constellation-VASCO** [comment]
Can confirm the exact same thing happened on my save. Kept getting Lung Damage in New Atlantis as a result of this.

**Comment by Pickysaurus** [comment]
> Hi Pickysaurus.
> 
> I tried to add some detail to Issue #21, regarding the watch Alarm, but was unable to submit the comments. Can you please grant me the appropriate permissions to do so?
> 
> 
> 
> Issue #21 Details - Regarding Watch Alarm trigging from Air Quality / Environmental Damage.
> 
> 
> 
> I've run into the same issue with the air quality. The alarm would not turn off no matter what I did. I had purchased new space suits upon arrival from Mars to New Atlantis and went back to Mars again. After fast traveling the game does not automatically put you in a space suit when entering into a poor air quality environment. You have to quickly put your space suit on or reboard your ship. When I put on the new suits, the Alarm would not go off, even when I returned back to my ship. My game play was like this for about 3 hours before placing the game on a long pause, to run an errand. Alarm was off when I returned.
> 
> 
> 
> I'll keep track and report any further issues or supporting details as I progress through the game. I WFH full time, so I can play this all day long if needed. I look forward to working with you all.
> 
> 
> 
> Thank you.

**Comment by Aurelianis** [comment]
Fix is here:
https://www.nexusmods.com/starfield/mods/8629

**Comment by Aurelianis** [comment]
This was fixed by Beth in v1.10.32
