### ISSUE TITLE
"Goat" translation typo in german translation

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#212]
The german translation of "goat" is wrong, in the game it appears as "Zriege" the right translation would be "Ziege"

---

## Details 
the word gets used in the romance/engagement quest with andreja

## Game Version
1.7.29

## New Game
Yes

## Reproduction Steps
engage in any conversation in which the word "goat" is used

**Comment by Pickysaurus** [comment]
Can you please provide specific dialogue lines for this? It'll be easier to fix if we know the extent of the problem.

**Comment by Pickysaurus** [comment]
I've found the following:

# [000DBCD7]
> Hungry... Could use some groat. I must maintain my strength.

> Bin hungrig ... Habe Lust auf Zriege. Muss bei Kräften bleiben.

# [000B85B1]
> In my culture, every child is entrusted with a pet groat.

> In meiner Kultur wird jedem Kind eine Zriege anvertraut.

# [000B857F]
> They are domesticated creatures native to my planet. Smelly, cantankerous... but their milk is a staple of our diet.

> Auf meinem Heimatplaneten werden Zriegen als Haustier gehalten. Sie stinken und sind störrisch, aber ihre Milch schmeckt köstlich.

# [000B85BC]
> Through this groat, we are shown the connection that we have to the Great Serpent. That all things serve the Serpent, and can be tools for his use, in more ways than one.

> Die Zriege ist das Symbol für unsere Verbindung zur Großen Schlange. Alle Dinge dienen auf vielen Wegen der Schlange und sind ihr Werkzeug.

---

I've not played to this point in the game, but it seems like they're talking about a fictional creature called a "Groat" - this doesn't seem to be a typo.

**Comment by Constellation-VASCO** [comment]
You are right Groat is very missleading here.

> Hungry... Could use some groat. I must maintain my strength.
> Bin hungrig ... Habe Lust auf Ziege. Muss bei Kräften bleiben.

> In my culture, every child is entrusted with a pet groat.
> In meiner Kultur, jedem Kind wird eine Ziege anvertraut.

> They are domesticated creatures native to my planet. Smelly, cantankerous... but their milk is a staple of our diet.
> Auf meinem Heimatplaneten werden diese als Haustier gehalten. Sie stinken, sind störrisch... aber ihre Milch ist eines unsere Grundnahrungsmittel.

> Through this groat, we are shown the connection that we have to the Great Serpent. That all things serve the Serpent, and can be tools for his use, in more ways than one.
> Die Ziege ist das Symbol für unsere Verbindung zur großen Schlange. Alles dient der großen Schlange, und kann Ihr zu nutze sein, auf vielfältige Weisen.

**Comment by Constellation-VASCO** [comment]
markdown fix?

> Hungry... Could use some groat. I must maintain my strength.
> 
> Bin hungrig ... Habe Lust auf Ziege. Muss bei Kräften bleiben.

> In my culture, every child is entrusted with a pet groat.
> 
> In meiner Kultur, jedem Kind wird eine Ziege anvertraut.

> They are domesticated creatures native to my planet. Smelly, cantankerous... but their milk is a staple of our diet.
> 
> Auf meinem Heimatplaneten werden diese als Haustier gehalten. Sie stinken, sind störrisch... aber ihre Milch ist eines unsere Grundnahrungsmittel.

> Through this groat, we are shown the connection that we have to the Great Serpent. That all things serve the Serpent, and can be tools for his use, in more ways than one.
> 
> Die Ziege ist das Symbol für unsere Verbindung zur großen Schlange. Alles dient der großen Schlange, und kann Ihr zu nutze sein, auf vielfältige Weisen.

**Comment by Pickysaurus** [comment]
Appears to be not a bug.
