### ISSUE TITLE
Power from beyond 

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#214]
The power from beyond quest(dioynsus) is not working. The scanner is not distorting to show the location of the anomaly. 

---

## Details 
You land where the anomaly is to find it’s not a temple. The marker says to go there but it’s a different anomaly. 

## Game Version
1.7.29

## New Game
Yes

## Reproduction Steps
There are cases on Reddit were this is happening to a lot of people. Seems to be when you progress a certain distance in the main story. Quest is active and shows a marker but there is no scanner distortion or temple to be found.

**Comment by Constellation-VASCO** [comment]
If you still have the save that has this issue, can you try this fix and see if it works for you? https://www.nexusmods.com/starfield/mods/6206

**Comment by Pickysaurus** [comment]
Pickysaurus, Here's a save that is missing a bunch of quest markers for Power From Beyond. Washakie, Carinae I, Tau Ceti are all missing quest markers so you have to manually find them in the Starmap to set course to them.

[PowerFromBeyondQuestMarkersMissing.zip](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/files/13265856/PowerFromBeyondQuestMarkersMissing.zip)

**Comment by Constellation-VASCO** [comment]
This issue shouldn't be closed, as it's still not resolved.
