### ISSUE TITLE
Typo in "Scan Jammer - Single - Frequency" part

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#22]
There is a typo in the description (shown on the left) of the "Scan Jammer - Single - Frequency" ship part.

---

## Details 
Current text

> A Scan jammer that increases your chance of evasion during a ship scan by 10% if you're using a a shielded cargo module and carrying contraband.

Corrected text (no duplicate "a")

> A Scan jammer that increases your chance of evasion during a ship scan by 10% if you're using a shielded cargo module and carrying contraband.

## Game Version
1.7.23.0

## New Game
Yes

## Reproduction Steps
- Go to a vendor who can customise your ship and also sells the "Scan Jammer - Single - Frequency"
- Select it from the "Equipment" menu. 
- See the typo on the right side. 

![Screenshot](https://i.imgur.com/031wcKZ.jpg)

**Comment by Constellation-VASCO** [comment]
The IDs for this item are `co_SMS_ScanJammer01[001AD84D]`.

This issue is also present in:
- `co_SMS_ScanJammer02_DualFrequency[001AD84C]`
- `co_SMS_ScanJammer03_MultiFrequency[001AD84B]`

**Comment by Pickysaurus** [comment]
https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/commit/a51cf6dbb83968aa19b2ab8b3bb16811260bd46d
