### ISSUE TITLE
Crew not on ship

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#221]
Crew will NEVER appear on the ship under any circumstances except current follower. May be caused by boarding and stealing another ship, but once it happens even switching to another normal ship or the frontier wont fix it.

---

## Game Version
1.7.29.0

## New Game
No

## Reproduction Steps
It doesn't happen every time per evidence of others on reddit.

**Comment by thelostemperor** [comment]
I have this issue currently. And if you use the console to move an NPC into the ship, they will just stand in one spot without doing anything, as if they weren’t assigned crew. You can engage in dialogue but they will not move around at all. You can ask them to be your follower, but then your current follower will leave the ship.

**Comment by Aurelianis** [comment]
See duplicate issue (closed) for more detailed info https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/issues/268

**Comment by Aurelianis** [comment]
This was at one point fixed in SFCP, and has since been fixed by Bethesda.
