### ISSUE TITLE
Into the Unknown, collect the power on...X

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#225]
Quest, Into the Unknown, no "scanner anomaly" location spawns on the planet and repeated attempts to land in the approximate location and find scanner anomalies are not successful.

---

## Details 
Relates to "discovered" scanner anomalies that are found rather than being directed from Vladimir.  If the planet has been previously visited and scanned the notification will appear (and the mission will appear in the log) but the temple location (scanner anomaly location) will not spawn on the planet.  This means that the player cannot obtain all the powers in the playthrough.

## Game Version
1.7.29.0

## New Game
Yes

## Reproduction Steps
Survey a planet that has a temple before getting to the point in the game where you are first narratively taken to a temple.
Obtain your first power and keep playing until you get "Into the Unknown" from Vlad the first time and complete it.
Go back to the planet and you will still get the "Into the Unknown, Obtain the power on X" mission in your log but will not have the "scanner anomaly" location or the temple spawn on the planet.

**Comment by Aurelianis** [comment]
This was fixed by Bethesda
