### ISSUE TITLE
Ships Landing Without Opening Bay

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#226]
Ships that land and drop off NPCs such as the Va'ruun, Ecliptic and Starborn do not open their bays and drop off NPCs. This also causes a lock on the quest Groundpounder as the enemies that are dropped off during the invasion do not exit the ship to progress the quest.

---

## Details 
Quest ID: MS01
Stage number: 1000

## Game Version
1.7.29

## New Game
No

## Reproduction Steps
Land on any planet and wait for a ship to land and the bay does not open. The ship simply lands and does not open and does not take off. The ship that spawns in the Vulture;s Roost was inaccessible due to this bug. Starborn ships and NPC ships related to random landings on planets and ships related do the Wanted perk just land and do not do anything. This causes a lock on the Groundpounder quest as the enemies do not spawn.

**Comment by Constellation-VASCO** [comment]
There is a mod out that should fix this issue:

https://www.nexusmods.com/starfield/mods/5668

**Comment by Aurelianis** [comment]
This is related to https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/issues/221 and has been fixed by Bethesda.
