### ISSUE TITLE
Can't use grav drive - always going to Unity

### ISSUE THREAD

**Issue by obrunopolo** [Starfield-Community-Patch/Starfield-Community-Patch#228]
My save has become unplayable since I built an outpost and left the artifacts there. For some reason, I cant use the map to jump to any other system. Whenever I put energy into the grav drive, I get to Unity. I tried traveling to a planet on the same system, I tried landing on the planet, I tried a lot of things. The last 2 hours of gameplay were frustrating. I do not have the artifacts on my ship or on my inventory.

I guess I will have to return to a previous save and lose all the effort put into that outpost.

**Comment by Larandar** [comment]
Have you tried removing the armeliery (or whatever it's called/spelled)? The artifacts are weightless so keeping them in your inventory is only a minor inconvenience after the the last temple.

**Comment by obrunopolo** [comment]
Yeah, I noticed it later
I could not understand this way. I must have skipped some dialogue because I thought you should have them away from you to avoid going to Unity
I'll close the issue
