### ISSUE TITLE
Console failing to close

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#236]
I manage to start the console but cannot close it but pressing the same or any button or key combination

---

## Details 
I've never successfully managed to use the console. I always have to Alt+F4 out of the game because the console freezes everything except the ability to enter commands. The box that warns that some commands may disable achievements appears every time I open the console, and I cannot press the corresponding key to disappear it. A Reddit-commentor said it may be because the console takes priority but this time it was "fighting" with the PSA box and they end in a stand-still (paraphrasing a bit), as not even entering valid commands manage to end the console. This has been an issue since day 1 on Game Pass for me and ever since I moved to Steam.

## Game Version
Up to date as of 18.9.23

## New Game
Yes

## Reproduction Steps
Simply pulling up the console when in-game.

**Comment by Constellation-VASCO** [comment]
Tested right now (37 minutes after this issue was submitted) and console is working as it should. I've installed certain mods in the meantime, so they MIGHT have fixed the issue, whatever it was, but leaving this up in case. You choose to delete it if you don't see a need.

**Comment by Constellation-VASCO** [comment]
UPDATE - FIXED! Solution in the last paragraph; the rest is context:

Again, you decide on deleting this thing. I don't know if there are others looking for this or not.

Tested console again and it seems to work when not in-game, so in the game main menu, essentially. This makes me think that Reddit person's theory isn't far off - that the PSA about commands turning off achievements may be the cause of this issue, since it doesn't pop up in the main menu when I tried just now. I chose 'New Game' and spammed the console key, and it works fine all the way through the Bethesda self-congrats and even through the opening cutscene. Seems it only causes issues during actual gameplay.

WHEN LIN STARTS TALKING for the first time in this cutscene the PSA box pops up and I CAN click it away, allowing me to pull up and take down the console intended. Turns out all I had to do was start a new save and press the console key DURING THE FADING INTO THE CUTSCENE. I have no clue why this work as opposed to any time during actual regular gameplay, but it seems to have worked.

**Comment by Constellation-VASCO** [comment]
UPDATE 2:

It seems the above fix is ONLY TEMPORARY, as it resets when you turn off the game and reemerges your next play session. The cutscene thing makes me think you can try to spam the console button in another cutscene, like taking off/landing, see if that works.

**Comment by Constellation-VASCO** [comment]
UPDATE3:
I ended up installing this mod: https://www.nexusmods.com/starfield/mods/252?tab=posts . READ UNDER "MOD INSTALLED CORRECTLY BUT STILL DOES NOT WORK OR CAUSED GAME TO CRASH" IN THE FIRST COMMENT ON THIS PAGE. The instructions written in italics will tell you the fix I applied when the mod itself didn't work after I installed it correctly, and the changes worked for me, so hopefully for you, too.

**Comment by Constellation-VASCO** [comment]
This PSA box is still something I think needs fixing so we don't need all this roundabout stuff. Sorry for spamming messages but that's what happens with no 'edit' function.

**Comment by Deebz96** [comment]
I know what you are referring to, however fixing this would likely require an engine-level adjustment, which would be out of the scope of this mod.
