### ISSUE TITLE
Mini map or radar

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#237]
Lack of shop icons and crafting tables

---

## Details 
I noticed that I can hardly find where to sell, buy, improve or make something. I wanted to make my suggestion on creating a radar or a mini-map for better orientation on the terrain, especially in cities. So that the icons of merchants, other shops and crafting tables are indicated

## Game Version
1.7.29

## New Game
Yes

## Reproduction Steps
Creating the appropriate mod

**Comment by Aurelianis** [comment]
This is out of scope for SFCP. SFCP is meant to fix bugs not add features. However, ground maps were improved significantly in v1.11.36.0 by Bethesda
