### ISSUE TITLE
Companion head invisible after Stealth 

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#24]
My companion Andreja wound up with a completely invisible head after carrying out a mission involving sneaking around (the first quest to join the Ebbside Strikers, where you steal the slate).  I haven't been able to recreate it yet, but I didn't find a matching issue so I figured I'd start one to see if we can pin this down.

---

## Details 
andrejaRef 59A9

## Game Version
1.7.23.0

## New Game
No

## Reproduction Steps
N/A yet.

**Comment by Constellation-VASCO** [comment]
I had this issue as well! I'm not sure how I triggered it, but can confirm the bug!

**Comment by purplepity** [comment]
Can also confirm, seems to happen occasionally when exiting stealth

**Comment by Constellation-VASCO** [comment]
Was she wearing something with the chameleon attribute? I do not travel with companions often, but most times, when I wear something with the chameleon attribute on it and go stealth, my body and head end up permanently invisible, even after I take the item off.

**Comment by purplepity** [comment]
I think it's part of her kit. Cause I don't have any gear that gives her chameleon but she still goes invisible when sitting still in sneak

**Comment by Constellation-VASCO** [comment]
Fixed in game update 1.8.83
