### ISSUE TITLE
Cydonia crashes game

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#240]
Cydonia caused no issues at the beginning of the game, but after getting to the end of "Delivering Devils" where you need to return there with NPC Percival Walker, the game will crash as soon as I get close or fast travel to Cydonia. Loading a save before this point still works. I've tweaked settings, verified files, and even tried some more esoteric fixes other have tried in the community - https://www.reddit.com/r/Starfield/comments/16ejjl1/game_crashes_when_i_try_to_enter_cydonia_cant/

---

## Details 
Quest ID: 0029D04C Quest stage: 947

## Game Version
1.7.29.0

## New Game
No

## Reproduction Steps
Unsure. When I Google this issue there seems to be a few community members who are experiencing the same thing, but it manifests a little different for everyone.

**Comment by Deebz96** [comment]
Unable to replicate, not enough information to investigate.
