### ISSUE TITLE
Useless Head Rotation

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#247]
Every time you walk for a long time and are in 3rd person perspective, the character turns his head 90 degrees to the left.
Whether you run around with active scanner mode or not doesn't matter.
What kind of person runs straight ahead while constantly looking to the side?

---

## Game Version
C45EB345  V1 7.29.0

## New Game
No

## Reproduction Steps
Walk straight ahead and you will see....
You must be in the 3rd person perspective.

**Comment by Pickysaurus** [comment]
That fix is definitely worth looking at.

**Comment by Constellation-VASCO** [comment]
Afaik Bethesda fixed this already. At least the bug hasn't been happening for me as of late.

**Comment by Constellation-VASCO** [comment]
Wait try and verify this still happens later. There is a fix ready to go if it does.

**Comment by Pickysaurus** [comment]
Fixed in https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/commit/365e45ee01733a39d43c1d002a23ea088fd05d45
