### ISSUE TITLE
Last Will and Testament Bugged Start

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#248]
Cannot complete first stage, "Speak to Elias Cartwright". 

---

## Details 
When spoken to, Elias does not have any dialogue options pertaining to the quest. In order to progress, you can read the body text under the title on the mission screen and go to Sahar's farm.

## Game Version
1.7.29.0

## New Game
No

## Reproduction Steps
First, hear from a guard that Elias has a job for you. Then, go and speak to him. When I initiated the quest, the guard said that as I ran past and then I didn't get around to talking to Elias some 15 hours (real-life/save time) later.

**Comment by Aurelianis** [comment]
The quest will progress if you ask Elias about the Core. Then you will get the option "Tell me more about Frank Langston and your problem." It's really not intuitive that you need to ask about the Core first though.

**Comment by Aurelianis** [comment]
This is actually not a bug. As commented previously, you need to ask him about the Core first, then "Tell me more about Frank Langston and your problem."
