### ISSUE TITLE
NPCs starting conversations in dialogue with PC

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#25]
There seems to be an issue where NPCs who are already engaged in dialogue with the player will frequently start other scripted or random conversations with nearby NPCs despite being already engaged in dialogue. This will then cause only the voice lines of the NPC the player is not currently speaking with to play, so you're only hearing one side of the conversation. I've also had this cause two separate conversations begin playing at once, when the original NPC starts a new conversation with the second or another NPC after you exit dialogue with them.

The worst I've seen it yet is when visiting the PC's parents after taking the Kids Stuff trait. I've had both parents do this if you try talking to them early on in the visit, before they might naturally trigger some of their potential conversations. One conversation will begin while you're talking to your mom or dad, and then a second conversation triggers after you get out of the dialogue, but you only hear half of each conversation.

---

## Game Version
1.7.23

## New Game
Yes

## Reproduction Steps
It seems all really need to do is spend time around NPCs that you can open a dialogue window with, who also have scripted dialogue with each other or the potential to have random dialogue interactions. Aside from the character's parents, I've had this trigger in the Lodge between multiple members of Constellation. 

In one such instance, Sophia began praising Noel while I was talking to Noel, but I only heard Sophia's side of the conversation, though I believe Noel is supposed to be bashful if I remember the conversation correctly when I heard it trigger normally on my first character. Likewise, after I asked Noel to give me the tour of the Lodge, I did not get one because as soon as I exited the dialogue window with her, she walked over and asked Walter about the state of his marriage. This time I did at least hear the entire conversation from both sides, but the tour did not happen and could not be restarted. I still had ownership of the bed in my assigned quarters however and did not find any other problems with the tower being skipped.

**Comment by Deebz96** [comment]
I don’t believe this is an issue with the game anymore. Bethesda has specifically addressed the issue with parent dialogue in a past update as well. Closing as dated.
