### ISSUE TITLE
Companion affinity event on appearance change does not fire

### ISSUE THREAD

**Issue by Bobbyclue** [Starfield-Community-Patch/Starfield-Community-Patch#255]
Problem is in CompanionAffinityEventsScript.

**Details**
Starfield has a companion affinity event for when the player changes their appearance (COM_Event_Action_Enhance_PlayerChangeAppearance), however the script that calls for this never fires as it attempts to use RegisterForMenuOpenCloseEvent to register for a nonexistent menu, "LooksMenu". LooksMenu was the Fallout 4 name for what is now called "ChargenMenu", and swapping the name over seems to have resolved the issue.

**Reproduction Steps**
To reproduce simply change the players appearance through ChargenMenu and notice the lack of companion response. Or, as I did, enable papyrus logging and notice the game throw an error when starting a new game about failing to register for "LooksMenu".

**Game Version**
1.7.29.0

**Comment by Bobbyclue** [comment]
More to it than just that it looks like. All instances of changing appearance happen inside of dialogue, and companion lines are set to only play if the player isn't in dialogue. It is simple enough to add an exception of some kind, but I could also see that being considered more in the realm of "cut content" at that point. 

Personally I do think this is a bug, likely an older bit of content that just wasn't kept up to date with everything else around it.

**Comment by Noggog** [comment]
@Starfield-Community-Patch/qa Anyone available to try reproducing this one?  There is a PR out and it would be nice to get it reproduced

**Comment by Bobbyclue** [comment]
For the sake of testing, the only companions who will make comments on appearance change are listed here
![Screenshot 2023-09-23 125919](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/assets/97621924/e7f99200-e8b8-4a31-8c15-028b1ad6c3bd)

**Comment by Pickysaurus** [comment]
Fixed in https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/pull/259
