### ISSUE TITLE
Typo in description of Peak Performance 05

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#26]
The description text of the magazine "Peak Performance 05" reads "Permanenelty adds 5% to unarmed damage."  Should be spelled "permanently."

---

## Details 
00202D9A

## Game Version
1.7.23.0

## New Game
Yes

## Reproduction Steps
Look down, open console, execute "player.placeatme 202d9a" and read the description of the magazine.

**Comment by Geeknasty** [comment]
I cannot reproduce this. It appears to be spelled correctly for me. `Permanently`

![Image](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/assets/103335300/728e3705-c0ee-4f51-ba31-c0a7b40d6807)

Can anyone else verify this?

**Comment by Constellation-VASCO** [comment]
That's really bizarre.  I actually shared a screenshot of it in the Discord, and I just looked it up to confirm that l wasn't just losing my mind.  But now it's fixed even in my own game.  How the hell?

**Comment by Pickysaurus** [comment]
I've verified this in the strings file so there is a mistake.

**Comment by Pickysaurus** [comment]
https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/commit/a51cf6dbb83968aa19b2ab8b3bb16811260bd46d
