### ISSUE TITLE
"pique his interest" spelled with "peak"

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#260]
Masako's dialog subtitle for "pique his interest" is spelled as "peak his interest" during the "Sabotage" quest introduction.

---

## Details 
"Sabotage" quest introduction. Didn't check xedit for quest id.
Screenshot: https://i.imgur.com/v4nJA9P.png

## Game Version
1.7.29.0

## New Game
Yes

## Reproduction Steps
Just find this dialog response in xedit and fix the spelling.

**Comment by Constellation-VASCO** [comment]
Form ID [0015E064]

**Comment by Pickysaurus** [comment]
https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/commit/a51cf6dbb83968aa19b2ab8b3bb16811260bd46d
