### ISSUE TITLE
Exiting Cydonia City Causes Crash on Steam Deck.

### ISSUE THREAD

**Issue by Celestial-Vixen** [Starfield-Community-Patch/Starfield-Community-Patch#266]
Something about how the main exit to the Cydonia City door is set up causes an insta-crash on steam-deck. I'm not sure if it occurs on other systems. The crash happens before the loading screen, all other methods to travel to the Cydonia City landing pad work fine. 35+ hours in with no other CTDs on the steam deck.

**Comment by Constellation-VASCO** [comment]
This seems to be an issue on alot of hardware and not just Steam Deck. I've experienced it on my Desktop as well. My friend has experienced it as well on his desktop and laptop. It seems to be Mars in general too, exiting the lab in the same worldspace causes it.

**Comment by Deebz96** [comment]
Not enough details to investigate.
