### ISSUE TITLE
NPCs behind inaccessible doors

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#278]
In multiple Sidequests (The Showdown, Operation Starseed) NPCs (Vogel, FDR) are behind inaccessible doors.

---

## Game Version
1.7.33.0

## New Game
No

## Reproduction Steps
--

**Comment by Constellation-VASCO** [comment]
I can confirm I encountered this during Operation Starseed.

**Comment by Pickysaurus** [comment]
This report lacks detail but is probably fixed in game update 1.8.83
