### ISSUE TITLE
Sivan lacks follow stop conditions in FFCydoniaZ05

### ISSUE THREAD

**Issue by Bobbyclue** [Starfield-Community-Patch/Starfield-Community-Patch#279]
In the quest FFCydoniaZ05, "My North Star," Sivan is a temporary follower. Like many quest related followers the script DefaultFollowerToggleQuestScript is used on the quest to control when she starts and stops following. While the FollowConditions property on this script is set properly, StopFollowConditions is not. Rather than the condition form it is supposed to contain it is instead filled with a light (LGT_ShipInterior_Omni_NS_Cool_001_5k) which is an invalid form for that property.

That at least is an error for certain. What the original intent was however is still a question. Many quests use the same condition form for both FollowConditions and StopFollowConditions, and that would work here as well. The resulting difference would be that Sivan would only follow you on Mars and on your ship. There is a chance Bethesda intentionally did not want to limit her follow distance, but that seems very out of place compared to other followers and given the context of the quest. 

So, my suggested fix is to fill the StopFollowConditions property of DefaultFollowerToggleQuestScript on FFCydoniaZ05 with FFCydoniaZ05_FollowerConditionForm_Follow, the same as what's in FollowConditions. This will need to wait for some kind of esp editing.

**Game Version**
1.7.33

**Reproduction Steps**
Start the quest My North Star in Cydonia by talking to Sivan. Once she starts to follow the player leave Mars and land on another planet. She still follows but shouldn't.

**Comment by Constellation-VASCO** [comment]
Can confirm this issue appears in the papyrus log. Will fix in the next build.
