### ISSUE TITLE
Andromeda Kepler subtitles spelling error -English

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#284]
Andromeda's subtitles shows "...planets' movement smight affect...". Should be "...planets' movements might affect..."

---

## Details 
Found this record in SF1View:
INFO:00146104 \ Responses \ Response #1 \ NAM1 - Response Text
"Most of the ancient astronomers I've studied were astrologers too. They read astrological charts to predict how the planets' movement smight affect their lives."

## Game Version
1.7.33

## New Game
No

## Reproduction Steps
Speak to Andromeda Kepler after hiring her.
Dialogue options chosen:
- "Do you mind if I ask you some personal questions?"
- "Have you studied anything new recently?"
- Andromeda will begin saying "I've been dabbling in astrology..."
The next set of subtitles will have the error.

**Comment by Pickysaurus** [comment]
https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/commit/a51cf6dbb83968aa19b2ab8b3bb16811260bd46d
