### ISSUE TITLE
Can't save in ng+

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#289]
Every time i try ng+ in a different universe Can't save .

---

## Details 
Every time i try ng+ in a different universe Can't save .

## Game Version
1.7.33.0

## New Game
Yes

## Reproduction Steps
Play the same way

**Comment by Evolution0** [comment]
Starting with a NG+ save on NG+9 at the Unity (so +10 entering) acquired on Nexus this happened to me as well.
I could not:

 - Save
 - Load
 - Access Inventory
 
 What fixes this is running `SetInChargen 0 0 0` so my assumption is the game still thinks the player is in character creation like with a fresh playthrough. I did not test if I could wait but I'm guessing if you do `SetInChargen 1 1 0` you will be able to reproduce the same effect. (as you don't get a toast message that controls are disabled)

**Comment by Aurelianis** [comment]
This was fixed in v1.8.86
"Fixed an issue that could temporarily prevent opening the inventory or saving after entering the Unity."
