### ISSUE TITLE
Door Issue

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#29]
when you are moving into a building and it has a sealing door, if an enemy goes through it and opens the inside or outside part of the sealing door they are able to shoot through it before fully opening the door

---

## Details 
its a minor detail I believe none are necessary 

## Game Version
1.7.23.0

## New Game
Yes

## Reproduction Steps
find an outpost or structure with a door that goes from the outside to inside (no atmosphere) so once the door is in the process of opening and an enemy is in the sealing part they can shoot through it even while its just opening

**Comment by Pickysaurus** [comment]
A better version of this report is here: https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/issues/316
