### ISSUE TITLE
Manufactured components lack rarity tags

### ISSUE THREAD

**Issue by craig-king** [Starfield-Community-Patch/Starfield-Community-Patch#290]
## Description
Manfactured components lack data indicating their rarity resulting in items cards missing the rarity symbol, and them being shown as common when using inventory mods such as StarUI.

## Game Version
1.7.33.0

### Incorrect StarUI Values
![image](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/assets/5041926/913e1388-9761-452f-ab09-33fb3fd4ce4b)

### Inorganic / Manufactured Comparison
| Inorganic Resource  | Manufactured Resource |
| ------------- | ------------- |
| ![image](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/assets/5041926/9adb1fbb-072a-4efe-911b-10edbd3d9a07) | ![image](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/assets/5041926/b5f2fb61-14f3-415c-a81c-866ed2357809) |

**Comment by Constellation-VASCO** [comment]
This has been driving me slightly batty.

**Comment by thomoray** [comment]
Hi all, I also had this driving me crazy, plus there were a couple of items that say Unique but where flagged as Common like Memory Substrate. Attached is a update esm file with the fixes. Full list of changes made attached. 

Hope this can be included in a future patch as standard :)

[Resource Fix List.xlsx](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/files/13314687/Resource.Fix.List.xlsx)
[Resource Fixes.zip](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/files/13314692/Resource.Fixes.zip)

**Comment by Deebz96** [comment]
Quite late on seeing this one, but this does appear to still be an issue with the game. Thank you for providing that extensive fix thomoray. It will be included in version 0.1.8.
