### ISSUE TITLE
A High Price To Pay - Game Breaking Bug x2

### ISSUE THREAD

**Issue by Conroy1988** [Starfield-Community-Patch/Starfield-Community-Patch#293]
**1 -** Upon placing the artifact on the table, The quest begins. Requiring you to talk to Noel to start the dialogue for the Eye being attacked. However she cannot be talked with, pressing both keyboard and controller keys just makes the dialogue key flicker, tested speaking to all other members, reloading, coming in and out etc.

Using console to disable char and re-enable does not fix this.

To get passed this a quest stage command can be used, but that then brings us to issue number 2 below.
Video of this issue - https://medal.tv/games/starfield/clips/1wIL5cxxQLjTWC/d13377gC4VXG?invite=cr-MSxXS2ssMjUwMzE1LA

**2 -** Upon using a stage quest console command to force the next stage of this quest, you find yourself going to The Eye, once heading back to the Lodge, you must speak to the other constellation members for updates. Every one can be spoken to apart from Walter Shroud. Similar to a previous bug where you cannot finish a dialogue with him. 

Quest stage command has not been used here as already used before. Disabling Walter and re-enabling does not solve the issue. Shooting Walter to force him to get up and faint, then reset also does not solve.
Video of this issue - https://medal.tv/games/starfield/clips/1wIKS4B04kGbZC/d1337307hEG7?invite=cr-MSxvR2ksMjUwMzE1LA

**Comment by Conroy1988** [comment]
Meant to mention - 1st playthrough, latest steam game version 1.7.33 Sept 25th

**Comment by Conroy1988** [comment]
Has this been acknowleged?

**Comment by Deebz96** [comment]
Not enough details to replicate issue. Going to close as dated.
