### ISSUE TITLE
Completed Activities still on list

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#296]
The Activities list is full of completed objectives that still show as active. There is no way to reset or clear them

---

## Details 
none

## Game Version
1.7.33

## New Game
No

## Reproduction Steps
Just play the game

**Comment by Constellation-VASCO** [comment]
Remains an issue in 1.7.36. I've had a few completed mission get stuck, they resolved themselves, but "Distilling Confidence"  seems permanent at this point.

**Comment by Deebz96** [comment]
Without specifics, this one cannot be investigated.
