### ISSUE TITLE
Paradiso Gen Store Glitched After Complaint

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#301]
After complaining about Jacquotte Laguerre to Emilian Vasilescu about her tone, her sale inventory does not appear. The UI flickers and shows her dialogue options again.

---

## Details 
Unknown.

## Game Version
1.7.33.0

## New Game
Yes

## Reproduction Steps
Select all dialogue for Jacquotte Laguerre on Paradiso and look at sale inventory. Every option worked for me on a new game. Then, complain to Emilian Vasilescu about Jacquotte's tone. Go back to Jacquotte and select "Let's see what you have for sale." When selecting that dialogue, the UI flickers but does not open up the inventory. The NPC also doesn't say anything like "take a look" or whatever this NPC vendor says. I was able to repeat this issue several times where the only thing I do inbetween looking at the vendor's items is complain.

**Comment by Constellation-VASCO** [comment]
I've just fixed this: [https://www.nexusmods.com/starfield/mods/11056][https://www.nexusmods.com/starfield/mods/11056]

The condition set on 0004844A was supposed to be equal to 1, as this is the more "friendly" set of responses, but the game has this as equal to 0, the same as the other set of responses. That meant there were no possible responses after speaking with Emilian Vasilescu about Jacquotte Laguerre and her vendor dialogue was broken.

Trying to make this change in the CK resulted in a crash for some reason, but xEdit worked.

**Comment by Deebz96** [comment]
#185
