### ISSUE TITLE
Abandoned Industrial Compound - two coolers

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#304]
On the north side of the location, under the stairs of the tower by the rock there is a cooler on its side on a bunch of garbage, two coolers occupy the same space, so far in every instance of this location.

---

## Details 
Location object related, no associated quests. Item is shown as FF06C781 in console.

## Game Version
1.7.33.0

## New Game
Yes

## Reproduction Steps
None necessary.

**Comment by Deebz96** [comment]
Addressing as part of issue #848
