### ISSUE TITLE
Altair II floating objects

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#31]
Got a few floating objects at the northern Research Camp on Altair II. 

---

## Details 
![image](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/assets/36433/505fc335-6010-4a92-9165-17b6c032b3a2)

## Game Version
1.7.23.0

## New Game
Yes

## Reproduction Steps
Go to the research camp on Altair II

**Comment by Geeknasty** [comment]
I'm trying to reproduce this issue, but my research camp looks completely different, and the map marker dropped in a different spot.

I believe this quest stage is being generated like a radiant quest.

This is how my Reseach Camp looks like.

![20230904092143_1](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/assets/103335300/210c8491-ac9c-4f78-aa76-b97ecb0048d6)

All the static objects are also prefaced with the index `FF` which means they are generated in-game and only found in the save file, right?

![20230904092207_1](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/assets/103335300/395bae4a-4dd9-4e18-bf26-0d8bb892ba20)


So will this mean we need to have a save file included with these types of issues?

**Comment by khirasier** [comment]
there are many locations with floating assets most likely these places were built using procedural generation

**Comment by Deebz96** [comment]
This is more of a general issue with the procedural generation system. Sometimes objects don't appear. This is beyond the SFCP's ability to fix.
