### ISSUE TITLE
Companion wearing starborn suit speech in cities

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#310]
When giving companions a full suit that covers everything, the starborn suit is the only one I can think of. In cities where the suit is automatically hidden, the companion still sounds like they have the helmet on.

---

## Details 
Starborn suits, or any that cover the face and make the companions speech modified to sound like it's coming through a helmet.

## Game Version
1.7.33.0

## New Game
Yes

## Reproduction Steps
Issue a companion with a suit that covers the head. For example, the starborn suit.
Go to a city, such as New Atlantis(Anywhere their spacesuit would be hidden automatically)
Start talking to them.

**Comment by Deebz96** [comment]
This is likely the same glitch that can cause any helmet modulation to occasionally stick on a character. Unfortunately, it's an engine level issue, and thus out of the scope of the SFCP to fix.
