### ISSUE TITLE
Ryujin Sabotage questline

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#313]
Report information to David at SSNN not available - Sabotage Ryujin questline 

---

## Details 
Final portion of the questline broken, waypoint leading to David at SSNN tracks off the map outside of New Atlantis. When you try to go in to SSNN with the questline tracked or untracked, the NPC David is not there. Unable to complete questline. Tried resetting and quitting the game. Even went back to an earlier save to see if it would resolve, but still results in the same outcome. 

## Game Version
1.7.33

## New Game
No

## Reproduction Steps
Reload earlier save game prior to this quest point, still resulted in the same outcome, waypoint does not track properly and the NPC is not around to complete the final quest point

**Comment by Constellation-VASCO** [comment]
Can’t progress through to the last part of the quest for the final rewards

**Comment by Constellation-VASCO** [comment]
Any update on questline glitches?

**Comment by Constellation-VASCO** [comment]
You may need to share your save where this is happening as it didn't happen for me.

**Comment by Constellation-VASCO** [comment]
This is a unique issue I have had happen a few times now with other various quests targeting NPC's randomly showing up at various locations on the map.
All you can do is travel to the marker in a straight line till you find em usually trapped on some terrain or object at that location.

I feel the issue is due to a Spawn bug with the npc's spawning or placing npc's in the incorrect spawn locations.

**Comment by Deebz96** [comment]
Never experienced this; supposedly fixed officially in 1.10.31.
