### ISSUE TITLE
Neon Security dialog wrong for bounty at entance.

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#319]
Neon Security's comment about your bounty at the entrance checkpoint is incorrect.

---

## Details 
Dialog in the DialogueNeonConvo_SecurityCheckpoint (0x32C7C0) quest is conditioned on a CrimeBountyAmount global variable (0x9108). This global variable is only used for the guard arrest quests - DialogueCrimeGuards (0x269BC0) and DialogueCrimeGuards (0x5BD6F). It is set at the beginning of the quest for displaying the payable bounty amount in dialog. It is never cleared when the quest ends because it is probably not intended to be used anywhere else.

This leads to the following issues:
- If you have a bounty but no guard has attempted to arrest you for it, Neon guards will not comment about it.
- If you don't have a bounty, but had one in the past, Neon guards will always comment about it.

## Game Version
1.7.33.0

## New Game
Yes

## Reproduction Steps
To reproduce Neon guards not commenting about active bounty:
1. get a bounty for UC
2. avoid UC guards
3. enter Neon through starport entrance.

To reproduce Neon guards commenting about paid off bounty:
1. get a bounty for UC
2. get arrested and pay for your bounty
3. enter Neon through starport entrance.

**Comment by Pickysaurus** [comment]
Fixed in https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/commit/847bc21d4cffcee24638ae179aff597800fb1a74

(Thanks to wSkeever for the fix!)
