### ISSUE TITLE
4 books titled "Book" placed in The Clinic

### ISSUE THREAD

**Issue by Orvid** [Starfield-Community-Patch/Starfield-Community-Patch#322]
There are 4 instances of the book titled `Book` (EditorID: `_BookHardback_Large01_DONOTUSE`, FormID: `0x001829E7`) placed in The Clinic (Cell `0x001DEBE6`). The 4 references have the following FormIDs: `0x00126335`, `0x001275BA`, `0x0012E038`, `0x1316DC`. These should be either removed or replaced with the normal sets of books, both of which will need xEdit working to do.

**Comment by Pickysaurus** [comment]
Replaced them all with `LL_Loot_Book_Common_Large [LVLI:001D211F]`
