### ISSUE TITLE
Blast Zone mission missing required rocks

### ISSUE THREAD

**Issue by Ripper1302** [Starfield-Community-Patch/Starfield-Community-Patch#325]
The rocks that need to be mined to complete this mission in Akila City are missing.  Multiple quest markers appear but there are not any rocks at those locations that can mined with a cutter.

I have returned to the location several times over several weeks of game time and still not rocks.

**Comment by Constellation-VASCO** [comment]
Same for me.  Tried to do this last night and no rocks.  Oddly enough if you walk over where the rocks are supposed to be, you get hung up on the invisible rocks but cannot break them.

**Comment by Ripper1302** [comment]
I got it from hearing a conversation from one of the guards in Akila City.  The guard told me to look for a man named Tate who was a relator with a problem.  I found him outside  the Core Manor in Akila City which he is trying to sell.

**Comment by Pickysaurus** [comment]
I'm guessing you closed this by accident?

**Comment by Constellation-VASCO** [comment]
The latest community patch fixed this for me.  All missing rocks are now visible and can be removed with a cutter to complete this mission.  

Thanks.

**Comment by Pickysaurus** [comment]
Fixed by Game Update 1.8.83

**Comment by Constellation-VASCO** [comment]
I think in my case, well before the quest, I saw rocks so I blasted them because they were there :) 

I resolved this with this console command which acknowledges the previously destroyed rocks. Maybe a "Oh, I already did that because I'm compulsive that way" dialog could be added haha.
setstage 0003DC10 300
