### ISSUE TITLE
Constellation Mission Board empty.

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#328]
Suddenly the Constellation Mission Boards stops giving more missions. Sadly I have no idea how to reproduce this. My theory is that certain quests given by the mission board are bugged. I have the save which has the last quests given to my by the mission board. I did some testing and it seems like rejecting them gives me more missions but then if you keep doing more missions the bug happens again. It seems like completing certain bugged missions causes this. 

---

## Details 
I have noted down some of the IDs of the missions I think are bugged (again, I don't know if these missions are actually bugged): 001953F8, 001953F9, 00195403

## Game Version
1.7.33

## New Game
No

## Reproduction Steps
Sadly I dont know how you can recreate the bug.

**Comment by Deebz96** [comment]
This is intentional game design. These boards have restrictions on distance and survey completion. Eventually you will run out of missions from the Lodge. This is out of the scope of the SFCP to fix, but I have a mod to do so: https://www.nexusmods.com/starfield/mods/8365
