### ISSUE TITLE
Rejuvenation perk not working

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#331]
In combat portion of Rejuvenation does not work. No health regeneration while in combat.

---

## Details 
According to one user on Nexus mods, this has to do with the actor value HealRate being set to 0 in combat regardless of perks.

## Game Version
1.7.36

## New Game
Yes

## Reproduction Steps
Take rank3 or 4 of rejuvenation and take damage in combat. Will never regen health.

**Comment by Pickysaurus** [comment]
Duplicate of #141 <https://www.starfieldpatch.dev/issues/141>
