### ISSUE TITLE
Andreja repetitive dialogue.

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#336]
When Andreja has been romanced, you can flirt with her and sleep with her. During either of these, Andreja's dialogue will not be random but will instead run through a non-randomised list. So if you play the game and flirt with her once, her response will be "Thank you, dearest. You are not so bad yourself." She has other lines of dialogue that she will use if you save and reload before talking to her, or if you flirt with her more than once without closing the game, but every time the game is closed her responses always start over. What ends up happening because of this is that you hear the same one or two lines of dialogue from her over and over again despite the fact that she has five or six responses to flirting or and five or six for sleeping together. I'm not sure if it is only Andreja or if this happens with other romance companions as well.

---

## Game Version
1.7.36

## New Game
No

## Reproduction Steps
Romance Andreja, marry her, and then flirt with her when you have the option. After you flirt once the option goes away for a little while but comes back after some time. Close the game and flirt again. And again if you wish. Her response will be the same every time. The only way to hear more responses is to save before flirting with her and then reload that save without closing the game.

**Comment by Deebz96** [comment]
This was fixed officially.
