### ISSUE TITLE
Annhilator rounds affect allied companions

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#337]
Damage over time from annihilator rounds on particle weapons affects companions and eventually kills them.

---

## Game Version
1.7.36

## New Game
Yes

## Reproduction Steps
Take a Varuun Inflictor, modify with annihilator rounds and kill enemies with a companion.

**Comment by Deebz96** [comment]
This will be changed officially in the next game update.
