### ISSUE TITLE
Spelling mistake in Helena Strickland subtitles

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#339]
When choosing the dialogue option to refuse to work for Helena Strickland (in Reliant Medical, Gagarin Landing) a *second* time after finding the courier, 'decided' has been incorrectly written as 'decide' in the subtitles.

---

## Game Version
V1.7.36.0

## New Game
Yes

## Reproduction Steps
Complete Helena Strickland's first quest (find the courier). Return to her, and choose the dialogue option that you'd rather never work with her again. Speak to her again, and choose that same dialogue option again. She will say something ending with 'Come back when you've decided to actually be useful', but the subtitles are incorrectly written as 'Come back when you've decide to actually be useful'.

**Comment by Pickysaurus** [comment]
### Current
> So you've said. And yet here you are again. Come back when you've decide to actually be useful.
### Corrected
> So you've said. And yet here you are again. Come back when you've decided to actually be useful.

Form ID 0018E0C1

**Comment by Pickysaurus** [comment]
https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/commit/a51cf6dbb83968aa19b2ab8b3bb16811260bd46d
