### ISSUE TITLE
Starport Elevator

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#343]
Both the upper and lower starport elevators in new atlantis have stopped working.

---

## Details 
Both the upper and lower starport elevators in new atlantis have stopped working. This includes the main level and waterfall elevators. I have seen online that the same on in the well is not functioning however in my save it still works.

The doors still open for me in contrast to some who are having trouble with the doors working. In my case the touchpad the player interacts with to pick a floor is not selectable on both the starport and waterfall levels.

## Game Version
1.7.36

## New Game
No

## Reproduction Steps
I am unsure of how i would even recreate this bug as it has not been working for a long time without my noticing. Reloading older saves on the broken character have the same issue, so I cannot tell at which point it stopped working.

Creating a new character fixes the issue, so I can at least assume it is a problem which may occur after some time of playing.

**Comment by Constellation-VASCO** [comment]
Can confirm this, doesn't work after doing the vanguard questline

**Comment by Constellation-VASCO** [comment]
Confirmed. Once the spaceport gets back to normal after the terrormorph attack in the vanguard quest line, the spaceport/well/waterfall elevator stops working from each location. One has to use the elevator in the MAST NAT station to get to the well and they have to boost jump up to the waterfall platform when that area is needed for Sarah’s companion quest.

**Comment by Constellation-VASCO** [comment]
Similar to https://www.starfieldpatch.dev/issues/839

**Comment by Deebz96** [comment]
Will use #839 as it has more specific details.
