### ISSUE TITLE
German strings issues

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#345]
Spelling errors and inconsistencies between dialogs and text in German strings.

---

## Details 
Inconsistencies:
- Some of the spoken dialog by Gideon Anker (00015064) doesn't match the text in the strings 
- Some of the spoken dialog by Yannick Legrande (0026FDE2) doesn't match text in the strings
(Unfortunately nothing more specific for these two, haven't found a tool like the Voice Reference Tool for Skyrim SE to get the specific lines...)

Typos:
- Missing space: "Ich habe mit Leuten vonReliant Medical und..." should be "Ich habe mit Leuten von Reliant Medical und..."(DIAL: [0022DAC4]; INFO: [0022D907]). 
- Spelling mistake: "Unternehmensnahmen" should be "Unternehmensnamen" (DIAL: [002C334A]; INFO - [002C33C5]).
- Spelling mistake: "Nach der aktion, haben..." should be "Nach der Aktion, haben..." (DIAL: [000131B2] |; INFO - [000131BB]).
- Wrong punctuation: "...dich echt mal zurück," should be "dich echt mal zurück." (DIAL: [00019284]; INFO - [00019287]).

## Game Version
1.7.36

## Language
German (DE)

## New Game
No

## Reproduction Steps
Read subtitles in the corresponding dialog or just take a look at the starfield_de strings. :D

**Comment by Constellation-VASCO** [comment]
Thanks for the report SkyHorizon3. 

I'm afraid I don't speak German, so for the inconsistencies can you please provide the text that should match the dialogue? You can use xTranslator to look them up specifically and it can play the voice lines if required,

**Comment by Constellation-VASCO** [comment]
It's turned out to be quite difficult to apply fixes across more than one language. We'll be discussing the process and if it's something we want to support.

**Comment by Constellation-VASCO** [comment]
No problem :)
I'll write directly what the whole line should look like...
I almost thought the strings were complicated. I send it anyway after listening to the 500 voice lines :D

Gideon:
 - DIAL: [00051A6F] | Record: INFO - [00051A7B]: "Schlimmer noch, ich habe eine Familie zu Hause, die von mir abhängig ist. Finde ich keine Arbeit, haben sie nichts zu essen."
- DIAL: [00051A6F] | Record: INFO - [00051A7B]: "Ich bin völlig pleite, und wir wissen beide, dass sie mir im Nacken sitzen werden, bis sie die Schulden eingetrieben haben. Deshalb bin ich hier und bettle um Credits."
- DIAL: [0027BC78] | Record: INFO - [0027BC70]: "Deshalb unternahm ich Schmugglertouren für die Handelsaufsicht. Ich hoffte auf große Auszahlungen, aber alles ist mir um die Ohren gefolgen."
- DIAL: [0027BC76] | Record: INFO - [0027BC6F]: "Mech-Teile, Biotechnologie, Drogen ... nichts ist tabu. Sogar die Crimson Fleet macht Geschäfte mit ihnen."
- DIAL: [00219573] | Record: INFO - [00219542]: "Puh. Schon besser ... Danke, Chef."

Legrande:
- DIAL: [0012C632] | Record: INFO - [0012C618]: "Laut Neshar wird beim Einstellungstest nach dieser Droge gefragt."
- DIAL: [0021B170] | Record: INFO - [0021B154]: "Für Blend braucht man Aurora. Eine böse ... böse Droge. Außerhalb der Astral Lounge komplett illegal. Und außerplanetar noch illegaler."

**Comment by Pickysaurus** [comment]
https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/commit/a51cf6dbb83968aa19b2ab8b3bb16811260bd46d
