### ISSUE TITLE
Missile Weapon Systems skill issues

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#348]
- The skill rank descriptions don't clearly describe which damage type is getting modified.
- The skill should be modifying hull _and_ shield damage to be in line with the crew perk of the same name, but only modifies hull damage.
- The "reload" part of rank 4 doesn't work.

---

## Details 
Form ID 002C5558
- The perk ranks should be modified to also add a "mod typed weapon attack damage" effect to affect shield damage increases.
- The skill rank descriptions should read "[...]do X% more hull and shield damage[...]"
- The entry point for the "reload" part of rank 4 should be changed to "mod ship weapon recharge rate" instead of "mod weapon reload speed", and the value should be "1.2" instead of "0.8"

## Game Version
1.7.36.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Examine the skill descriptions in the game, and look at the PERK records in Starfield.esm in xEdit.

**Comment by Constellation-VASCO** [comment]
I just looked again and the perk should also effect EM damage as well to fully bring it in line with the crew perk of the same name.

**Comment by Pickysaurus** [comment]
https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/commit/a51cf6dbb83968aa19b2ab8b3bb16811260bd46d
