### ISSUE TITLE
Marauder 115N Railgun Turret ship weapon issues

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#355]
"Magazine Size" is >0. This weapon can continue firing at normal rate until its magazine is exhausted even if the player hasn't set the power to max. This should not be the case for non-automatic weapons.

---

## Details 
Form ID 00025FB6 [WEAP]

## Game Version
1.7.36.0

## New Game
Yes

## Reproduction Steps
Look at the WEAP record in Starfield.esm via xEdit.

**Comment by Pickysaurus** [comment]
Fixed in https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/commit/a51cf6dbb83968aa19b2ab8b3bb16811260bd46d
