### ISSUE TITLE
Dialogue zoom isn't interrupted by combat

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#36]
When in dialogue, and zoomed on a character, combat can interrupt the dialogue but not the zoom. If dialogue does not resume, this results in being stuck looking at the NPC's beautiful face permanently, and having to reload a save to continue playing.

---

## Details 
I specifically noticed this while dealing with the Altair system Spacer quest, and talking to Myeong. A spacer ran away from the fight, after giving up on finding him, i went to talk to her. In the middle of the conversation, he showed up again. She stopped talking, turned around and finished him (he was very low). Being the last spacer, this triggered her natural dialogue with the other NPCs, never resuming our conversation, and I was stuck in the zoom.

## Game Version
1.7.23.0

## New Game
No

## Reproduction Steps
Talk to an NPC during a mission that requires killing enemies and those kills trigger unfocused dialogue (See details for an example). Get the fight to end without killing them all, then talk to an NPC involved in that conversation. Wait in dialogue for the enemy to return, voila, the issue should appear.

It is possible that an enemy death dialogue trigger is unnecessary, and this happens when any dialogue is interrupted by combat, but I'm unsure. Worth testing.

**Comment by Deebz96** [comment]
This type of issue would require an engine-level fix. Out of scope of the SFCP.
