### ISSUE TITLE
Sarah loves to block most of the the lockers I am trying to open

### ISSUE THREAD

**Issue by Ripper1302** [Starfield-Community-Patch/Starfield-Community-Patch#362]
If there is one justification for going solo it is not having Sarah stand in front of 30-50% of the lockers I want to open.  Can her behavior be adjusted to keep her a fixed distance away from any locker or any device with a lock.

**Comment by Pickysaurus** [comment]
I'm not really sure this is something we can fix. AI companions getting in the way is just a quirk of the Bethesda Creation Engine.
