### ISSUE TITLE
Interior Gravity Settings

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#363]
Several interior locations do not match the exterior Gravity value 

---

## Details 
<https://discord.com/channels/916686954421157930/916692282021916702/1166106689649516544>

## Game Version
1.7.36.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Visit any location in the patch.

**Comment by Pickysaurus** [comment]
[InteriorGravityFix.zip](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/files/13112359/InteriorGravityFix.zip)

**Comment by Constellation-VASCO** [comment]
Related to https://www.starfieldpatch.dev/issues/63 #63
