### ISSUE TITLE
Benzene uses incorrect chemical formula

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#367]
Benzene does not display as C6H6 in the UI. 

---

## Details 
Fix on Nexus Mods: <https://www.nexusmods.com/starfield/mods/5874>

## Game Version
1.7.36.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Acquire Benzene or scan a planet that has Benzene on it.

**Comment by Pickysaurus** [comment]
Fixed in https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/commit/872197c038e28e0296b3dffaf308cf887c09c803
