### ISSUE TITLE
Coe Estate remains locked in NG+

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#370]
When starting NG+ and skipping the main quest, the Coe Estate door would remain locked

---

## Details 
<https://www.nexusmods.com/starfield/mods/5823>

## Game Version
1.7.36.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
N/A

**Comment by Krevil** [comment]
Occasionally, the doors to the Coe Estate will remain locked after skipping the main quest in New Game Plus. This can be reproduced by following these steps:
* Begin a new game
* Enter the NG+ by completing MQ305
* Go to Akila, the doors to the Coe Estate should be locked
* Go to The Lodge and talk to Sarah to skip the main quest
* Go back to Akila, the doors to the Coe Estate will remain locked when they should have locked.

This does not seem to happen if loading a save **after** entering NG+ but **before** talking to Sarah to skip the main quest.
