### ISSUE TITLE
Companions commenting on dead companions.

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#376]
When landing at Akila City, and with Sarah set as a companion (other companions may have the same dialog option), Sarah tells the player they should talk to Sam who has many stories about Akila City, even though Sam has been killed by the Hunter. 

---

## Game Version
1.7.36

## Language
English (EN)

## New Game
No

## Reproduction Steps
Only encountered this one time. I believe it's a dialog choice offered as a random comment from Sarah when landing in Akila City and she is set as the player's companion. Occurred several hours into the game after completing "A High Price to Pay" with Sam being killed by the Hunter in that quest.

**Comment by Constellation-VASCO** [comment]
I have had it happen to me a couple of times, following the quest in the original playthrough where the Hunter kills a member of Constellation. In my first playthrough it was Sarah, where Sam would later make jokes about her always criticizing him for things he did wrong as if she was still alive (so basically running his mouth about a dead person, quite inappropiate and poorly scripted). Something similar happened in another playthrough where I let Sam die, and Andreja would drop a remark upon visiting Akila City how Sam will love it next time he's there (or something along these lines). Again the game hadn't registered the companion had died. So ya, would be nice if these issues were resolved

**Comment by Constellation-VASCO** [comment]
Barrett is dead in my playthrough. Cora tells Sam a joke on the ship, and he says to try it out on Barrett next time she sees him. He has said it about two different jokes now.

**Comment by Pickysaurus** [comment]
This ticket needs the exact line otherwise we can't find it.
