### ISSUE TITLE
Skill Fixes compilation

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#389]
Compilation of bug fixes to various perks.

---

## Details 
I've made a compilation of bug fixes to perks, called Skill Fixes: https://www.nexusmods.com/starfield/mods/5660
It includes a proper fix to the Rejuvenation perk. The community patch does not fix it the way the developers had intended; perhaps a lack of quality assurance? More info about the perk (and various other perks) can be found in the Posts tab of Skill Fixes where you can find a lot of my research. Feel free to include the mod's fixes in the next version of the patch. I'm also available to join the patch team if you could use someone with my skill set. :)

## Game Version
1.7.36.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Self-explanatory.

**Comment by Pickysaurus** [comment]
Merged into 0.0.2
