### ISSUE TITLE
Game will lose FPS after a period of time

### ISSUE THREAD

**Issue by madebylydia** [Starfield-Community-Patch/Starfield-Community-Patch#39]
## Details
After a period of time in game, the game will slowly lose FPS. Memory leakage?

## Game Version
1.7.23.0

## New Game
No

## Reproduction Steps
- Just... play the game!
- It might be interesting to try to leave the game in the background for a long period of time (Notice the difference before/after)

**Comment by Constellation-VASCO** [comment]
One thing I could notice is that everytime you open the pause menu/TAB causes a burst of VRAM usage, and if you have a low amount(4GB), it may easily exceed your limit, and cause your framerates to take a huge drop.

**Comment by Pickysaurus** [comment]
Not enough here to go on. See if the game updates from Bethesda help
