### ISSUE TITLE
Missing Facial Hair

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#390]
Facial hair appears missing when wearing a spacesuit and opt to hide your helmet. But the apparel you're wearing is a full body outfit, e.g. Hazmat.

---

## Game Version
1.7.36

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
1. Give your character facial hair (more than stubble but an actual 3d beard or moustache
2. Equip a space suit
3. Equip a helmet - preferably one so you can see your face to make it easier
4. Toggle to hide helmets in breathable locations
5. Equip a full body apparel that covers face, in this instance I used hazmat
6. Go somewhere breathable but a spacesuit is required. E.g. your ship
Or
6. View your character in the main menu by going to space suits so the hazmat doesn't appear on character
7. Check facial hair

This is most noticeable when getting in and out your pilot seat.

**Comment by TESWartortle** [comment]
[Hazmat Fix.zip](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/files/13689864/Hazmat.Fix.zip)

**Comment by Constellation-VASCO** [comment]
Thanks Wartortle!
