### ISSUE TITLE
Va'ruun Inflictor Rifle name contains [CR][LF]

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#393]
The Va'ruun Inflictor Rifle (WEAP:0026D8A0) contains the characters [CR][LF] at the end of "FULL - Name", which can mess up the UI.

---

## Details 
-

## Game Version
1.7.36

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
-

**Comment by Pickysaurus** [comment]
Replaced with more details and a link to the fix at https://www.starfieldpatch.dev/issues/486 #486
