### ISSUE TITLE
Cannot complete Power from Beyond quest

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#398]
Quest: Power from Beyond (Skink). The quest marker did not appear on my ui to show me the location of the planet. I did end up finding the planet but the "space anomaly" landing location does not appear on the planet in the starmap. I tried landing on the planet randomly and the objective updated to 'locate the temple with the scanner' but there is no distortion nor temple at any landing site I make, if it's even possible to find it that way.

---

## Game Version
1.7.36.0

## Language
English (EN)

## New Game
No

## Reproduction Steps
Hard to pinpoint the start of the bug as the quests activate once you enter the system. In this case the Cheyenne System. Though I'm not sure I had the correct amount of artifacts at the time to technically start that mission, but activated anyway. That could be the cause?

**Comment by Constellation-VASCO** [comment]
Fix: <https://www.nexusmods.com/starfield/mods/6206>

**Comment by Pickysaurus** [comment]
Duplicate of #214

**Comment by Constellation-VASCO** [comment]
Fix does not resolve the issue. This issue should not be closed.
