### ISSUE TITLE
[Typo] Starfield community patch announcement acronym

### ISSUE THREAD

**Issue by Kornil** [Starfield-Community-Patch/Starfield-Community-Patch#4]
In https://www.nexusmods.com/news/14877 there seem to be two acronyms for the Starfield community patch, "SCP" and "SFCP"

### Description
In the section "What is the Community Patch?", the first line states
> The Starfield Community Patch (**SCP**) project ...

Later in the "Spriggit, what's that?" section, just after the video
> The **SFCP** team will be working closely ...

### How to fix
Use one acronym

**Comment by Pickysaurus** [comment]
This isn't related to this repository, but thanks for the heads up.
