### ISSUE TITLE
Piloting simulation gives Piloting skill progress

### ISSUE THREAD

**Issue by CansecoDev** [Starfield-Community-Patch/Starfield-Community-Patch#40]
The piloting simulation during Supra et Ultra quest gives progress to the Piloting skill.

There is also the question; should doing something during a simulation give progress to a skill? I'd say that eliminating ships during a simulation should not count towards a skill that requires destroying actual ships to progress, not only because of the wording of the skill or trying to make sense of it, but more importantly because it trivializes the progression of that skill.

## Game Version

1.7.23.0

## New Game

No

## Reproduction Steps

Have the Piloting skill ready to be progressed.
Enter the piloting simulation and eliminate some ships.
The Piloting skill is increased, you will not be able to check the skill menu during the simulation but after leaving the progression will be there.

Attaching a save right before entering the simulation for ease of reproducing.

[Save62_DBDBB2D9_4B68616E_010932_20230903220534_18_0_4.zip](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/files/12507998/Save62_DBDBB2D9_4B68616E_010932_20230903220534_18_0_4.zip)

**Comment by stuffynotstuffy** [comment]
I'm not convinced that this is a bug. All other related ship skills will also progress in the simulator (ballistics, targeting etc.). If you go back to the simulator after the mission, the attendant says something along the lines of "back to get some practice in?".

I can see this being an intended way to train these skills, and lore wise it would make sense that a simulator could be used to better your skills in the relevant areas.

I also get the argument for this trivializing progression, but note that you could do the same thing for Fitness by sprinting back and forth after your oxygen refills to full or Medicine by taking falling damage then healing. This is just a way to have space combat whenever you want to a limited degree, and is ultimately up to the player how often they use it.

Even if this does trivialize progression to an unwarranted degree compared to the other examples, you're still gated by skill points so completing the challenges ultimately doesn't amount to much in the long run (same with other skills)

**Comment by Constellation-VASCO** [comment]
I too am unconvinced that this is a bug. I believe it is intended gameplay.

IRL we use simulators to train pilots in the military and commercially, so I don't see why it would be different in Starfield. It's simply there to provide players the option of advancing their skills without the subsequent risk to their own ship. The space combat is much more challenging than the land combat in this game and I'm sure some people like being able to hone their skills without having to reload a save and lose progress because they got bested in a 3 on 1 engagement when they have a terrible starter ship =P

**Comment by Constellation-VASCO** [comment]
It's a simulation and therefore can earn you skills, it's not a bug it's part of the game.

**Comment by Pickysaurus** [comment]
We're going to assume this is intended gameplay
