### ISSUE TITLE
All Scans for power temple

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#400]
scan never triggered any glitch to show me the temple s way. Not in "into the unknown" and not even more in "power from beyond"

---

## Details 
My scan doesn t trigger any distorsions / glitch to show me the way of the temple, so i ve found them by myself, did the puzzle, but the quest stay stuck, so i ve used the console command to get through it, but it was working for Into the unknwon" quest, but i can t find all the ID's for "Power from beyon", i ve tryed 72 hours wait, re install game, without mods, with mods, without Sarah as a crew members, doing lot of side quests meanwhile, nothing seems to work.

## Game Version
1.7.36.0

## Language
French (FR)

## New Game
No

## Reproduction Steps
get a new game, and rush the main quests without any other missions

**Comment by Constellation-VASCO** [comment]
i ve started a new game, go straight to the main quest, still work ... a script must have been broken :/ lose about 6 days of saves

**Comment by Aurelianis** [comment]
Many of these issues with temples have been fixed by Bethesda in updates since this report was created.
