### ISSUE TITLE
Optimizing bug fixed scripts

### ISSUE THREAD

**Issue by RedxYeti** [Starfield-Community-Patch/Starfield-Community-Patch#401]
I talked briefly about this on the discord with Pickysaurus and Orvid, but I am willing and able to optimize any scripts that are bug fixed. 

Mostly fixing slow functions and possibly caching commonly used properties to speed up scripts. This is very useful for people who are cpu bound.

I've already done the current scripts you've fixed and attached the source if you want to look them over.

I also have a beta on nexus that does these optimizations across most of the problem scripts in the game [here](https://www.nexusmods.com/starfield/mods/5080) and I am very open with merging with the community patch when more is known about the new VM. I wouldn't suggest doing it now as there could be adverse affects that haven't been reported yet.

[community patch.zip](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/files/13170320/community.patch.zip)

**Comment by Constellation-VASCO** [comment]
@RedxYeti can you please double-check the script optimisations still apply? I know it's taken a while to get to this!

**Comment by Deebz96** [comment]
The script fixes have been redone on the official source files now. I'll close this issue, as the originally provided scripts no longer apply. RedxYeti, if you are still willing to assist, you can find us in the Starfield Modding discord server.
