### ISSUE TITLE
Quest Worlds Apart

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#402]
This quest wont trigger. I have found after scouring the internet, that Baretts last companion quest is preventing Worlds Apart from triggering. While the quest does finish and gives you credit, it doesnt technically finish. After you finish the last companion quest and ask him about the case, the only options you are given to talk about is the artifact that he found. I had him set as my companion for several other missions afterwards and even slept for nearly a week straight and nothing. I eventually found the console command and started Worlds Apart manually.

---

## Details 
Worlds Apart Quest ID SetStage 2fae 1

## Game Version
1.7.36

## Language
English (EN)

## New Game
No

## Reproduction Steps
i have not tried to recreate it, but everything i have read from many many reddit posts points towards Barretts last companion quest. i hope this helps.

**Comment by Constellation-VASCO** [comment]
This mod claims to fix this issue.  https://www.nexusmods.com/starfield/mods/5683
This fix is also now incorporated into a larger "Skill Fixes" mod, some of which should likely be incorporated into this patch.  https://www.nexusmods.com/starfield/mods/5660

**Comment by Aurelianis** [comment]
Fix was added to 0.0.2 pre-release

**Comment by Aurelianis** [comment]
This was fixed in SFCP and is related to the bug with the Leadership Skill causing incorrect actor values which triggers the companion reactions to various quest lines (this one being after you discover what the Unity is).
