### ISSUE TITLE
Cannot enter Deimos Staryard

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#406]
I fly to Sol from another system and fly to the Deimos Staryard. Hail the Staryard and dock as per normal. I get up from the Captains chair, goto the docker inside the ship and attempt to enter the Staryard. The audio that normally plays for the entrance animation plays, the sound of the hatch opening but it never opens. I can click to activate the door, hatch, stairs, doesn't matter. Audio "hatch opening" sound plays but nothing.  am unable to enter the Staryard.

---

## Details 
I have about 290 hours into the game and have never had a problem entering any Staryard until today. I had just started the first quest of the UC Vanguard questline and decided to take a detour to Deimos to work on a new ship I have been working on that requires I visit multiple Staryards. I was able to dock but could not enter. I thought perhaps I was locked out so I left and played the first Vanguard mission. After, I came back and found that I still could not get in. Decided to research this and found other reports of the same issue:

https://steamcommunity.com/app/1716740/discussions/0/3824173836664650000/

I was able to get around the issue. While standing inside my ship near the docker I saved the game and quit out to the main menu. I loaded the save up and I was immediately able to enter normally. I am using the following mods I felt might be relevant:
- No Instant Ship Exit and Board: note this has been installed since almost the beginning (200+ hours) 

## Game Version
1.7.36

## Language
English (EN)

## New Game
No

## Reproduction Steps
Fly to the Deimos staryard. Get up from the Captain's chair. Walked to the docker and attempt to enter the Staryard.

**Comment by Deebz96** [comment]
Never been able to replicate this issue with any star station. Without further details, unable to troubleshoot.
