### ISSUE TITLE
Sarah Commentary after entering a Staryard

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#407]
Sarah will often comment that the crew is loaded and ready to depart, even though I have just arrived and just entered a Staryard.

---

## Details 
Arrive at a Staryard and enter it. With Sarah set as the companion she will often state "The crew is loaded and ready to depart" immediately after the staryard cell loads. Problem is you are just arriving at the Staryard not leaving. Suspect this is just a random comment available from a pool of comments. This comment should only trigger after some x period of time spent at the Staryard and even then only as you approach the door to leave. 

## Game Version
1.7.36

## Language
English (EN)

## New Game
No

## Reproduction Steps
Fly to any staryard and enter it with Sarah set as your companion.

**Comment by Constellation-VASCO** [comment]
Other companions make similar comments on seemingly all starstations; Sam talked about coming home to Cora when we boarded the Key.

**Comment by Aurelianis** [comment]
Fix was added to 0.0.2 pre-release
