### ISSUE TITLE
Typo in Nikau Henderson's introductory remarks

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#41]
When you board Deimos Staryard and speak to Nikau Henderson for the first time, he says "What do we have here? A civilian in my staryard?" In the subtitles, the word "civilian" is spelled "civlian" which is incorrect.

---

## Details 
N/A

## Game Version
1.7.23.0

## New Game
Yes

## Reproduction Steps
- Board Deimos Staryard
- Walk over to Nikau Henderson and speak to him for the first time.

**Comment by Pickysaurus** [comment]
https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/commit/a51cf6dbb83968aa19b2ab8b3bb16811260bd46d
