### ISSUE TITLE
Annihilator Rounds still fire without mod

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#411]
All particle beam weapons - Novalight, Big Bang, Va'ruun Inflictor Rifle and Inflictor Pistol (dubbed Star Shard in-game), except for Novablast in my experience - produce an Annihilator Round effect as though the weapon mod by that name were installed when it is not installed.

---

## Details 
Annihilator Rounds is a weapon mod that can be applied to Particle Beam type weapons for a chance to produce residual area-of-effect damage as a glowing ball of sparks on the ground. Even without this mod installed, those weapons listed above produce this effect about once every five or so shots that hit an enemy. The AoE damage affects companions and friendlies which causes obvious issues, and the only way to avoid producing it is simply not to use these weapons, regardless of which mods they have - or don't.

## Game Version
1.7.36.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Acquire a Va'ruun Inflictor Rifle or Pistol (in the console, searching help "inflictor" 4 weap will show results for both); without the Annihilator Rounds weapon mod on it, use it on several enemies. Since it is an RNG function, it may take several tries, but you should see a residual ball of white sparks on the ground where the weapon hit an enemy. This effect is supposed to happen only with the Annihilator Rounds mod, a mod that is meant to be used advisedly since it's "banned by nearly every government", not ejected randomly by every weapon of the particle beam variety.

**Comment by Deebz96** [comment]
This is intended design. These appear upon critical hits.
