### ISSUE TITLE
Matters of the Hart - No Enemies Spawning

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#412]
After you get the location of the cache and upon approaching it. two enemy ship lands nearby but there are no enemy spawning and the quest expects you to kill (the enemies that supposed to spawn) them in order to proceed with the quest. now Sam, Cora and Lilian is stuck with me permanently. preventing me from proceeding with other companion and main quest.

---

## Game Version
1.7.36

## Language
English (EN)

## New Game
No

## Reproduction Steps
I didnt do a new game+ walkthrough yet. but i see many people on reddit reporting on the same issue.

**Comment by Aurelianis** [comment]
This is related to https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/issues/221 and has been fixed by Bethesda.
