### ISSUE TITLE
Weapons don't always reload while being healed

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#417]
After using a med pack or trauma pack, and while the healing effect is still being applied, weapons don't always reload successfully despite the animation playing normally.

---

## Details 
Different weapons seem to be affected by a higher or lower change of this occurring.

## Game Version
1.7.36

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
The most consistent weapon I've found that suffers from this bug is the Big Bang shotgun. Lower your characters health by some means (so the med pack has something to actually heal), then apply a med pack/trauma pack, etc. While the healing effect is occurring, reload the Big Bang. The animation will play normally, but the weapon won't actually be reloaded. It will work correctly again as soon as the healing effect is complete.

**Comment by Deebz96** [comment]
Unable to replicate this one with the steps provided. It may have been fixed officially.
