### ISSUE TITLE
Bug - empty enemy ships

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#418]
I found a game breaking bug that prevents npc's from spawning inside boarded or landed spaceships. Ships that have landed no longer open the landing bays and are empty inside as well as any ships you board are empty. This even prevents starborn from spawning and strangely enough allows players to enter and steal their landed spacecrafts.

---

## Details 
I believe this bug is caused by the "kill all npcs on ship or leave ship" misc quest not properly finishing and thus breaking the current save-file. earlier save-files will not be affected and starting another newgame+ instance will also fix this. But once a save is affected by this bug it appears to be broken forever.
I do not know exactly how to replicate this bug.

## Game Version
1.10.0 (since launch)

## Language
English (EN)

## New Game
No

## Reproduction Steps
Boarding enemy ships. May have been initiated by a vanguard misc mission or one of the early crimson fleet quests that has you board a trade vessel to kill someone. But wouldn't know for sure as it seems random.

**Comment by Constellation-VASCO** [comment]
https://www.starfieldpatch.dev/issues/268

**Comment by Constellation-VASCO** [comment]
Current mod to fix and discussion on the topic:

https://www.nexusmods.com/starfield/mods/5668

**Comment by Constellation-VASCO** [comment]
I had the same problem in the "Matters Of THe Hart" quest at the smugglers cache.  The smugglers would not exit their two ships to attack you , the quest could not progress .

**Comment by Aurelianis** [comment]
This is related to https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/issues/221 and has been fixed by Bethesda.
