### ISSUE TITLE
Eye of the Strom 

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#430]
When I reach to captain office and trying to put the core it get bug out and I'm not able to progress that misson

---

## Game Version
1.7.36

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Fix

**Comment by Constellation-VASCO** [comment]
Assuming this is being stuck at credtank transfer, I attempt to address it here: https://www.nexusmods.com/starfield/mods/7429

**Comment by Aurelianis** [comment]
Fixed in v1.9.47.0
"Eye of the Storm: Fixed an issue that could cause data transfer to not start after placing the Data Core."
