### ISSUE TITLE
Leadership perk effects

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#447]
2C890D Skill_Leadership - broken affinity gains.

---

## Details 
Ranks 2, 3, and 4 accidentally reduce the bonus from rank 1 from 1.25 to 1.15.

## Game Version
1.7.36

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
go look at the record.

**Comment by Aurelianis** [comment]
Fixed in SFCP
