### ISSUE TITLE
Quest NPC appearing as a security guard

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#45]
There is an NPC with the UC Vanguard questline which is called Hadrian, This NPC I spotted twice in my playthrough once as a security guard and once as a quest NPC.

---

## Details 
Quests: 
Completed:Supra Et Ultra, Grunt Work, Delivering Devils, Eyewitness, 
Current: Friends like these

## Game Version
1.7.23.0

## New Game
No

## Reproduction Steps
Happens randomly, NPCs may be reused for different purposes but quest NPCs shouldn't

**Comment by Aurelianis** [comment]
I have seen other NPCs that look similar to Hadrian but never exactly like her. They share the same hair style and have a few similar features, but they are not the same. The game also reuses the same faces for many different NPCs. Bethesda has always done this. For example, in Fallout 4 there are only 2 faces for the 20 or so Diamond City Security Guards that are spawned at any given time. This is not a bug that needs to be fixed.
