### ISSUE TITLE
New Atlantis Spaceport, Waterfall Promenade, The Well elevators have a menu in an incorrect order

### ISSUE THREAD

**Issue by ja231c** [Starfield-Community-Patch/Starfield-Community-Patch#472]
The Well cannot physically be located above the Waterfall Promenade, especially not with the elevator door facing the direction it's facing (as that would put The Well floating in the air above the Waterfall Promenade), the only location it can be located is below the Spaceport.

The menu should be reordered from this:
1. The Well
2. Waterfall Promenade
3. Spaceport

To this:
1. Waterfall Promenade
2. Spaceport
3. The Well

**Comment by Constellation-VASCO** [comment]
Where are you getting the lift from to see this?

**Comment by ja231c** [comment]
The lift in question is the one behind Jemison Mercantile, all three instances of the panel show the same incorrect order.

**Comment by Deebz96** [comment]
This is actually correct. The Well is situated above the entire Spaceport area, directly below MAST.
