### ISSUE TITLE
Va'ruun inflictor name has a new line in it

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#478]
Va'ruun inflictor name has a new line in it. This causes issues with the UI

---

## Details 
Remove new line in record and strings to fix

## Game Version
1.7.36.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Look at va'ruun inflictor in menus

**Comment by Constellation-VASCO** [comment]
https://www.nexusmods.com/starfield/mods/6132

**Comment by Deebz96** [comment]
Will use #486 for this issue.
