### ISSUE TITLE
The Audition

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#48]
At the stage where it says "Meet Briggs" for the first time, I had left the building to resume a different quest. When I had returned, all the NPCs related to the quest had been stuck in a "busy" state. I haven't been able to talk to any of them. If I knew the console command to advance the stage, I can get around this bug. This is a questline for the Ebbside Strikers at Neon. Current quest summary is "I've met up with one of the Ebbside Strikers at Madame Sauvage's Place. Her name is Andrea, and she wants me to speak to her boss, Briggs. I should follow her to see if there's a place for me within their ranks."

---

## Details 
Not sure what the Quest ID is nor what stage this is.

## Game Version
1.7.23

## New Game
No

## Reproduction Steps
Leave Madame Sauvage's Place while following Andrea to Briggs. Return after sometime and the NPCs will be bugged.

**Comment by Aurelianis** [comment]
Fixed in v1.10.31.0
"The Audition: Addressed an issue with later passing a door if the area was left while Andrea escorted the player."
