### ISSUE TITLE
Vasco spawn marker in Ship interior cells.

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#482]
Ships other than the Frontier don't seem to have a functioning VASCO interior spawn point

---

## Details 
Currently, there is a bug in the game that causes Vasco to get stuck in your ship hallways.
Based on tests the source of the problem seems to be that other than the Frontier, the ship interior spawn markers for Vasco in every other ship is bugged.

When you land on a planet, outside the ship, Vasco spawns in front of the landing bay (stairs or the main ramp). But when you are in your ship, Vasco is supposed to spawn besides the landing bay hatch or door inside the ship (like when you just assign him while you're inside). But this is currently bugged, and the exterior spawn point coordinates carries over and glitches Vasco upwards through the ship in the same horizontal coordinates he was supposed to be on the ground.

Only way to prevent Vasco from blocking critical paths (to the cockpit for example) is moving the landing bay on your ship to a place where the ground spawn location does not cross upwards into any important HABs. Frontier is the only ship that does not have this problem.

## Game Version
1.7.36

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Have a ship other than the Frontier (preferably a decently sized ship with more than one floor with an interior cell above where Vasco would be on the ground outside) - Have Vasco as a crew member - Land on a planet and go outside - come back inside the ship (board the ship normally) - Try to find Vasco inside - He should be glitched upwards from where he was on the ground outside - No mods installed.

**Comment by Constellation-VASCO** [comment]
Can report that this bug is still happening in 1.8.86 - and he blocks pathways in real annoying ways.  I want Vasco as crew on my ship, but I get super-annoyed with this one.

**Comment by Aurelianis** [comment]
Fixed in v1.10.31.0
"Fixed an issue that could cause Vasco to appear incorrectly in the player's ship."
