### ISSUE TITLE
normal weapons modded into EM given to companions

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#484]
when you mod a weapon in game, give it a non-letal effect(Eletromagnetic), and then give it to a companion, in their hands it turns to a lethal weapon and they can kill enemies with it.

it affects every weapon i tested, since i don't want my companions stealing my XP, and the normal base EM weapons that comes with the effect, needs charging, which my companions can't use well, i tried give them weapons with modded EM like the breacher and the laser weapons that you can apply the constalation skin and both turn lethal in their hands.

---

## Game Version
on release

## Language
English (EN)

## New Game
No

## Reproduction Steps
just mod a weapons that has the has a slot to turn it's damage to EM, and gives it to a companion.

**Comment by Deebz96** [comment]
This seems to no longer be a bug with the game.
