### ISSUE TITLE
Va'ruun Inflictor Rifle new line in name fix

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#486]
For some reason, there are [CR][LF] (Carriage Return, Line Feed) characters at the end of the name for the Va'ruun Inflictor Rifle, which can mess with the UI.

---

## Details 
<https://www.nexusmods.com/starfield/mods/6132>

## Game Version
1.7.36.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
N/A

**Comment by Constellation-VASCO** [comment]
Possible form ID [0026D8A0]

**Comment by Constellation-VASCO** [comment]
If the form ID is the one shown above this is not a safe fix as it contains reflection data. It may be fixable in the localisation step though.

**Comment by Constellation-VASCO** [comment]
This can be fixed now the CK is available!

**Comment by Deebz96** [comment]
This will be fixed in 0.1.8.
