### ISSUE TITLE
Character's eyes shut/bugged in 3rd person

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#489]
When going into 3rd person, within 3-5 minutes of playing, looking at your characters face will show their eyes fully closed, eyes bugged out looking to the far bottom right, eyes squinted 85% and stuck, or eyes/eyelids overlapping each other. There is no fix for this besides re-loading the game, only for it to happen 3-5 minutes after again. 

---

## Details 
N/A / Entire Game

## Game Version
V1.7.36.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Play the game anywhere at any point and switch to 3rd person. Then look at your characters face. CONSTANT eye glitching.

**Comment by Deebz96** [comment]
This is an engine level bug, out of scope of the SFCP. Another mod to fix it is here: https://www.nexusmods.com/starfield/mods/8653
