### ISSUE TITLE
Suspicious Activities Subtitle Misspelling

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#49]
When reporting the impending robbery to Karson Endler, and choosing to mention Theresa, his response subtitles misspell "with" as "wth". (typo)

---

## Details 
Quest found in the New Atlantis Well, which may need to be started by becoming a reporter at SSNN beforehand.

## Game Version
1.7.23.0

## New Game
No

## Reproduction Steps
Complete the Quest 'Primary Sources' up until you talk to Theresa at Kay's Place in the Well. She will mention a possible robbery. Investigate this robbery, and choose to report it to UC security. When choosing to mention Theresa as your dialogue option, and turning subtitles on, this bug will occur.

**Comment by Pickysaurus** [comment]
Found two instances of this:
> Those thieves won't be so cocky wth security on patrol. 
[0033A879]

> Damn mercs just don't know how to take a hint. Hey rook, wanna help me wth some target practice?
[0022B6E4]
