### ISSUE TITLE
sprint headtracking is busted again

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#490]
head keeps locking looking left when running in 3rd person view 

---

## Details 
I've downloaded the sprint head tracking bug fix before and it worked beautifully however the author said that the fix was included in the community patch however ever since getting the community patch the head tracking got messed up again even when going back to the original fix didn't help

## Game Version
1.7.36

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
jus run in 3rd person long enough and it'll happen

**Comment by Constellation-VASCO** [comment]
Are you absolutely sure you enabled the patch properly? If reverting back to the loose fix doesn't help then there might be some specific condition in your game that is causing a case the fix doesn't apply to.

**Comment by Deebz96** [comment]
This was fixed officially.
