### ISSUE TITLE
Juno AI Missing - 2 People stay on ship

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#494]
After completing the Juno AI mission, I let Juno free and took the 2 Ryujin guys back to Neon, and the mission ended, however the 2 guys stayed on the ship.

---

## Details 
After completing the mission and going back to Neon for the 2 Ryujin guys (Operative Collins, and Operative Khambatta) to get off my ship, they ended up staying on board. I have done a number of other missions since completing this, and when I am in the ship you can see dialog happening of the two guys. I flew to a planet just now and they are standing next to me in the cockpit, cant talk to them other than 1 liner NPC chat you get from random NPCs, and so I have no idea what they are sticking around for other than this being a bug.

## Game Version
1.7.36

## Language
English (EN)

## New Game
No

## Reproduction Steps
Unsure how to recreate it other than doing the Juno mission again from an old save, but I suspect it will be the same, unless this is a one off glitch?

**Comment by Constellation-VASCO** [comment]
Did you actually enter the starport at Volii Alpha or did you just fast-travel to Neon City and then fast-travel away? You need to either land at Neon and exit your ship, or fast-travel to Neon City and then take the elevator to the starport.

**Comment by Constellation-VASCO** [comment]
Yeah I landed on Neon and got out of the ship, the quest completed, and then I went into Neon and did something else, and then left on the ship again. Didnt notice the guys still on the ship till a few missions later, and they are still currently standing on the bridge next to me, just saying random NPC things, you cannot actually talk to them. So weird.

**Comment by Deebz96** [comment]
Have been unable to replicate this issue across three characters. Possibly a fluke.
