### ISSUE TITLE
jupiter is off its axis in starmap bug

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#498]
this bug isn't a game breaker and its barely visible but breaks the immersion when jupiter is seen in a diffrent axis each time you visit the sol system. some photos https://www.reddit.com/r/Starfield/comments/17clecs/is_jupiter_sideways_for_anyone_else_or_is_it_just/ (notice: planets in starmaps NEVER change thier axis, they only rotates) 

---

## Game Version
1.7.36

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
just spend time, preferably sleeping for long hours, but you need to be outside the sol system for this to effect. sleeping/spending time the sol system wont contribute to the bug

**Comment by Deebz96** [comment]
This affects every planet intermittently, and seems to be an engine-level bug. Unable to fix with the SFCP.
