### ISSUE TITLE
Stroud 1LA and 1LB bottom modules

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#499]
Stroud 1LA and 1LB bottom modules all have the same NIF file. I have already put up corrected NIF's on my modpage, you can download them and add them to a next release of the patch.

---

## Details 
smod_struct_stroud_cap_portbtm_1l_a
smod_struct_stroud_cap_portbtm_1l_b
smod_struct_stroud_cap_stbbtm_1l_a
smod_struct_stroud_cap_stbbtm_1l_b

## Game Version
1.7.36.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
None really just wrong NIF's found while i was working on my shippart mod

https://www.nexusmods.com/starfield/mods/6029

Download section contains the corrected NIF's

**Comment by Pickysaurus** [comment]
Thanks for sharing. Do you happen to have a screenshot comparison of before/after the fix? I'm not sure I full understand what you're fixing.

**Comment by Constellation-VASCO** [comment]
The Vanilla bottom modules for Stroud 1LA and 1LB have 4 seperate entries but they all share the same NIF. That NIF does not fit the other parts like the Stroud Cowl A.

smod_struct_stroud_cap_portbtm_1l_a
smod_struct_stroud_cap_portbtm_1l_b
smod_struct_stroud_cap_stbbtm_1l_a
smod_struct_stroud_cap_stbbtm_1l_b


Vanilla (notice the "square bottom of the back module compared to the front Cap):
https://staticdelivery.nexusmods.com/mods/4187/images/6029/6029-1698775424-1715432792.jpeg

Fixed NIF's now fitting flush with the curves of the front Cap:
https://staticdelivery.nexusmods.com/mods/4187/images/6029/6029-1698775434-713578644.jpeg

**Comment by Constellation-VASCO** [comment]
After further investigation it's not really a bug, just lazy Bethesda, the bottom NIF's fit the Stroud Landing gear, they just did not want to create 4 extra bottom modules I guess to fit those end caps :-) 

I'll fix that in my mod

NOT A BUG can delete or close
