### ISSUE TITLE
Vasco Robot First Pirate scene

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#5]
Vasco audio issue.

---

## Details 
Vasco the robot helps in the fight against the pirates. Once the fight is over you can still hear his gun shooting.

## Game Version
1

## New Game
Yes

## Reproduction Steps
Just play the game.

**Comment by RPINerd** [comment]
Cannot duplicate this, his audio never got hung for me during the entire pirate outpost

**Comment by Constellation-VASCO** [comment]
Comment

**Comment by Aurelianis** [comment]
Played this scene multiple times (probably at least 20, if not more) and have never had this issue happen. Closing due to not being able to reproduce.
