### ISSUE TITLE
Benzene fix does not apply to all locales

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#508]
Benzene fix does not apply to all locales. 

---

## Details 
<https://www.starfieldpatch.dev/issues/358>

## Game Version
1.7.36.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
n/a

**Comment by Pickysaurus** [comment]
Fixed in Polish here: https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/commit/8100a389ec8545bf4aad3daab89dc381b97e9f92

Fixed for Spriggit here: https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/commit/19d33d148751ba31690a3a4acc91e6f26b3e64cb
