### ISSUE TITLE
You? can't follow unless crew

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#516]
You?, your alternate self from one of the alternate universes, has no option to be your follower unless they are also crewed on your ship.

---

## Details 
If You? is not assigned to your crew, there is no dialogue option to have them be your follower.
If they are your follower and crewing your ship and you unassign them from crewing your ship, they will immediately stop being your follower.

## Game Version
1.7.36

## Language
English (EN)

## New Game
No

## Reproduction Steps
Have You? not following you and not on your crew.
Try talking to them, there is no dialogue to have them follow you.
Try assigning them to crew, talk to them, have them follow you.
Unassign them from your crew, and they'll stop being your follower.

**Comment by Krevil** [comment]
I'm not sure that this is a bug, this is the behavior for all crew who aren't the main 4 members of Constellation. It sounds like a good idea for a mod though.

**Comment by Deebz96** [comment]
This is intended behavior for crew followers.
