### ISSUE TITLE
"Other You" follower changes appearance 

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#522]
"Other You" follower will change appearance when player changes appearance at enhance.
Fixed in mod linked below.

---

## Details 
https://www.nexusmods.com/starfield/mods/5426

## Game Version
1.7.36

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
https://www.nexusmods.com/starfield/mods/5426

**Comment by Pickysaurus** [comment]
Based on a bit of digging by connerria, it doesn't appear that "Other You" is supposed to change their look when you do. This dialogue distinctly mentioned you having a difference appearance to them. 

![image](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/assets/31670524/48e6af73-076f-459d-bbda-78f3665a1cfc)

**Comment by EpicestGamer** [comment]
Now that the Creation Kit's been released we've gotten original source code (and comments!,) so I've decided to go back and check the Other You Elite Crew Script. Troublingly it revealed this to be intended behavior as the `CopyAppearance` function apparently is not completely persistent:

```
State hasbeentriggered
    Event OnLoad()
        ;do nothing
    EndEvent

    Event OnUnload()
        gotostate("WaitingForPlayer") ;Copy Appearrance needs to be called once per Load since it can reset
    EndEvent
EndState
```

If you want to work around this issue my recommendation is doing something like the following:
```
State hasbeentriggered
    Event OnLoad()
	;Copy Appearrance needs to be called once per Load since it can reset
        ;have this actor match the player
        Actor PlayerREF = Game.GetPlayer()
        Self.WaitFor3dLoad() ;wait for 3d to fully load
        CopyAppearance(PlayerREF)
    EndEvent

    Event OnUnload()
        ;Do Nothing
    EndEvent
EndState
```

This will avoid calling `ForceRefTo` multiple times (and just generally avoids repeating work that's already been done,) while still avoiding the issue BGS ran into, but it will bring back the non-immersive face swap.

I haven't had any issues without `CopyAppearance` being repeatedly called, personally. But that's just me. I'm not sure what the correct path forward for your project is. :)

Best Regards
\- EpicestGamer
