### ISSUE TITLE
Character freezes in Third person shooter mode 

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#527]
My playable character freezes in 3rd person mode. 

---

## Details 
Mostly happens during a fight. The body disappears only the gun and the suit is visible and frozen... Lost numerous fights due to this as the enemy shots are registered and lowers the health... I am playing the NG+ mode and has happened thrice, since the amalgest casino visit.

## Game Version
1.7.36.0

## Language
English (EN)

## New Game
No

## Reproduction Steps
I haven't created the issue. But it's happening all of sudden now and quite frequently. I have a screenshot of it if you want.

**Comment by Deebz96** [comment]
This one seems to be unique to your game.
