### ISSUE TITLE
Can't scroll UI up while bottom item is selected

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#53]
In most scrollable UI menus, the user is unable to scroll up while the bottom item is selected.

---

## Details 
There might be more but these are the ones I've tested so far.
Affected scrollable menus:
- Display
- Controls
- Save
- Load
- Inventory
- Container
- Barter
- Missions

Unaffected scrollable menus:
- Bindings
- Help

## Game Version
1.7.23

## New Game
Yes

## Reproduction Steps
1. Navigate to one of the affected menus
2. Move to a position where the menu can be scrolled up
3. Select the bottom item in the window
4. Attempt to scroll the inventory up with the mouse wheel or scrollbar

**Comment by Deebz96** [comment]
This one was fixed by Bethesda at some point.
