### ISSUE TITLE
Sarah's dialogue misspells doppelganger.

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#533]
In the New Game Plus variant universe where you encounter your non-starborn self when you arrive at the Lodge, Sarah's dialogue contains a misspelling for doppelganger. It is spelled doppleganger instead.

---

## Game Version
1.7.36

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Go to the Lodge on a New Game Plus where you encounter the non-starborn version of yourself and listen to Sarah's dialogue.

**Comment by TESWartortle** [comment]
Fixed on Issue #730
