### ISSUE TITLE
Blast Zone Rocks missing

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#534]
In the Akila City mission Blast zone, the rocks you are supposed to blast/cut away with your cutter are missing making it impossible to complete the mission

---

## Details 
The rocks that you are supposed to blast away with your cutter are missing from the area they are marked at with the mission markers

## Game Version
1.7.36.0

## Language
English (EN)

## New Game
No

## Reproduction Steps
Accept the mission in Akilia City

**Comment by Pickysaurus** [comment]
DUPLICATE OF #325
