### ISSUE TITLE
Lodge Loading Door Doesn't Work

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#535]
Occasionally when fast travelling back to the lodge after a mission that requires going there, the door will be stuck in a semi-open position, and nothing happens when activating it. 

![image](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/assets/109992824/b9045daa-6974-4a63-a002-35fc8bebe93e)

---

## Details 
I've had this happen at the Lodge mostly, but there have been a couple times when it occurred on the yellow door in Neon by the spaceport elevator that takes you to Ebbside.

Fast travelling away and back again will sometimes fix it, but for the Lodge I usually just boost up to the door at the roof garden.

Reloading a save also seems to fix it.

NewAtlantisToLodgeDoorREF [0005C480]

## Game Version
1.7.36.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
It just happens randomly when fast traveling to the lodge at the end of a quest that requires going there. The last time it happened when returning after getting the first power in MQ104A

**Comment by Pickysaurus** [comment]
I've seen this is both Skyrim and Fallout 4 so it's an engine level bug. Not sure we can fix it without a hack.

**Comment by Aurelianis** [comment]
Since this is likely something that SFCP cannot fix and I reported it, I'm going to closet this out as unplanned.
