### ISSUE TITLE
Missing Geometry in New Atlantis

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#54]
After boarding a ship, stealing it, and flying to The Den in the Wolf system, geometry in New Atlantis breaks. The doors to the right leaving the spaceport are missing, you can walk through them and then under New Atlantis. The grate when leaving the Spaceport has several gaps that you can fall through after this bug is encountered. The Trade Authority Terminal also disappears when you trigger this bug.

---

## Game Version
1.7.23.0

## New Game
Yes

## Reproduction Steps
Board an enemy ship, kill everyone, take the ship, fly to Wolf, dock at The Den, register the ship. Done.

**Comment by TESWartortle** [comment]
This is a known bug that binds NA. Fix tbd in a future update from BGS as of v1.8.88.

**Comment by Aurelianis** [comment]
Fixed in v1.8.88
