### ISSUE TITLE
Player falls out of AI ships on takeoff if inside landing bay

### ISSUE THREAD

**Issue by W-Drew** [Starfield-Community-Patch/Starfield-Community-Patch#55]
When AI ships depart a planet, the player will travel to space with them if they have boarded the ship. Todd even called this out as a feature during one of his interviews. However, if the player is only part-way into the ship in the landing bay but has not climbed the ladder to enter the the ship interior proper, the bay door will close, the ship will take off, and the physics engine will fling the player out of the ship before it reaches orbit:

https://www.youtube.com/watch?v=kaL1vZjDs_A

One solution may be to teleport the player into the ship interior when this happens, but this will prevent the player from accessing loot from any enemies in the bay in space, as the landing bay is only accessible planetside. Another option may be to disable AI takeoff if any player or actor is within the landing bay. This could be done either before or after the landing bay doors shut: if the doors close, the player will be forced to enter the interior to proceed, and the takeoff sounds could be played to give the impression that the ship had actually taken off. If the closing of the doors are also blocked in addition to takeoff, it can avoid trapping the player.

**Comment by Constellation-VASCO** [comment]
I also experienced this. On Altair 1 during 'Groundpounder' mission, the ship that drops Spacers in the final assault on the research complex has an open cargo bay you can walk into. Unfortunately the bay door closed behind me while I was looting the corpses and there was no way to access the ship (no ladder/door to enter). The ship took off and reached world limits and launched me out of the ship back towards the ground.

**Comment by Deebz96** [comment]
Valid issue, but this one isn’t fixable within the scope of this mod.
