### ISSUE TITLE
Starborn Suit Voice Modulated Doesn't Apply

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#550]
It seems that, even if they are wearing the armor, the voice modulation wont apply to lines delivered in settlements-- maybe because the game doesnt realize they are wearing their suit, helmet up, not their casual outfit.

---

## Details 
Any of the Starborn endgame suits, any constellation companion.

## Game Version
1.7.37

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Equip starborn suit on any companion. Interact. Hear the voice modulation. Travel to Akila City, let them have ambient dialogue. No helmet audio.

**Comment by Deebz96** [comment]
This is an engine-level issue with all spacesuits. Voice modulation will only last until a character's 3D is unloaded, then it reverts to a default modulation. This will require either an official fix, or an SFSE fix.
