### ISSUE TITLE
Rejuvenation still broken.

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#551]
I have a character with Rejuvenation Rank 3 and there is still no health regeneration in combat.

---

## Details 
I tested by hiding near enemies where combat mode continued for at least a couple minutes before they gave up.  My health bar did not move at all for those couple minutes.

## Game Version
V1.7.36.0

## Language
English (EN)

## New Game
No

## Reproduction Steps
I guess I could start a new game, play through the tutorial, use the console to force my character to have Rejuvenation rank 3, then seek out a combat and let myself get injured, then run around and see if it works.  I have not done this.

**Comment by Constellation-VASCO** [comment]
Are you absolutely sure that you had the mod installed and enabled properly?

**Comment by Constellation-VASCO** [comment]
Great question.  I'm not great with mods and I let Vortex do my thinking for me so it's very possible I did something wrong.

I installed the mod via Vortex, which shows v0.0.1 installed and when I check for updates it seems happy with that.  Vortex did assign other mods after the SCP in the deploy order (although SCP is the one I installed most recently) and I don't see how to force it to deploy later in the list, in case that matters.

Is there something else I can check in-game to know whether the mod is obviously working or not?  Most of the changes seem kind of "under the hood" so I'm not sure how to verify.

**Comment by Constellation-VASCO** [comment]
Updated to v0.0.2.  Made sure all other mods are updated to most recent versions.  Installed Nukem's Plugins.txt enabler which I did not have before.  Checked Steam/steamapps/common/Starfield/Data and verified StarfieldCommunityPatch.esm file is there.  Activated Vortex Junction to ensure Starfield's weird two data folders issue would not cause problems.  Issue persists.

**Comment by Constellation-VASCO** [comment]
Did you follow all the instructions on the mod page. It sounds like you didn't enable the plugin by adding it to your plugins.txt file.

**Comment by Constellation-VASCO** [comment]
Hm, thank you, I did not.  I just checked for the plugins.txt file in %localappdata%\Starfield and the file did not exist at all.  (The folder is there but Pipeline.cache is the only file in it.)  On a long shot I tried creating plugins.txt and adding *StarfieldCommunityPatch.esm to it, but that didn't work either.  I guess the Vortex installation just didn't work period, which is odd because all my other mods seem to work fine through Vortex.  Tonight I'll try removing the patch from Vortex and doing the manual install instead.

**Comment by Constellation-VASCO** [comment]
Your plugins.txt should look something like this:
```
# Last Updated by Vortex 2023-10-7 18:29:30
*StarfieldCommunityPatch.esm
```

Note the first line MUST be a comment (starting with the #). This is explained on the plugins.txt enabler page.

**Comment by Constellation-VASCO** [comment]
If you install v0.0.3 https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/releases/tag/0.0.3

You can run a console command to check it's actually installed.  `cgf "SFCP:SFCPUtil.ShowSFCPVersion"`

If that command doesn't work after installing 0.0.3 you definitely haven't installed it properly.

**Comment by Constellation-VASCO** [comment]
Weird - I just installed 0.0.3 after fixing my plugins.txt which somehow got emptied, and on loading my savegame, I'm being told that achievements are disabled (again), but brunch's Achievement reenabler still seems to be in place. SCP giveth and it taketh away?

**Comment by Deebz96** [comment]
This was fixed officially by Bethesda.
