### ISSUE TITLE
Screen Fading in and out after Neural Transplant

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#565]
Ever since I agreed to have the Neural Transplant "Mind Controller" installed into my character, my game has acted like I am going in and out of consciousness, like when I was waking up from the anesthesia. My O2 bar is completely red and never seems to recover, so my screen keeps fading in and out, getting blurry, then bouncing back to normal. It also has the sound fading in and out like I am losing my hearing, or passing out as it gets blurry. I am unable to locate the save game for before this happened, so I am not sure I can fix it. Hoping its not a corrupt save, as I would hate to lose all my progress.

---

## Details 
I think this was from the "Sabotage" questline that is right after "the key ingredient" questline, on the way to the "executive level" achievement. It started happening after the step where I agree to get the mind control implant installed. As I woke up, I faded in and out, but it continued and never stopped. I thought it might just be a side effect that would go away, but it never did

## Game Version
1.7.36.0

## Language
English (EN)

## New Game
No

## Reproduction Steps
I do not remember the choices I made, but I was sarcastic when I spoke, and agreed to the implant installation. That is all I did.

**Comment by Deebz96** [comment]
Unable to replicate, will need more details to investigate. Most likely a one-off issue.
