### ISSUE TITLE
Infinate Phased Time Bug

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#567]
Randomly phased time keeps going infinate never ending and causes problems with using weapons.

---

## Details 
When it happens phased time will never end and you can only shoot one shot from a weapon, then you have to switch wepons to fire one shot with another then switch back.

The only way i have found to make it stop is to eliminate all active enemies using the one shot with a weapon, switch wepon fire one shot then switch to first. Then once all enemies are dead sitting in a chair. Unfortunatly using a chair to try and end it with enemies active just gives you cannot use this during combat message.

## Game Version
1.7.36

## Language
English (EN)

## New Game
No

## Reproduction Steps
Technicly the answer is both yes and no, i have seen this happen plenty of times but it is random it just happens sometimes when using phased time.

**Comment by Deebz96** [comment]
This one was fixed officially.
