### ISSUE TITLE
Missing "door" to the Guardian, can't enter

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#568]
Occasionally there will be no way to click on the entrance to the Guardian. The only way to enter the ship is through fast travel. Trying to find the door with the console reveals that there is no door there at all.

---

## Details 
https://www.reddit.com/r/Starfield/comments/16lmok9/please_help_cant_enter_my_own_starborn_guardian/ See other people with this problem and a discussion

## Game Version
1.7.33

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
I don't know what causes it, but it breaks in the middle of a NG+ after working fine for a while

**Comment by Constellation-VASCO** [comment]
Have you got any other mods installed? I had this issue when I used a mod that sped up animations for ship takeoff.

**Comment by Constellation-VASCO** [comment]
Next time it happens I'll uninstall that mod and see if that's the problem

**Comment by Constellation-VASCO** [comment]
@Pickysaurus if you read the reddit thread I linked to some people with the problem are on Xbox so they're playing unmodded

**Comment by Deebz96** [comment]
Never been able to reproduce this issue. Will need more specific reproduction steps if possible. Closing this issue as dated.
