### ISSUE TITLE
Sun cannot be seen in the sky on planets (AMD Only)

### ISSUE THREAD

**Issue by Anp0w** [Starfield-Community-Patch/Starfield-Community-Patch#58]
### Details
Found a bug on planets, where if you have an AMD graphics card, it does not render the sun. However, all the shadows and lighting effects are still there

Here is a reddit post that goes into more detail: https://www.reddit.com/r/Starfield/comments/168r300/this_needs_to_be_fixed_amd_vs_nvidia_ultra_is_not/

### Version
1.7.23.0

### Reproduction Steps
Just use an AMD graphics card, (preferably) go to a barren planet, with no atmosphere to see space better. Land on the planet on the side facing the sun, look up, and you will see there is no sun in the sky

**Comment by Aurelianis** [comment]
Fixed in v1.7.33
"AMD (PC): Resolved an issue that caused star lens flares not to appear correctly AMD GPUs."
