### ISSUE TITLE
Skins Mods Disappearing From Suits and Weapons

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#585]
The Skins Mods disappear from your suits or weapons if you give it to a companion or store it in a container and change cells, that affects all skins mods(in game mods) and external skins mods as well, witch means this bug is deeply embed in Starsfield's code. 

---

## Details 
If you retrieve the suit or weapon from a companion or container and try to mod it again at the workbench, the skin option will have disappeared as well.

## Game Version
1.7.36.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Just tried it with multiple suits using multiple skins options, as well as with external mods skins and objects.
Also this bug was recreated by every player who add a skin mod to their suit or weapon and share it with a companion or store it in a container, the forums around internet a full of players reporting this issue.
Unfortunately I didn't see anyone reporting here, therefore I decide to do it to see if anyone can find a solution. No solution has been found around internet yet, even modders from Vortex who create mods with skins options are aware of this issue and warn the users that this may happens.

**Comment by Constellation-VASCO** [comment]
I have found that storing a weapon on a weapon rack, such as one in the Lodge basement, will prevent weapon skins from glitching. I have not yet tested mannequin displays to see if armor skins have a similar issue. This is a vanilla bug, and is happening even with the Premium Edition Constellation skin for the Equinox. I haven't tested the PE Constellation skin for the Constellation spacesuit items yet, but those armor skin changes might also glitch out if not in player inventory.

**Comment by Constellation-VASCO** [comment]
I have tested with all skins available in vanilla game and external mods, it does that to all of it.
Also you can't re-skin it in workbench, it mess up the item, the only way to re-skin it is using console commands.

But something strange happened, with the most recent version of the Community Patch mod, that bug now only happens when you close the game, if you change cells or reload a save, the skins won't disappear anymore, but if you go to the main screen or close the game, when you're back the skins are gone.

**Comment by Constellation-VASCO** [comment]
Having this problem as well. I also found that using console commands to remove then re-equip standalone modded apparel with external skins set as "default skin" in xedit will display the desired skin properly, but the same does not work for spacesuits; spacesuits will default to the original material file even if an external skin is set to "default".

**Comment by Deebz96** [comment]
Fixed officially.
