### ISSUE TITLE
EM Rifle Sets NPC's on Fire With Patch 0.0.3 Activ

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#589]
During the mission when Terrormorphs attack the station i went to the NAT station and they supplied an EM weapon to take down the NPC civilians without lethal. It was an Assassin's EM Advanced Orion. EM 13. Long Barrel, Medium Scope, Stealth Lasers, Electromagnet Beams. With the Starfield Community Patch 0.0.3 active it would set NPC's on fire like the laser perk can do. With the patch deactivated it worked as normal (No NPC's Took Fire Damage). NG+(35)

---

## Game Version
1.7.36.0

## Language
English (EN)

## New Game
No

## Reproduction Steps
Take elevator to NAT Station, Pick up supplied EM weapon and attack hostile NPC's. Have all perks in Laser.

**Comment by Constellation-VASCO** [comment]
Is this the ONLY mod you have loaded? It doesn't sound like something any of our changes could cause.

**Comment by Constellation-VASCO** [comment]
I noticed this happening after the community patch update that integrated a lot of the fixes from Skill Fixes mod. Laser weapons that have been converted to EM are still causing targets to burn. Max level in Laser and EM skills. It's as if converted laser-to-EM weapons are still causing part of the laser skill's bonus to be applied, even though that weapon is no longer supposed to be considered a laser.

**Comment by Pickysaurus** [comment]
This will be fixed in the next release
