### ISSUE TITLE
Restore conditions on Rank 4 Lasers

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#592]
The removed conditions on rank 4 Lasers causes a bug that lets EM weapons proc the Laser burn damage if the EM weapon is a modified laser weapon.

---

## Details 
In version 0.0.2, I removed seemingly redundant conditions on rank 4 Lasers. It turns out that if you convert a laser weapon to an EM weapon, it retains the keywords from both types, which allows EM weapons to proc the burn effect from rank 4 lasers due to the removed conditions. It might also be that these converted EM weapons benefit from the +30% damage increase from the Lasers skill as they retain the laser weapon keyword, although that remains to be tested. Regardless, since the developers seemingly chose not to add the same conditions to the damage increases, and they made the Incapacitation skill only grant +15% EM damage instead of +30%, one would assume that this interaction is intentional if present.

Suggestion: Restore the conditions on the perk.

## Game Version
1.7.36.0

## New Game
Yes

## Reproduction Steps
Acquire rank 4 Lasers. Convert a laser weapon to an EM weapon. See if it procs the burning effect.

**Comment by Constellation-VASCO** [comment]
To clarify, the conditions in question are the ones that prevented the burn effect from proccing with ballistic or EM weapons, it is not the ones for the particle weapon fix.

**Comment by Constellation-VASCO** [comment]
I'll whip up an ESM to verify the changes

**Comment by Pickysaurus** [comment]
[LaserRevert.zip](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/files/13318136/LaserRevert.zip)
Is this making the intended changes?
