### ISSUE TITLE
Lookup Failed

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#595]
After using mods for a while now, manually entering “sTestFile1=” “sTestFile2=” etc. into StarfieldCustom.ini, I got to 21 esm/esp entries and decided to switch to “Nukem's Plugins.txt enabler” after that I started getting LOOKUP FAILED for a few quest names and their quest steps, object names and their descriptions (picked up a magazine named LOOKUP FAILED, about LOOKUP FAILED)

---

## Details 
Tests
1.	Rolled back to a much earlier save – no change
2.	Disabled all mods including loose files in Data folders – worked 
3.	Systematically removed all mods, then loose files, what I found was a folder common\Starfield\Data\strings was full of files like StarfieldCommunityPatch_en.DLSTRINGS, StarfieldCommunityPatch_en.ILSTRINGS, StarfieldCommunityPatch_en.STRINGS also in 7 other languages. I dumped these in a sub folder ran the game and it seams to be working… so far. 

## Game Version
1.7.36.0

## Language
English (EN)

## New Game
No

## Reproduction Steps
Not sure how to recreate it. The strings folder had similar files for xatmosLegendaryDrip and xatmosOutpostTrader. Though I had never seen LOOKUP FAILED till now.

This info may help other people, it is not meant to be a complaint!

**Comment by Pickysaurus** [comment]
This is not a bug with the mod or the game. You installed it wrong. Do not use the sTestFile method as it is not supported
