### ISSUE TITLE
Setting course to piracy mission objective crash

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#599]
From the mission menu, attempting to set course to Crimson Fleet Piracy mission objectives with the description "Travel anywhere in the <X> System" will occasionally crash the game to desktop. Possibly related: attempting to set course to such a mission objective after completing several of them in a new game or a NG+ will generally not work.

---

## Game Version
1.7.36.0 + SCP 0.0.3

## New Game
Yes

## Reproduction Steps
Attempt to set course to mission objective from the mission menu

**Comment by Deebz96** [comment]
Unable to replicate. Without additional details, this one cannot be investigated.
