### ISSUE TITLE
Inventory Item Inspect Mouse Error

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#6]
When panning an object with a right click, as soon as you let go the mouse always 'teleports' to the left side of the screen. It does it during Item Inspect and during the primary Inventory screen.

---

## Details 
Inventory Inspect, Right-Click. Using 3440 x 1440 21:9 resolution.

## Game Version
1.7.23

## New Game
Yes

## Reproduction Steps
As soon as you finish Character Creation, just press I to go into your inventory and right-click in the open space to try and pan, let go and you will see it.

**Comment by Deebz96** [comment]
This issue is valid, however I suspect it would be an engine-level problem.

**Comment by Deebz96** [comment]
Out of scope due to engine-level fix.
