### ISSUE TITLE
"Tree Grows in New Atlantis" Sensor Marked Stolen

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#601]
One of the bio-sensors required by the quest "A Tree Grows in New Atlantis", specifically the one found in UC Distribution, is marked as stolen even when bought (and therefore obtained legally) from the vendor, Wen Tseng.

---

## Game Version
1.7.36.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
1) Start the quest "A Tree Grows in New Atlantis"
2) Talk to Jorden near the SSNN building
3) Talk to Wen Tseng to purchase the bio-sensor
4) Look at inventory and notice purchased bio-sensor marked as stolen

**Comment by Pickysaurus** [comment]
Quest ID 00270718

**Comment by Pickysaurus** [comment]
The Sensor is Alias_SensorCommercial identified by LOCREFTYPE `City_NA_Botany01_ComSensorLocRef [LCRT:0017AE58]`

The Objectreference for this item is [00325E5E] with owner `UC_NA_WenTseng "Wen Tseng" [NPC_:00012489]`.

Stages 65 and 66 of the quest need the fragment updating to add the following:

```
Alias_Sensor_Commercial.GetReference().SetActorOwner(NONE)
```
