### ISSUE TITLE
Due in Full mission points to incorrect planet.

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#605]
The Galbank Due in Full mission for "Kill delinquent Spacer orbiting Voll II Beta" points to Mars.

---

## Game Version
1.7.36.0

## Language
English (EN)

## New Game
No

## Reproduction Steps
Proceed through the Galbank collection missions.
Obtain the above mission.  Follow it to Mars and realise you're in the wrong place. :)

**Comment by Constellation-VASCO** [comment]
I noted this a while ago and posted it on Reddit, hoping it would be resolved.

I had forgotten about it until I ended up on a different mission near the planet and saw "Ship" on my map, orbiting Vol II Beta.  I'm now flying around the planet, trying to find the ship.  The mission may be completely broken.

**Comment by Constellation-VASCO** [comment]
Yup, the mission is indeed incorrect.

The Spacer ship IS in orbit around Mars.  I remember now; I found it when I was flying a lesser vessel, and you end up 6-7k KM away from the ship, so it takes a long time to reach.

**Comment by translucentfocus** [comment]
> Yup, the mission is indeed incorrect.
> 
> The Spacer ship IS in orbit around Mars. I remember now; I found it when I was flying a lesser vessel, and you end up 6-7k KM away from the ship, so it takes a long time to reach.

FYI, there are other bugs with this quest as outlined here: https://www.reddit.com/r/Starfield/comments/16gvump/due_in_full_bugged/

And, in my own game, I cannot progress the quest because the ship was destroyed before the quest started. But the quest remains...

**Comment by Constellation-VASCO** [comment]
I encountered the same bug in my game and struggled to reproduce it on a new save. I had started the first mission and killed the target, but never turned it in, theoretically killing the second target before it should have been available to me. The way this quest works is weird... It's not a series of quests, rather, it is one quest that is being reset to act like a new quest (kind of like a procedural/radiant quest, but too specific). I think because it is the same quest, and the alias is filled at quest start (entering New Atlantis location) it spawns the delinquent spacer ship in the orbit of a settled system. Somehow it also gets the planet name wrong because that too is picked when the quest first started and not when it was needed and it somehow caches the planet name but targets a different planet. This quest is spaghetti AF, and I attempted to fix it here: RAD05 Due In Full Quest Fix (https://www.nexusmods.com/starfield/mods/7030). I'd like a second opinion from the SFCP team before it is implemented. I did confirm that my changes definitely don't break the quest. At worst, they are irrelevant - at best, they should resolve the issue. The proposed fix will not solve the issue for existing games where the quest is started, which most likely have because it is triggered by Story Manager Event Node of entering New Atlantis location. Existing saves can use console if they get stuck.

Purely speculating... Again, issue didn't present itself if I created a new save and quickly went through the questline - so maybe something is reset over time/not staying persistent? I had theories on this with the issues I had in my Better Courier mod for SSE where over time script filled aliases would eventually somehow become lost/unassigned.

**Comment by Constellation-VASCO** [comment]
There are so many bugs with this quest
For me the first stage completed without me ever going to the star system it was in, then when it told me to do this step there was NO spacer at Ganymede at all and I had to advange the quest stage with a console command to proceed, yesh

**Comment by Constellation-VASCO** [comment]
Same here except the quest location is constantly moving away from me and can never be reached. Starts at a few thousand KM away then with the distance rapidly increasing every second.

I also had the first stage completed without ever finding the target so maybe that's related to the cause of the bug; i.e. perhaps the locations get corrupted somehow leading to duplicate markers.

**Comment by Deebz96** [comment]
This is reportedly fixed officially in 1.14.
