### ISSUE TITLE
NPC dialog hints at Activity to talk to sgt Yumi

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#612]
NPC dialog hints at Activity to talk to sgt Yumi over and over.

---

## Details 
NPC dialog hints at Activity to talk to sgt Yumi over and over.
Seemed to start for me after the Vanguard UC missions started calling me Captain (which is right before talking to the Council).

## Game Version
1.7.36.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Go through the UC quest to the Captain section (either having done all yumi's quests OR not done them (tested both ways)).

Captain seems to be given right when you talk to Hadrian? out side the MAST building?

random UC guards will then spout this breadcrumb activity over and over, with the same phrase

**Comment by inire** [comment]
#Mod_Priority,#Mod_Status,#Mod_Name,#Nexus_ID,#Mod_Nexus_URL,#Mod_Version
"0000","+","Starfield Script Extender (SFSE)",106,"https://www.nexusmods.com/starfield/mods/106","0.1.5.0"
"0001","+","HDTP - Actors - Critters and Crawlers 0.1.1",496,"https://www.nexusmods.com/starfield/mods/496","0.1.1.0"
"0002","+","HDTP - Actors - Humanoids 1.0.0-RC1",496,"https://www.nexusmods.com/starfield/mods/496","1.0.0.0-RC1"
"0003","+","HDTP - Planets - Moons and Atmospheres 1.0.0-RC2",496,"https://www.nexusmods.com/starfield/mods/496","1.0.0.0-RC2"
"0004","+","HDTP - Planets - Named 1.0.0-RC2",496,"https://www.nexusmods.com/starfield/mods/496","1.0.0.0-RC2"
"0005","+","HDTP - Weapons 1.0.0-RC1",496,"https://www.nexusmods.com/starfield/mods/496","1.0.0.0-RC1"
"0006","+","HDTP - Clothes - Military and Space 1.0.0-RC1",496,"https://www.nexusmods.com/starfield/mods/496","1.0.0.0-RC1"
"0007","+","HDTP - Clothes - NPCs 1.0.0-RC1",496,"https://www.nexusmods.com/starfield/mods/496","1.0.0.0-RC1"
"0008","+","Address Library for SFSE Plugins",3256,"https://www.nexusmods.com/starfield/mods/3256","3.0.0.0"
"0009","+","Community Patch",1,"https://www.nexusmods.com/starfield/mods/1","0.0.3.0"
"0010","+","SFSE ASI Loader",857,"https://www.nexusmods.com/starfield/mods/857","1.0.4.0"
"0011","+","Console Command Runner",2740,"https://www.nexusmods.com/starfield/mods/2740","1.3.0.0"
"0012","+","Plugins.txt Enabler",4157,"https://www.nexusmods.com/starfield/mods/4157","1.1.0.0"
"0013","+","Baka Achievement Enabler (SFSE)",658,"https://www.nexusmods.com/starfield/mods/658","2.0.0.0"
"0014","+","Enemy Friendly Fire (SFSE)",614,"https://www.nexusmods.com/starfield/mods/614","1.0.2.0"
"0015","+","Auto Unlock",5571,"https://www.nexusmods.com/starfield/mods/5571","1.1.2.0"
"0016","+","powerofthree's Tweaks SFSE",3621,"https://www.nexusmods.com/starfield/mods/3621","1.1.1.0"
"0017","+","Simple Offence Suppression SFSE",4456,"https://www.nexusmods.com/starfield/mods/4456","1.1.0.0"
"0018","+","Baka Quick Full Saves",1750,"https://www.nexusmods.com/starfield/mods/1750","2.0.0.0"
"0019","+","Baka Quit Game Fix",1662,"https://www.nexusmods.com/starfield/mods/1662","2.0.0.0"
"0020","+","Undelayed Menus",404,"https://www.nexusmods.com/starfield/mods/404","1.0.5.0"
"0021","+","StarUI Inventory",773,"https://www.nexusmods.com/starfield/mods/773","2.3.2.0"
"0022","+","Looter Shooter - Shooter Looter",5294,"https://www.nexusmods.com/starfield/mods/5294","7.0.0.0"
"0023","+","Cleanfield - A No-Intro Videos And Clean Menu Fix",88,"https://www.nexusmods.com/starfield/mods/88","1.7.2.0"
"0024","+","Neutral LUTs - No Color Filters",323,"https://www.nexusmods.com/starfield/mods/323","1.3.0.0"
"0025","+","StarUI HUD",3444,"https://www.nexusmods.com/starfield/mods/3444","1.2.0.0"
"0026","+","StarUI Workbench",4966,"https://www.nexusmods.com/starfield/mods/4966","1.1.0.0"
"0027","+","Item Sorter",5537,"https://www.nexusmods.com/starfield/mods/5537","2.2.0.0"
"0028","+","EXE - Effect Textures Enhanced",340,"https://www.nexusmods.com/starfield/mods/340","1.0.0.0"
"0029","+","Enhanced Blood Textures Starfield",326,"https://www.nexusmods.com/starfield/mods/326","0.2.0.0"
"0030","+","Enhanced Subtitles - Latest Version",1914,"https://www.nexusmods.com/starfield/mods/1914","1.2.0.0"
"0031","+","Enhanced Dialogue Interface",871,"https://www.nexusmods.com/starfield/mods/871","2.0.1.0"
"0032","+","Enhanced Presets - Official Collection",3450,"https://www.nexusmods.com/starfield/mods/3450","1.0.0.0"
"0033","+","VSD - Visible Skill Descriptions - 60 FPS",750,"https://www.nexusmods.com/starfield/mods/750","1.2.0.0b"
"0034","+","Better Visible Magazines",1054,"https://www.nexusmods.com/starfield/mods/1054","0.1.0.0"
"0035","+","Scanner Encumbrance Display With Time",963,"https://www.nexusmods.com/starfield/mods/963","2.0.0.0"
"0036","+","DiskCacheEnabler-SFSE",2245,"https://www.nexusmods.com/starfield/mods/2245","1.1.2.0"
"0037","+","Sprint Stuttering Fix",884,"https://www.nexusmods.com/starfield/mods/884","1.0.4.0"
"0038","+","Stellar Glass",2894,"https://www.nexusmods.com/starfield/mods/2894","1.0.0.0"
"0039","+","Zero Weight (SFSE or ASI Loader)",3475,"https://www.nexusmods.com/starfield/mods/3475","1.1.2.0"
"0040","+","Weapon Equip Speed and Microgun Instant Firing",3532,"https://www.nexusmods.com/starfield/mods/3532","1.0.2.0"
"0041","+","SSI-1_0 (SFSE-1_7_36)",5562,"https://www.nexusmods.com/starfield/mods/5562","1.0.0.0"
"0042","+","Luma - Native HDR",4821,"https://www.nexusmods.com/starfield/mods/4821","1.0.1.0"
"0043","+","Ship Encounter Script Fixes",5668,"https://www.nexusmods.com/starfield/mods/5668","0.1.1.0"
"0044","+","Stealthing on Scow - Stealth option for No Sudden Moves",4556,"https://www.nexusmods.com/starfield/mods/4556","0.1.1.0"
"0045","+","Stroud-Eklund Acculander Thruster Fix",4630,"https://www.nexusmods.com/starfield/mods/4630","0.1.1.0"
"0046","+","Neon Entrance Bounty Dialog Fix",4763,"https://www.nexusmods.com/starfield/mods/4763","0.1.1.0"
"0047","+","Richer Vendors - 10x merchant gold and 1 day restock",5624,"https://www.nexusmods.com/starfield/mods/5624","0.1.0.0"
"0048","+","StarUI Outpost",5766,"https://www.nexusmods.com/starfield/mods/5766","1.1.0.0"
"0049","+","Textile Moire Fix",1743,"https://www.nexusmods.com/starfield/mods/1743","1.1.0.0"
"0050","-","Starfield Frame Generation - Replacing FSR2 with DLSS-G",761,"https://www.nexusmods.com/starfield/mods/761","1.3.0.0"
"0051","+","Compact Mission UI",682,"https://www.nexusmods.com/starfield/mods/682","1.7.0.0"
"0052","-","Compact Ship Builder UI",1170,"https://www.nexusmods.com/starfield/mods/1170","1.5.0.0"
"0053","+","StarUI Ship Builder",6402,"https://www.nexusmods.com/starfield/mods/6402","1.1.0.0"
"0054","+","Less Spongy Enemies",344,"https://www.nexusmods.com/starfield/mods/344","1.0.0.0"
"0055","+","SKK Craftable Ship Tools",5466,"https://www.nexusmods.com/starfield/mods/5466","3.0.0.0"
"0056","+","Ship Combat Overhaul - Modular ESMs",5648,"https://www.nexusmods.com/starfield/mods/5648","1.32.0.0"
"0057","+","SKK Universal Stash (unlimited storage)",5670,"https://www.nexusmods.com/starfield/mods/5670","5.0.0.0"
"0058","+","More Gooder Ship Weapons",5868,"https://www.nexusmods.com/starfield/mods/5868","0.2.0.0"
"0059","+","Ship Builder Retexture - Weapon Modules - Black",6020,"https://www.nexusmods.com/starfield/mods/6020","1.2.0.0"
"0060","+","Lively's Enhanced Skills",5928,"https://www.nexusmods.com/starfield/mods/5928","1.1.0.0"
"0061","+","No Negative Affinity",5797,"https://www.nexusmods.com/starfield/mods/5797","1.1.0.0"
"0062","+","Legendary Module Recycler",6074,"https://www.nexusmods.com/starfield/mods/6074","1.20.0.0"
"0063","+","Lively's Leveled Mannequins Bug Fix",6237,"https://www.nexusmods.com/starfield/mods/6237","1.0.0.0"
"0064","+","Better Scanner",4212,"https://www.nexusmods.com/starfield/mods/4212","1.2.0.0"
"0065","+","ClickLight - Highlight Objects Clicked in Console",6040,"https://www.nexusmods.com/starfield/mods/6040","1.0.0.0"
"0066","+","Streamline Native (Frame Gen - DLSS - Reflex Integration)",2751,"https://www.nexusmods.com/starfield/mods/2751","1.7.0.0"
"0067","+","Shut Up Everyone",6401,"https://www.nexusmods.com/starfield/mods/6401","1.0.7.0"
"0068","+","Lots More Neuroamps",6417,"https://www.nexusmods.com/starfield/mods/6417","1.0.0.0"
"0069","+","Smart Aiming SFSE - Third to First Person",1302,"https://www.nexusmods.com/starfield/mods/1302","1.0.4.0"
"0070","-","CRT - SKINS",5807,"https://www.nexusmods.com/starfield/mods/5807","f1.01"
"0071","+","FOG REMOVER BY URANIA",1607,"https://www.nexusmods.com/starfield/mods/1607","3.0.0.0"
"0072","+","TN's Ship Modifications All in One",6376,"https://www.nexusmods.com/starfield/mods/6376","1.0.0.0"
"0073","+","Swiftly Order Squad - Multiple Followers - Group Commands",6439,"https://www.nexusmods.com/starfield/mods/6439","0.1.3.0"
"0074","+","VBB (Voluptuous Body for Beauties) - New Proportions for Female Characters",3554,"https://www.nexusmods.com/starfield/mods/3554","1.2.0.0"
"0075","+","CRT - BODY MESH",6519,"https://www.nexusmods.com/starfield/mods/6519","1.1.0.0"
"0076","+","Ship Power Allocation Fix - Revert Unwanted Power Changes",6707,"https://www.nexusmods.com/starfield/mods/6707","0.1.2.0"
"0077","+","Weapon Swap Stuttering Fix",2830,"https://www.nexusmods.com/starfield/mods/2830","1.1.2.0"
"0078","+","Faster Furniture Animations",2645,"https://www.nexusmods.com/starfield/mods/2645","1.0.1.0"
"0079","+","Customizable Climbing Animations",2524,"https://www.nexusmods.com/starfield/mods/2524","1.0.0.0"
"0080","+","Faster Airlock and Hatch Animations",2489,"https://www.nexusmods.com/starfield/mods/2489","1.1.1.0"
"0081","+","Faster Ship Animations",2815,"https://www.nexusmods.com/starfield/mods/2815","1.1.0.0"
"0082","+","Show Star Names",5188,"https://www.nexusmods.com/starfield/mods/5188","1.3.0.0"
"0083","-","NSFW Ads and Posters",743,"https://www.nexusmods.com/starfield/mods/743","0.8.0.0"
"0084","-","CRT - LoadingScreens",6062,"https://www.nexusmods.com/starfield/mods/6062","1.0.0.0"

**Comment by inire** [comment]
this bug also existed on a vanilla save as well.

**Comment by Constellation-VASCO** [comment]
I think what inire is saying is that after you've finishied Sgt Yumi's 3 questlines (Keeping the Peace, A Break at Dawn, and Search and Seizure), guards will still comment that you should go see him regarding the next job, despite having no more work.

**Comment by Aurelianis** [comment]
Same as https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/issues/887 and fix was added to SFCP
