### ISSUE TITLE
Elevator bug 

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#613]
Jemison spaceport, elevator to Waterfall (etc) stops working after UC Vanguard questline.

---

## Details 
After the spaceport is destroyed and rebuilt, whilst the elevator is still there, it seems the game forgets to put the functions of it back into place resulting in a useless elevator (which can affect several quests). 

## Game Version
1.7.36.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
As per previous note.

**Comment by Pickysaurus** [comment]
Duplicate of https://www.starfieldpatch.dev/issues/343
