### ISSUE TITLE
Maheo I - Lopez's Farm

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#62]
At Lopez's farm the doors to his habitat are floating above it, it was fine before I started the quest not that I have finished destroying spacer ships and came here as part of the quest the doors are bugged.

---

## Game Version
1.7.32.0

## New Game
No

## Reproduction Steps
It only happened once I had go to a specific part in the questline where I have to return to Lopez's Farm. Perhaps if others do this they will get the same thing.

**Comment by Deebz96** [comment]
Floating airlock doors were officially fixed by Bethesda.
