### ISSUE TITLE
Stroud-Eckland mess hall cook station dumps items.

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#623]
Now that I finally have the S-E mess hall instead of the Deimos I used to have, I'm having an issue with the cooking station dumping crafted items out in front of itself (through the wall).  I have to go and pick them up.

---

## Game Version
1.7.36.0

## Language
English (EN)

## New Game
No

## Reproduction Steps
Install Stroud-Eckland mess hall.
Use the cooking station.
Observe where crafted items appear.  It should be in the inventory, of course.

**Comment by Constellation-VASCO** [comment]
The galley station works as it should.  Items go into the inventory.

**Comment by Pickysaurus** [comment]
Duplicate of #526
