### ISSUE TITLE
LOOKUP FAILED!

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#624]
It says LOOKUP FAILED! as name for the Loose Ends quest. Since I updated to latest nightly build. Allready tried removing strings folder. Going back to an older version of the patch and using commands to reset the quest. The words LOOKUP FAILED now show up everywhere, even location names, the quest name for loose ends.

---

## Details 
00238837 quest id

## Game Version
1.7.36.0

## Language
English (EN)

## New Game
No

## Reproduction Steps
Install the community patch 1.03 play the game, go to neon security office jail, talk to nashar to start quest. Update the patch to 1.04, and now the quest is bugged, and LOOKUP FAILED shows up in random places everywhere now.

**Comment by Constellation-VASCO** [comment]
Solved by downgrading to nightly of 10 november with ba2 file and .ini file of the 1.02 release of the community patch

**Comment by Constellation-VASCO** [comment]
Would like to upgrade in the future, please advise on how to fix it.

**Comment by Constellation-VASCO** [comment]
Solved by removing strings folder from root game directory please close issue

**Comment by nerwus3456** [comment]
And that's why we check the data folder for loose strings people
