### ISSUE TITLE
Inconsistency in gas/liquid collection

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#629]
Whith scanner open you can use the laser cutter and loot chests or corpes and gather plants, but you can't gather gas/liquid from their sources.

---

## Game Version
1.7.36.0

## Language
Spanish (ES)

## New Game
Yes

## Reproduction Steps
Just try to gather liquid/gas with scanner open

**Comment by Deebz96** [comment]
This one was fixed officially.
