### ISSUE TITLE
Coe's Estate has gravity of 1.0 instead of 1.51

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#63]
Coe's Estate in Akila has gravity of 1.0 instead of 1.51

---

## Game Version
1.7.23.0

## New Game
No

## Reproduction Steps
simply enter the Coe Estate interior

`coc CityAkilaCityCoeEstate` to enter directly.

**Comment by Constellation-VASCO** [comment]
> For this issue, I think that, technically, it should be an easy fix to make - if you add Unknown Flag 17 to a cell I believe that's responsible for setting the gravity to be the same as the planet, though I can't guarantee it doesn't do anything else. Only thing is that when I went to look it up a few weeks ago I found it wasn't just the Coe Estate with this problem - it's almost every single interior in each main city location - I think the only one I can recall that's different is Cydonia. You could even perhaps argue that the interiors have some sort of artificial gravity generator like your ship does and that it's intentional to have it be the same as Earth gravity.

- Krevil

**Comment by Pickysaurus** [comment]
Handled in #363
