### ISSUE TITLE
Blast shield at Nishina disappears

### ISSUE THREAD

**Issue by Aurelianis** [Starfield-Community-Patch/Starfield-Community-Patch#631]
One of the blast shields on the landing pad disappears when it is being lowered.

### Details

When first arriving:
![image](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/assets/109992824/5e4dd117-ffab-4e4d-98aa-3371db39296d)

After the animation for lowering the blast shield starts:
![image](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/assets/109992824/232adbd3-08f7-4c40-bacc-2f5535ee5acd)

It's just this one that is affected. The others are fine.

### Game Version

1.7.36.0

### Language

English (EN)

### Have you recreated this issue on a new game?

Yes, I can recreate this issue.

### Reproduction Steps

Land at Nishina on Freya III (part of the Entangled mission).

**Comment by translucentfocus** [comment]
I too was able to reproduce this bug.

![Image](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/assets/26986716/48864bdb-caab-40db-83b0-36e7623e1b1c)

**Comment by Aurelianis** [comment]
This was a bit more complicated that I thought it would be. 

MQ207CLandingMarkerRef [REFR:0023B8A5] has a linked Ref to [REFR:0023B8A6] (This is the blast shield that is disappearing when lowering).

No matter what blast shield I linked here, the linked shield would disappear. If there was none linked, the shield animations did not work.

I looked at other landing markers and blast shields and found that they were using an enable marker with a keyword; LinkedRef_LandingPadShield_EnableMarker [KYWD:0028B2A0]

I created a new Enable Marker, and linked it using this keyword on 0023B8A5 in addition to the already linked blast shield.

This kept the shield from disappearing, but now many of the shields were not raised when landing (the were missing linked ref). I went through all of them and relinked them in order. The red lines are the links that were in vanilla, the yellow is what they are now.

0023B8A6 links to 0023B8A7 which means when 0023B8A6 starts to move, then 0023B8A7 will begin it's animation.

0023B8AE is the last in the chain so is not linked to anything.
![NishinaBlastShields](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/assets/109992824/550abca5-edf2-4552-861d-00415ae94643)

Fix attached
[NishinaBlastShieldFix.zip](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/files/14408138/NishinaBlastShieldFix.zip)

**Comment by Aurelianis** [comment]
Updated the ESM attached so that 0023B8A5 has the changes previously made by SFCP (removed incorrect properties CloseSoundMarker and OpenSoundMarker).
[NishinaBlastShieldFix.zip](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/files/14435017/NishinaBlastShieldFix.zip)

**Comment by Constellation-VASCO** [comment]
Some of these edits were ITMs, so I've excluded them.
