### ISSUE TITLE
Unity has Constellation-- even when they all died

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#634]
The Unity ending ALWAYS shows the Constellation furthering space exploration, even in NG+ variations where they were brutally murdered or retired.

---

## Details 
MQ ending

## Game Version
1.7.36.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Play any NG+ where Unity is dead, reach the Unity, have Star-self tell you about how Consellation members that remain will further exploration.

**Comment by Constellation-VASCO** [comment]
With every variant universe, c9nstellation doesn't exist in its normal state,  but when entering the unity you still see the same vision of them.

Based on this guide: https://steamcommunity.com/sharedfiles/filedetails/?id=3034877981

The one it shouldn't show up in are:

**Definitely not because they were murdered:**

set 1801B9 to 0 [Everyone is dead in constellation... except you, and by that I mean the "you" from this universe]
set 1801B9 to 5 [Hunter has killed everyone]
set 1801B9 to 7 [A NG10+ version of your character has already killed constellation and is waiting inside. you have to fight your Variant]

**And I'm not sure if Constellation gathers research to share:**
set 1801B9 to 8 [The children universe]
set 1801B9 to 9 [Constellation has retired]
set 1801B9 to 6 [Cora Coe is a starborn]
set 1801B9 to 2 [Dopplegangers (yes plural) universe]

**Comment by Aurelianis** [comment]
Duplicate: https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/issues/639

**Comment by Aurelianis** [comment]
Closing as duplicate. Also this was fixed in SFCP
