### ISSUE TITLE
Game crashes when landing in New Atlantis

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#635]
I see a lot of fixes but why nobody fixes the game crash when trying to land in New Atlantis. It is great to have a lot of fixes done, yes, but if you can not play, what is the purpose of so many fixes? There is a lot people with this issue but nobody fixes it, neither Bethesda. Why nobody has fixes yet? Thanks a lot for fixing textures, sound, dialogues but I think the fixes that should be done are those that allows players to play the game. Thanks a lot for your effort. Regards.

---

## Details 
I see a lot of fixes but why nobody fixes the game crash when trying to land in New Atlantis. It is great to have a lot of fixes done, yes, but if you can not play, what is the purpose of so many fixes? There is a lot people with this issue but nobody fixes it, neither Bethesda. Why nobody has fixes yet? Thanks a lot for fixing textures, sound, dialogues but I think the fixes that should be done are those that allows players to play the game. 

I have a i7 with an NVIDIA RTX 3050 4Gb, with 16 Gb of system memory but this error happens playing the game in cloud and also in the Xbox console.

Thanks a lot for your effort. Regards.

## Game Version
1.7.36.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Just play to the game and in some points, once you change of ship, I remember that this started to happen when I changed to an Ecliptic ship, the game will crash once you try landing in New Atlantis, no matter playing form PC, console o rin cloud.

**Comment by Pickysaurus** [comment]
This seems like it's very specific to your game (which would tell you why nobody has fixed it yet).

**Comment by Constellation-VASCO** [comment]
I think is not specific to my game, it is happening to a lot of people, just look at it in internet, there is a lot of people with this issue. And it is not something about my PC, happens also playing in cloud or console. Could be something about my saving game data? That could be happening to the other people?
