### ISSUE TITLE
Quest: Rough Landings (script logic issue)

### ISSUE THREAD

**Issue by translucentfocus** [Starfield-Community-Patch/Starfield-Community-Patch#636]
Update: Bethesda has fixed this issue as of the January 30th path: https://help.bethesda.net/#en/answer/62604

Update: Bethesda is also [tracking this issue](https://help.bethesda.net/#en/answer/62604)

The **"Rough Landings"** quest encounters a bug during the "Meet Up with Milena Axelrod" portion of the quest.
After talking to Marko Jansen, the quest script sometimes fails to spawn Milena (and her ship) and halts the quest script. A quest marker will show on the map, but jumping to the planet indicated by the quest marker triggers nothing. No Crimson Fleet, no Milena.

Redditors have [explained the issue](https://www.reddit.com/r/Starfield/comments/169qhad/comment/k13nmco/) also.

### Details

**Quest Name** [Rough Landings](https://starfieldwiki.net/wiki/Starfield:Rough_Landings)
**Quest ID:** 001A8B64
Error occurs when spawning Milena **Stage:** 100

✅ Milena's spawn is randomly selected amongst the celestials in the Cheyenne system.
❌ The quest script does not check the built-in conditions (there cannot be any FC or UC vessels where she spawns) of her spawn until **_after_** it selects a spawn point.
❌ What occurs **_infrequently_** is that the quest script selects a planet in the Cheyenne system like Montara Luna (that has a permanent security patrol) as the spawn for Milena, realizes that she cannot spawn (due to the permanent security patrol), and proceeds to run the same loop repeatedly **_without changing where to spawn_** until the program enters a failsafe that auto marks the quest as stopped so that it is not running in the background permanently.
**Note:** This quest generally works properly, because the script chooses a planet that does not have UC or FC vessels

### Game Version

1.7.36.0
I did not see this bug fixed in the [latest beta patch](https://bethesda.net/en/game/starfield/article/6BV2LYrp98qW4F15zfejEA/starfield-beta-update-1-8-83-notes-november-8-2023)
### Language

English (EN)

### Have you recreated this issue on a new game?

Yes, I can recreate this issue.

### Reproduction Steps

1. `StartQuest 001A8B64 1`
2. `SetStage 001A8B64 100`
3. Set Rough Landings as Active Quest from the Missions screen
4. A quest marker will appear at the planet Milena is supposed to have spawned at
5. Jump to Milena
6. If Crimson Raiders and Milena are not there, you've successfully reproduced the bug! 👏
7. If Milena _is_ there and everything seems to work fine, do the following to reset the quest:
8. `CompleteQuest 001A8B64`
9. `ResetQuest 001A8B64`
10. Begin at top of Reproduction Steps

Additional Note: The Stage 200 Note shown in xEdit below is misleading. Milena can spawn anywhere in the Cheyenne System, not just at Agamon C
![image](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/assets/26986716/d2192e39-0204-4989-aa14-1d62ee2639a3)

**Note:** It is possible for this quest to work properly, if the script chooses a planet that does not have UC or FC vessels

**Comment by Constellation-VASCO** [comment]
`Rough Landings [001A8B64]` Starts `City_Akila_Jansen_MilenaSpace[001A8AA2]` at stage 200.

I don't see any aliases that would fail to fill there. 
.

**Comment by translucentfocus** [comment]
> `Rough Landings [001A8B64]` Starts `City_Akila_Jansen_MilenaSpace[001A8AA2]` at stage 200.
> 
> I don't see any aliases that would fail to fill there...
My apologies, my reproduction steps are incorrect. I'll update them once I get it sorted out.

**Comment by translucentfocus** [comment]
This is only my second day doing any of this, so apologies if my information isn't completely clear.
I think I've narrowed it down. Here's what I **think** happens.

1. On quest start, Alias `004 AgamonCLocation` is configured as the location that Milena's ship, Dalliance, will eventually spawn/move to.
⚠️ Despite the name, it is a _random_  orbit inside the Cheyenne system (it doesn't even have to be the orbit of one of the  Agamon planets)
![image](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/assets/26986716/3d476605-e774-46f7-a44c-ba9c96f24f95)
3. There is only one condition for selecting the location of the Alias `AgamonCLocation` which is that it is a Major Orbital
![image](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/assets/26986716/54127cac-6775-46e7-a250-574e28de1497)

Also, I believe this is the script where the quest actually stops functioning.
```
qf_city_akila_jansen_milenas_001a8b65.pex

Function Fragment_Stage_0000_Item_00()
  Alias_MilenaShip.GetRef().MoveTo(Alias_DallianceMapMarker.GetRef(), 0.0, 0.0, 0.0, True, False) ; #DEBUG_LINE_NO:8
EndFunction
```
Because Alias ```DallianceMapMarker``` is based off of Alias ```AgamonCLocation``` and if it's a place with UC or FS vessels, than it can't continue the quest.

Recommendation: I think if a condition is added to check if Alias `AgamonCLocation` has any UC or FS ships there that it might fix it.

Again, I'm brand new to this, so I might be reading this all wrong.

**Comment by translucentfocus** [comment]
Update: Bethesda has fixed this issue as of the January 30th path: https://help.bethesda.net/#en/answer/62604
