### ISSUE TITLE
Quest: Rough Landings (typo)

### ISSUE THREAD

**Issue by translucentfocus** [Starfield-Community-Patch/Starfield-Community-Patch#637]
### There is no Akila System. The underlined text should say Cheyenne System.
![Rough Landings Typo](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/assets/26986716/37346354-ca24-4b18-be45-c0bdf8850214)

### Details

There is no Akila System. Bethesda meant the "Cheyenne System".
Recommend looking for any other places where "Akila System" is written as it is likely they should also be "Cheyenne System"

### Game Version

1.7.36.0
I did not see this bug fixed in the [latest beta patch](https://bethesda.net/en/game/starfield/article/6BV2LYrp98qW4F15zfejEA/starfield-beta-update-1-8-83-notes-november-8-2023)
### Language

English (EN)

### Have you recreated this issue on a new game?

Yes, I can recreate this issue.

### Reproduction Steps

Quest Name [Rough Landings](https://starfieldwiki.net/wiki/Starfield:Rough_Landings)
Quest ID: 001A8B64

1. Restart the quest at Stage 200
2. At this point, the quest will show the text with the typo as depicted in the screenshot

**Comment by Pickysaurus** [comment]
This is the only reference to "Akila System" and is definitely an error.
