### ISSUE TITLE
NG+ variant inconsistencies

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#639]
If you ng+ and get any of the variant universes where Constellation is disbanded, whether cora kills everyone, andreja kills everyone, walter is the only one, or Sarah is a plant and Constellation is gone, when you enter the Unity, it will still show the vision of Constellation members eventually sharing the info with the settler systems.

It doesn't make any sense, because in those universes, Constellation doesn't exist anymore. It's a major inconsistency.

---

## Details 
It's related to the specific ng+ variants where congellations is disbanded.

## Game Version
1.7.36.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Have to enter ng+ unity and get a variant universe, one of the ones where Constellation no longer exists. Inve you gather all the artifacts and enter the u ity again, it will show to generic Constellation vision about what happens to your universe, even though it doesn't make sense stoywise

**Comment by Aurelianis** [comment]
I have a fix for this. Just need to do some testing and send it off to the team.

**Comment by Aurelianis** [comment]
[mq305script.zip](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/files/14406279/mq305script.zip)
Fix attached.
