### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by erisangt** [Starfield-Community-Patch/Starfield-Community-Patch#64]
I would like to report that I and several people are crashing, in search of solutions I did several techniques to improve performance and nothing... When trying to see the average FPS I used OCam which is a video recorder that measures FPS together, but at the same time opening it next to the game appeared saying that I was trying to make a reverse engine, I believe that because it was in the background it opened this warning, which made me notice that the large drops in FPS, crashes and other problems may be due to some kind of anti-cheater reading or something like that.
Maybe removing this reading can solve a good part of these problems.

**Comment by Pickysaurus** [comment]
I'm afraid this isn't specific enough to do anything with.
