### ISSUE TITLE
[Starborn] choice in Breach of Contract

### ISSUE THREAD

**Issue by NullArgumentException** [Starfield-Community-Patch/Starfield-Community-Patch#649]
There is a [Starborn] choice in Barrett's mission "Breach of Contract", that shouldn't be there if the mission hasn't been done before.

In NG+, after coming back from the Hephaestus mine and talking to the lawyer (Ellie), there is a [Starborn] choice to skip searching for Helgi and going straight to Lizzy.

In other missions you're only given [Starborn] choices after you've done them at least once before. Not here though.
You shouldn't be given the choice if you've never completed this mission before.

![Screenshot 2023-11-19 134853](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/assets/145229712/9be7b796-c910-4eb5-8636-c002d0728a06)

### Details

ID: COM_Quest_Barrett_Q01

Quest stage: 6000

### Game Version

1.7.36.0

### Language

English (EN)

### Have you recreated this issue on a new game?

Yes, I can recreate this issue.

### Reproduction Steps

- Don't do Breach of Contract before going into NG+
- restart the game in NG+
- do Breach of Contract

**Comment by Constellation-VASCO** [comment]
I experienced this bug as well. Had never pushed Barret's relationship passed getting the Starborn power-- first time ever and had this dialogue option.

**Comment by TESWartortle** [comment]
[Issue649.zip](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/files/13813066/Issue649.zip)
Untested but conditions now match other Starborn dialogue from that mission, so should be good to go.
Compare to 00336C1C, 002E28D4
