### ISSUE TITLE
Sunless Space freezes everything-- except turrets

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#653]
Sunless space freezes all enemies and makes them stop attacking, but not turrets. Probably due to them being stationary and not staggerable rather than a genuine gameplay/balance decision.

---

## Game Version
1.7.36.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Use sunless space on a turret, nothing happens.

**Comment by Deebz96** [comment]
This falls a bit too much into a balance change, in my opinion.
