### ISSUE TITLE
Ghost ship bug.

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#655]
At some point in the main quest, landed ships and ships we fight in space no longer have crew.

This means that when we approach a landed ship, it won't have anybody disembarking.  Sometimes we can still access the vessel (such as with the Starborn ships) but nobody will be aboard.

---

## Details 
This is due to two placeholder quests becoming stuck.  Some say it is triggered by us reaching a certain point in the main story (but that point is debated).  Others say it happens if we leave a planet after they have landed and we don't engage them.

The fix is as follows:

The two quest IDs are - 
ID 2C0FD9 and 98B4E

We first need to check the state of the quests - 

sqv 2C0FD9

Enabled: YES

State: RUNNING

Current Stage: 10

Priority: 90

AND

sqv 98B4E

Enabled: NO

State: Stopped

Current Stage: 100

Priority: 90
If one of these is running it must be stopped with the resetquest command, e.g.  "resetquest 2C0FD9".

I did find that I needed to do this a second time so it may need to happen after each new engagement, hence the submission to your wonderful patch. :)

## Game Version
1.7.36.0

## New Game
No

## Reproduction Steps
As above.

**Comment by Constellation-VASCO** [comment]
I've been that problem for a long time. Then I just did the reset quest of 2c0fd9 and worked! I will test further more and post the results in here. Thank you very much!

**Comment by Constellation-VASCO** [comment]
One more update on this issue, after the recent update, the problem still continues to happen. Like the post said, after each encounter it is needed to do the reset quest again.

**Comment by Deebz96** [comment]
This one was fixed officially.
