### ISSUE TITLE
Issue in SFCP component fix

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#657]
I routinely check the changes of the SFCP via SFEdit for conflicts with other mods. Is it possible you made a mistake on the fix for "Red Harvest Double Malt Whiskey" [ALCH:0003614B] - instead of ResGastroLiquor "Liquor" [IRES:0029B02D] like for the Single Malt, SFEdit shows me ResGastroCoffee "Coffee" [IRES:0029B017] as the component. However, I don't think Double-Malt is made from Coffee :-).

---

## Details 
Concerns the fix of SFCP to "Red Harvest Double Malt Whiskey" [ALCH:0003614B]
Patched component in 0.0.4 is "Coffee" [IRES:0029B017]. 
However, it should be "Liquor" [IRES:0029B02D] like for the Single Malt.

## Game Version
1.7.36.0

## Language
English (EN)

## New Game
No

## Reproduction Steps
Run SFEdit and open the respective component in SFCP 0.0.4 and inspect it.

**Comment by Constellation-VASCO** [comment]
Can confirm the issue in 0.0.4. The plugin I posted to Nexus in the original bug report still has the correct components set.

**Comment by TESWartortle** [comment]
[Issue 657.zip](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/files/13697857/Issue.657.zip)

Still present in 0.0.6. One month after being reported. Smh. Here's the fix.
