### ISSUE TITLE
Eyewitness - EM Weapon doesn't spawn

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#659]
When leaving the elevator at the NAT station below MAST, after the initial attack, the EM weapon that is supposed to be on the ground does not spawn, thus forcing the player to use lethal force if they want to continue the quest (unless they already own an EM weapon). 

---

## Details 
Quest ID:	UC04
Relevant Stages: 575 580 581

## Game Version
1.7.36.0

## Language
English (EN)

## New Game
No

## Reproduction Steps
It happens on one of my saves, it's a known bug that has been reported by others. Unsure of exact steps.

**Comment by Deebz96** [comment]
Never experienced this one myself. Possibly fixed officially. Closing as stale.
