### ISSUE TITLE
Legrande's Liquors Typo

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#661]
Legrande's Liquors is misspelled 'Legrande's Liqours' in English subtitles.

---

## Details 
When the audio ad for Blend is playing in front of Legrande's Liquors in the Neon Core, the above typo is present in the subtitles.

## Game Version
1.8.86.0

## Language
English (EN)

## New Game
No

## Reproduction Steps
Turn on subtitles and stand in front of Legrande's in Neon to reproduce.

**Comment by TESWartortle** [comment]
Confirmed broken.

Edits NPC_ 0030D630, FULL - Name to correct spelling.

[Issue 661.zip](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/files/13693985/Issue.661.zip)
