### ISSUE TITLE
Multiple Weapons Have The Wrong Keyword

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#662]
Multiple weapons have the WeaponTypeAutomatic keyword when they shouldn't, causing Marksmanship  to not correctly identify them as non-automatic when they are.

---

## Details 
WeaponTypeAutomatic should be given by the Automatic Receiver for the weapons that have it. Kodama, Grendel, Maelstrom, and Shotty have the WeaponTypeKeyword as part of their base Weapon - keywords ref which means it won't be removed when they don't have the Automatic Receiver. WeaponTypeAutomatic is checked by the Marksmanship skill to find out whether a used weapon is automatic or not, causing the effected weapons to never be effected by the skill, no matter what receiver they have.

## Game Version
1.7.36.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Pick up any of the effected weapons, then take the Marksmanship perk and shoot enemies to check the critical hit chance.

**Comment by Deebz96** [comment]
This will be fixed in 0.1.8.
