### ISSUE TITLE
DLSS "generic_app"

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#663]
I don't know exactly what section to report this, but I think it needs to be fixed for somehow. As before, using DLSS Mod, the app's name never was Starfield, but "generic_app", "sample_app" or "custom_engine_generic". It think that if DLSS if working perfectly in native settings, it could be named "Starfield". I don't know if it's something to Bethesda or NVIDIA fix, I'm only reporting.

---

## Game Version
1.8.86

## Language
Brazilian Portuguese (PTBR)

## New Game
Yes

## Reproduction Steps
Turn on DLSS Hud

**Comment by Pickysaurus** [comment]
This is out of scope for our patch.
