### ISSUE TITLE
LOOKUP FAILED    

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#667]
the main quest entry's are all showing LOOKUP FAILED following the patch update  

---

## Details 
LOOKUP FAILED following the patch update  if patch is removed then the UI shows the correct information  

## Game Version
1.8.86

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
patch installed

**Comment by Pickysaurus** [comment]
This is 100% caused by you having a "Strings" folder in your data folder with outdated copies of the StarfieldCommunityPatch strings. Delete these to fix the issue.
