### ISSUE TITLE
Fungal Growth is sometimes called Fungal Grotto

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#674]
The trait at locations named Fungal Growths consists of towering fungal growths, although they are named Fungal Grotto in the game. This is likely a mistake, as they are clearly growths and not grottos.

---

## Details 
FF462B3C

## Game Version
1.7.36.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Go to Zelazny III in the Zelazny system, land in the Volcanic biome, find a Fungal Growth location and observe how the growths are refered to as grottos.

**Comment by Pickysaurus** [comment]
I don't think this is a bug. The POI name tends to slightly differ from the trait name sometimes.

**Comment by Constellation-VASCO** [comment]
Sometimes, sure. And to change anything without more confirmation would be premature. It's just that the object in question is so obviously a growth, a grotto would be its exact opposite.
