### ISSUE TITLE
Vice Grips are actually Adjustable Pliars

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#68]
Model for "Vice Grips" are not Vice Grips but a Channel Lock Wrench

---

## Details 
Reported from Reddit: the "Vice Grip" item in game is not infact a "Vice Grip" but a pair of "Channellock" adjustable pliars. ChannelLock is a US company, so probably renaming them to "Adjustable Pliars" is the better route.

## Game Version
1.7.23.0

## New Game
Yes

## Reproduction Steps
`player.additem 20b97d` go to your inventory and stare at this horror

![Screenshot 2023-09-06 090015](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/assets/654621/371d9834-6791-423a-84a2-daba7331e2e0)

**Comment by ArtaiosGreybark** [comment]
Channellock is an American brand though. The general term is tongue-and-groove pliers, so maybe just call them "Pliers" or "Adjustable pliers". Please don't regionalize this.

**Comment by halgari** [comment]
agreed, "Adjustable Pliers" is probably the better term

**Comment by ArtaiosGreybark** [comment]
> agreed, "Adjustable Pliers" is probably the better term

Awesome! You just made a small type in the title (Pliars) :)

**Comment by Pickysaurus** [comment]
This is a mistake, but I wonder if it's out of scope of the patch to fix. Bethesda may have named them this way on purpose?

**Comment by Constellation-VASCO** [comment]
Words change meaning over time. 300 years in the future that tool will be called "vice grip".

**Comment by Deebz96** [comment]
Going to count this one as out of scope, even though I personally agree that this is the wrong name for this item.
