### ISSUE TITLE
Typo in Ambassador Bal'Mor's personal log

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#684]
There is a typo in "Log 03: A Visitor" in the Personal Computer in the basement of the House Va'ruun Embassy. Text reads "incalcuable", should read "incalculable".

---

## Details 
Personal Computer in the basement of House Va'ruun Embassy, ID 00352ABC

## Game Version
1.7.36.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Go to the Personal Computer in the basement of the House Va'ruun Embassy in New Atlantis, read "Log 03: A Visitor".

**Comment by TESWartortle** [comment]
Fixed on Issue #730
