### ISSUE TITLE
Typo in 'Naeva Meetup (Evidence)' Datapad

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#692]
In the datapad, 'Naeva Meetup (Evidence)', there is a typo in Naeva's line beginning "Two things, Alder. And I'm going to make this..." At the start of the line, Adler is incorrectly typed as 'Alder'.

---

## Details 
There is a typo in the subtitles of the first datapad collected as part of the SysDef questline, called 'Naeva Meetup (Evidence)' and collected behind Adler in the Broken Spear. At the start of Naeva's line beginning "Two things, Alder. And I'm going to make this..." Adler is incorrectly typed as 'Alder'.

## Game Version
1.8.86.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Play game, listen to datapad with subtitles on

**Comment by Deebz96** [comment]
Fixed for the next release.
