### ISSUE TITLE
Sam Coe ShipEmbark incorrect dialogue

### ISSUE THREAD

**Issue by Aurelianis** [Starfield-Community-Patch/Starfield-Community-Patch#697]
When boarding the derelict starstation in Failure to Communicate, Sam Coe speaks as if he is entering the player's ship. 

### Details

Not sure if it specific to this location but it is the derelict starstation by Altair IV. He said something along the lines of Hello, ship, glad to see Cora hasn't taken off.

### Game Version

1.8.86

### Language

English (EN)

### Have you recreated this issue on a new game?

Yes, I can recreate this issue.

### Reproduction Steps

Board the station with Sam.

**Comment by TESWartortle** [comment]
Not a bug. The comment is said as you look out the window and see your ship. He is saying he is glad to see that Cora didn't leave them stranded on the spacestation.

See 002B8A7D - NLDT context

**Comment by Aurelianis** [comment]
Yep, you're right. Closed.
