### ISSUE TITLE
Vial Placement Error

### ISSUE THREAD

**Issue by Ghastly13** [Starfield-Community-Patch/Starfield-Community-Patch#7]
There is a vial placed within a desk organizer, which causes clipping. This is in the Kreet Research Lab, which I don't know the formID of.
![20230831223243_1](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/assets/83313692/972f9d40-8ce4-40d6-bc42-b7bee2fddcf7)
Will update with new information as it becomes available. This is of the utmost importance.

**Comment by Ghastly13** [comment]
The pen sitting on the whiteboard right next to the placement of the vial is unobtainable. Just putting this here too because it'll probably be pretty easy to patch once the CK releases.

**Comment by Noggog** [comment]
Looking for anyone else to reproduce.   Any @Starfield-Community-Patch/qa willing to take a look?

(This style issue doesn't always need to be double checked, but just flexing the systems a bit)

**Comment by Geeknasty** [comment]
>>> Looking for anyone else to reproduce. Any https://github.com/orgs/Starfield-Community-Patch/teams/qa willing to take a look?

I can confirm there is a vial with the RefID `0011304a` that's clipping inside a PaperTray02 with RefID `00113018`

![Image](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/assets/103335300/88631a06-545f-426d-a022-248fff818ae6)

**Comment by Aurelianis** [comment]
ESM attached that moves the vial from inside the paper tray to in front of it. Attached:
[SFCP_Issue_007.zip](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/files/15366808/SFCP_Issue_007.zip)
