### ISSUE TITLE
MAJOR Game-breaking Ship/ Den Bug

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#70]
There is a bug I encountered, where by boarding a pirate ship, taking it to the den to register it, and switching your home ship back to your old ship will cause major POIs to disappear along with turning your ship invisible. 

---

## Details 
PC- Steam Version 
About 40h in at the time of the bug, no mods installed at the time.
I encountered a bug where my ship when flying in orbit was transparent and the engines/shields/turrets and additional details were invisible. On a planet or space port, everything but the portholes and connection points were invisible. There were additional bugs including details in New Atlantis disappearing. Floor geometry was missing, doors were spawning off axis, and more. I was no longer able to access the Trade Authority Kiosks as they were missing too. I found a reddit thread of people who encountered the exact same bug, and the steps to recreate it always line up. 

https://www.reddit.com/r/Starfield/comments/167x7rh/dude_what_happened_to_my_ship_bug/

## Game Version
pre-launch

## New Game
Yes

## Reproduction Steps
Board a pirate ship (Pirate ship specifically seems to be a theme, but it could also be tied to the Pirate Scarab specifically) 
Kill Captain>
Take over ship>
Fast Trave to the Den>
Register the ship with the ship mechanic>
Before leaving the Den, change your home ship back to the ship you used when you boarded the pirate ship (For me both times, this was a modified version of the Frontier) >
Exit the Den via the door to the ship 

you should teleport to New Atlantis in the ship you set as your home ship (The Frontier for me).
The game is now bugged and the next time you hit a load screen E.G. going to orbit or going in and out of a settlement you ship will begin turning invisible and objects will start to despawn.

**Comment by Constellation-VASCO** [comment]
sorry if i entered anything else wrong on this. I wasn't sure of the version at the time, it was 1.7.23

**Comment by WolfGangS** [comment]
+1

This is a complete game breaker, only fix is reverting to a save before the issue occurred, which unfortunately is 2 days for me, becuase i was relying on quicksave and autosave, (I should know better with a bethesda game...)

Some users are suggesting a "workaround/fix" by editing the ship (chaning a cosmetic detail), this does seem to return the ships visuals, but only that, not the despawned kiosks, computers etc, game is completely broken, can confirm that i performed a similar set of actions to @Constellation-VASCO

**Comment by WolfGangS** [comment]
@Constellation-VASCO If you can i would reconmend changing the title to include "Ship invisible" or similar, to try and catch more people searching for a similar bug

**Comment by spkyghzt** [comment]
+1

This seems to occured at ANY space station that has a technician there. So the Den is unfortunately not the only place, but all of them after strenuous testing.

**Comment by alesimula** [comment]
+1

This bug completely breaks the game, and it's both hard to realize the game is FUBAR on the first place, and to tie it to the moment you stole the ship

Unfortunately, I only realized god-knows-how-many hours after I encountered the Den-to-Atlantis teleport bug that the New Atlantis spaceport was actually broken, and even then, I thought the game was just acting weird as it usually does after running for a few hours

**Comment by rileyg98** [comment]
Also can confirm I've got this bug. Pain in the arse.

**Comment by TESWartortle** [comment]
Same issue as #54 . Known bug, fix to be released by BGS as of v. 1.8.88

**Comment by Aurelianis** [comment]
Fixed in v1.8.88
