### ISSUE TITLE
NPC conversations, but they are not near each othe

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#702]
.

---

## Details 
had this happened twice, inside the lodge

first barret was talking to cora about books, but only barret was there. Don't know where cora was, also couldn't hear her voice, just the subtitles playing
second time was between sarah and walter, again only sarah was on the scene, and only the subtitles played without walter's voice

## Game Version
1.8.86.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
.

**Comment by Deebz96** [comment]
I believe the Walter and Sarah conversation was fixed officially.

The Barrett and Cora conversation has uniquely broken conditions which can allow this quest to start regardless of their distance from each other, and an issue with the scene which made Barrett travel to himself before the conversation starts. These two issues combined allowed this conversation to take place between these two characters while they are standing anywhere in The Lodge.

Fix attached which limits this quest to only start if these two characters are within 20 meters of each other (like all the others), and to make Cora travel to Barrett for the conversation to begin.

[SFCP_702.zip](https://github.com/user-attachments/files/16647028/SFCP_702.zip)
