### ISSUE TITLE
Crimson Fleet Multiple progression blocks

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#711]
Wow, so glad I didn't try this faction until I had 300 + hrs. Two quest-breaking bugs that I have to resolve using console commands.

---

## Details 
Eye of the Storm:
https://www.reddit.com/r/Starfield/comments/16d97hu/eye_of_the_storm_quest_bug/

Listening to all 3 audio logs multiple times did not ever progress this quest for me. A lot of other players encounter this issue (some probably user error), but the flag on all 3 audio logs should probably progress as soon as you listen to a snippet. Especially since I hate the Kryx voice and the awkward dog-panting between words that he does.

Later, the space battle portion of Legacy's End has multiple issues, from destruction of turrets or whatever not progressing, but many players (including me) seem to get stuck trying to "Destroy all UC/crimson fleet" objective of Legacy's End.

One player solved this by finding an enemy still alive inside the vigilance to kill. I suspect there may be buggy spawns preventing players from killing them all.

https://www.reddit.com/r/Starfield/comments/16oqe6t/legacys_end_crimson_fleet_side_bugged/

This is by far the least polished questline I have played in Starfield.

## Game Version
1.8.86.0

## Language
English (EN)

## New Game
No

## Reproduction Steps
Reach the latter stages of the Crimson Fleet quest line. Listen to the 3 Kryx audio logs in an erratic manner, perhaps as soon as you find one, then run around, then try another. It seems anything less than perfection with listening to them in full after reaching the correct step will cause it to bug.

For the fleet portions, I'm not sure, as I haven't been able to NOT experience this bug.

**Comment by Constellation-VASCO** [comment]
There are so many different unique bugs people have across these last few missions:
https://www.reddit.com/r/Starfield/comments/16k4lon/legacys_end_quest_bugged/

Definitely where the QA team ran out of time.

**Comment by Constellation-VASCO** [comment]
https://www.reddit.com/r/Starfield/comments/16imyxk/legacys_end_bugged_hard/

This is another description of my main blocking issue.

**Comment by Deebz96** [comment]
Unable to replicate this one. It's possible it was fixed officially at some point. Closing unless more specific reproduction steps can be provided.
