### ISSUE TITLE
New Atlantis GalBank hole in the floor near wall behind the counter

### ISSUE THREAD

**Issue by ja231c** [Starfield-Community-Patch/Starfield-Community-Patch#72]
![Photo_2023-09-07-071254](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/assets/68137237/9072b30e-d5e0-4439-9181-847a5482253b)
![hole](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/assets/68137237/f863d6e5-337e-4dd6-aa09-4bb278cf5c14)

**Comment by Pickysaurus** [comment]
Form ID for the floor [0007CAB7]

**Comment by Pickysaurus** [comment]
The formID above is the entire floor for the room. It might be worth looking for a smaller piece of floor to fill the gap.

**Comment by Aurelianis** [comment]
Fixed in v1.1031.0
"Fixed gaps in the wall inside Galbank of New Atlantis."
