### ISSUE TITLE
Eyewitness - President Abello Subtitle Typo

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#722]
In the Vanguard mission 'Eyewitness', after the cabinet session, president Abello's subtitles incorrectly say "We'll have to make due with the tools we've got" where it should be written "We'll have to make *do* with the tools we've got".

---

## Details 
Eyewitness quest ID -  002AAE8D

## Game Version
1.8.86.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Play Eyewitness quest with subtitles on

**Comment by TESWartortle** [comment]
Fixed on issue #730
