### ISSUE TITLE
"Survey Planet" Mission Complete w/ Wrong Planet

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#724]
"Survey [Target Planet] in [Target Planet's System]" missions (from both regular Mission Boards and Constellation Mission Boards) are completed when 100% surveying any planet in the target planet's system. It becomes especially apparent when the target planet's system has other planets that just require a planetary scan to 100% (aka "Gas Giant"-, "Ice Giant"-, "Hot Gas Giant"-, and "Asteroid"-type planets/moons) and the target planet is not (aka "Rock"- and "Barren"-type planets/moons).

---

## Details 
Quest IDs from Constellation Mission Board (according to SF1View):
   FormIDs: 0022607A and 00184574
   EditorIDs: MB_SurveyPlanet01 and MB_SurveyPlanet02

Quest IDs from regular Mission Board:
   FormIDs: 00182C46 and 00137578
   EditorIDs: MB_SurveyPlanet03_LIST and MB_SurveyPlanet04_LIST

## Game Version
1.8.86.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
1) Obtain a Survey mission from any Mission Board
2) 100% survey any other planet/moon in the target planet's system (quickest if system has "Giant"-type planets)
3) Receive credits and XP for completing the Survey mission, despite surveying the wrong planet/moon
4) Bug re-created 🥳

**Comment by TESWartortle** [comment]
Unable to replicate on 1.8.88. Survey accepted from Constellation Mission Board to Magnar, Delta Pavonis. Survey Faraday 100% from ship. No change in quest of survey results of Magnus.

**Comment by Constellation-VASCO** [comment]
Yeah, I think this got silently patched in 1.8.88 or 1.8.87. I haven't been able to replicate it since updating either.
