### ISSUE TITLE
Eyewitness - Post-mission Dialogue Typo

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#730]
After the Vanguard mission 'Eyewitness', when visiting Gagarin, Chief Pretorius says "We sent a squad of officers to New Atlantis". However, the subtitles are incorrectly typed as "We sent a squad of officer to New Atlantis." 

---

## Details 
Eyewitness quest ID - 002AAE8D

## Game Version
1.8.86.0

## New Game
Yes

## Reproduction Steps
Finish Eyewitness quest, then approach Chief Pretorius on Gagarin.

**Comment by TESWartortle** [comment]
[Typo Fixes for SFCP.zip](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/files/13689736/Typo.Fixes.for.SFCP.zip)
Typo fixes for issues #730, 722, 684, 533
