### ISSUE TITLE
Ryujin Access is Key Optional Suit

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#735]
Wearing the Va'ruun Amabassador Suit during the quest Access is Key does not trigger the optional objective to wear a suit before talking to the guard. 

---

## Game Version
1.8.86.0

## Language
English (EN)

## New Game
No

## Reproduction Steps
Wearing the Va'ruun Ambassador Suit does not trigger the quest objective and you cannot talk to the guard. Switching apparel to another suit, in my case the Green Fashionable Suit, triggers the quest objective and allows you to speak to the guard. Switching back to the Va'ruun Ambassador Suit does not allow you to continue speaking to the guard even though the quest objective has been completed.

**Comment by TESWartortle** [comment]
Confirmed broken.

[Issue 735.zip](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/files/13694156/Issue.735.zip)

Adds keyword and condition form to support other clothing qualifying for quest. Updates Scene conditions. Adds keyword to Ambassador suit. Edits quest scripts to check for keyword. Should easily support adding other suits if identified just by adding the new keyword to them.
