### ISSUE TITLE
Deep Cave Windows is Crash

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#736]
Reaching the deepest part of the Deep Cave, which is part of the Abandoned Mine, a generic location in StarField, has an almost 100% chance of causing Windows to crash and the PC to shut down.
To recover from this shutdown, it is necessary to perform a cold boot, which involves unplugging the PC's power cable, clicking the power button several times to discharge the power internally, then reconnecting the cable and turning the power back on.
Below is a video of this procedure.

https://www.youtube.com/watch?v=saUWY4hbZf8

This symptom has been observed to recur even when the "Starfield Community Patch v0.0.2" was installed, has this been addressed in the current version?

Translated with DeepL.com (free version)

---

## Game Version
1.8.86.0

## Language
日本語（JA）

## New Game
Yes

## Reproduction Steps
https://www.youtube.com/watch?v=saUWY4hbZf8

**Comment by Deebz96** [comment]
Unable to replicate this issue, and I have been in this POI many times. If your entire PC is crashing, this is likely related to an unstable overclock, or another issue with your system.
