### ISSUE TITLE
In Memoriam Sarah Companion Quest final task

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#739]
So after you meet Sarah at the Colony War Memorial and she asks you to meet her at the waterfall to discuss things, the elevator leading up to the waterfall does not open/work. I tried to overcome this by using my Jetpack but as soon as I get to the top, she stops being my companion and enters the elevator on her own (without the door opening either I might add) and that’s where she stays. It doesn’t move up, she never exits, and you in turn cannot complete the quest and as such can never have a companion either.

---

## Details 
Sarah Morgan companion quest line “In Memoriam”, the last task meeting her up at the waterfall.

## Game Version
1.8.88.0

## Language
English (EN)

## New Game
No

## Reproduction Steps
Meet Sarah at the Colony War memorial, and go to the elevator leading to the waterfall. I also noticed that it did not let me enter the Lodge either around the same time, until I figured out a work around by completing the Overdesigned quest line that let me fast travel into the Lodge directly.

**Comment by Deebz96** [comment]
Unable to replicate. Closing until more specific reproduction steps can be provided.
