### ISSUE TITLE
[Groundpounder Quest] Lezama Won't Unlock Door

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#74]
During the Groundpounder quest, I was forced to use console commands to finish it. 

During the quest, Corporal Lezama is supposed to open a door for you after you clear the area of all Spacers. I killed every spacer on that map, searching everywhere for them (except for the locked areas that only were accessible past this point in the quest).

I had a waypoint for both Corporal Lezama as well as my ship. If I went up in my ship, I saw no waypoint other than back on the planet.

In the end, I simply used the 'TCL' console command to no clip through the door. This allowed me to talk to Corporal Lezama and progress the quest, but the door stayed locked. Every time I wish to enter that room, I need to use No Clip Mode.

---

## Game Version
1.7.23.0

## New Game
Yes

## Reproduction Steps
It seems to break the quest if you kill every Spacer before speaking with Private Mahoney. In both the original case and my new game test, I had killed all Spacers on the map before interacting with Private Mahoney and getting the actual quest objective to kill all Spacers.

**Comment by Aurelianis** [comment]
This was fixed in v1.9.47.0
"Groundpounder: Fixed an issue where the door to Lezama could sometimes be locked"
