### ISSUE TITLE
Sowing Discord Commerce Dialogue Option

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#747]
During the mission Sowing Discord for Ryujin I was able to select a [Commerce] dialogue option in the mission briefing when I do NOT have that skill unlocked

---

## Details 
It was specifically when discussing Arthur with Imogene during the initial mission briefing

## Game Version
1.8.86.0

## Language
English (EN)

## New Game
No

## Reproduction Steps
1) Start Sowing Discord
2) Ask to go over their backgrounds verbally rather than just rely upon the dossiers
3) When discussing Arthur, this option will be available even without the skill unlocked

**Comment by TESWartortle** [comment]
Confirmed broken.
Edits text for INFO 1e4d79 as well as assigning Commerce Perk to that INFO

[Issue 747.zip](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/files/13693970/Issue.747.zip)

Confirmed working.
