### ISSUE TITLE
Picking up evidence stops Doctor's Orders starting

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#752]
If you pick up the Gennady Ayton (Evidence) item in the Clinic before starting the Doctor's Orders quest given by Samira Mizrah in the Key, you will be unable to start that quest. The dialog with her to start the quest will appear, but the quest will never trigger.

---

## Details 
The Doctor's Orders quest is 001B6246, and is supposed to advance to stage 100 after receiving speaking to Samina, but it won't if the evidence is collected first. The evidence is spawned in by the Burden of Proof quest, which is 001E8E2A. The evidence item is itself 001DEDA4, and the reference for it in the Clinic (001DEBE6) is 001DDF9F.
The Doctor's Orders quest does contain an alias for this piece of evidence, and the script for stage 100 references this evidence, but as far as I'm aware from looking up a playthrough, the evidence itself isn't involved in the quest in any other way. I'm not experienced enough with quests to say this for sure/test it myself, but potentially this could be fixed by removing any connection to the evidence from the Doctor's Orders quest. The evidence is spawned by and is only used for the Burden of Proof quest, so I wouldn't think it would cause any issues.

## Game Version
1.8.86.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Start the Crimson Fleet/SysDef questline to get the Burden of Proof quest, and then go to the Clinic in the Narion system, and collect the Gennady Ayton (Evidence) item in the office. Then complete Deep Cover and Rook Meets King to get access to the Key, and speak to Samira. The dialog to start the quest should be there, but the quest shouldn't start after finishing the dialog.

**Comment by TESWartortle** [comment]
Confirmed this prevents the quest starting.
Optional flag set on quest alias.
Confirmed quest starts correctly.

[Issue752.zip](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/files/13693711/Issue752.zip)
