### ISSUE TITLE
companionaffinityeventsscript registers for incorrect menu

### ISSUE THREAD

**Issue by TESWartortle** [Starfield-Community-Patch/Starfield-Community-Patch#753]
companionaffinityeventsscript registers for "looksmenu" instead of "chargenmenu." As a result, companions do not comment on the player changing appearance at Enhance

### Details

companionaffinityeventsscript.psc has this line:
  Self.RegisterForMenuOpenCloseEvent("Looksmenu") ; #DEBUG_LINE_NO:264

Papyrus log shows:
[20:41:20] error: "LooksMenu" is not a valid menu name.
stack:
	[SQ_Companions (002A567C)].companionaffinityeventsscript.RegisterForMenuOpenCloseEvent() - "<native>" Line ?
	[SQ_Companions (002A567C)].companionaffinityeventsscript.OnQuestStarted() - "E:\BuildAgent\work\4c7f7506a0fb268b\Source\Scripts\CompanionAffinityEventsScript.psc" Line 264
[20:41:20] error: Cannot call BlockActivation() on a None object, aborting function call

2a800e is the related AFFE. Describing intended behavior

Vendorenhancescript.psc shows that CharGenMenu is the menu used at Enhance.

[Papyrus.0.log](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/files/13691431/Papyrus.0.log)
[Looks Menu register fix.zip](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/files/13691436/Looks.Menu.register.fix.zip)

### Game Version

1.8.88

### Language

English (EN)

### Have you recreated this issue on a new game?

Yes, I can recreate this issue.

### Reproduction Steps

New game, check papyrus log, see attached.

**Comment by Constellation-VASCO** [comment]
This was already fixed in v0.0.1 of the patch https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/blob/main/Scripts/Source/companionaffinityeventsscript.psc#L196
