### ISSUE TITLE
Emissary Barrett is white

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#756]
If the Emissary is Barrett from another universe while meeting him and the Hunter before going to the temple, when the Emissary reveals his face, he's light-skinned.

---

## Details 
Not sure if this is a bug because perhaps Barrett is not black in most universes?

## Game Version
1.8.86.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
1) Be playing the main story
2) have Barrett be killed by the Hunter
3) meet the emissary and the hunter and proceed through the dialogue on the Hunter's ship

**Comment by Aurelianis** [comment]
This actually affects them all. If Andreja is the Emissary, her skin tone and tints are not applied correctly. It's the same thing that sometimes happens to Unity you, when scars, makeup, etc are not applied as they should be. I believe this may be an engine level bug with the copy appearance function that is used to replicate the appearance of NPCs.

**Comment by Deebz96** [comment]
I have never experienced this myself, but Bethesda has fixed some issues relating to this in official updates. Closing this one, will work off of a new report if the issue can still be replicated.
