### ISSUE TITLE
Eye of the Storm - Credit Transfer

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#759]
The transfer of credits gets stuck.

---

## Details 
After inserting the keys and datacore and then activating the switch the process begins but gets stuck. Multiple reloads seems to let the process go a little further but, for me at least, it never completes. After a little googling and a visit to the Nexus the following mod resolved my issue - https://www.nexusmods.com/starfield/mods/7429. So it looks like there maybe an issue with a script.

## Game Version
1.8.88.0

## Language
English (EN)

## New Game
No

## Reproduction Steps
Insert the two keys, then the datacore before activating the switch.

**Comment by Constellation-VASCO** [comment]
Yep. Need people to try the fix to know if it really works how I think it did before commit changes to SFCP. Unless others can analyze and reach the same conclusion.

**Comment by Constellation-VASCO** [comment]
Will wait for confirmation from Korodic

**Comment by Aurelianis** [comment]
Fixed in v1.9.47.0
"Eye of the Storm: Fixed an issue that could cause data transfer to not start after placing the Data Core."
