### ISSUE TITLE
Misplaced computer [Cheyenne System, Washakie planet]

### ISSUE THREAD

**Issue by MiahNelah** [Starfield-Community-Patch/Starfield-Community-Patch#76]
There is a floating computer on Whashakie, Cheyenne system.

# Details
![image](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/assets/1334405/9b521754-893d-4dc6-a001-756a0b6526c7)

# Game Version
1.7.23.0

# New Game
Yes

# Reproduction Steps
Go to Washakie planet in heyenne system. Computer is upstair, near the landing pad of an Ore processing plant.
Position : -800 / 900 / 11

**Comment by Deebz96** [comment]
This terminal belongs to a robot pod, which can sometimes go invisible along with other surface objects. This requires an engine fix.
