### ISSUE TITLE
Pacifier Shotgun - Missing Keyword Breaking Perks

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#761]
The Pacifier Shotgun template is missing the WeaponTypeRanged keyword. This causes it to not benefit from the stealth attack perks, and likely any other buffs that check that keyword. (other shotguns, like the Breach template have the keyword. so its definitely a mistake, not a design choice)

---

## Details 
Pacifier: Weapon - 002953F8, needs the the WeaponTypeRanged (0002B714) keyword added to it. Perks that buff damage by checking for that keyword, such as Stealth and Concealment, don't apply to the gun because its missing the tag. Other shotguns like the Breach template have the keyword, so its definitely an oversight rather than intended.

## Game Version
1.8.86.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Stealth attack with a Pacifier shotgun when you have levels in the Stealth/Concealment perks gives a sneak attack message that says 2.5x dmg rather than the 5.0x it should say with the skills maxed. The damage is also noticeably lower than it should be if it was just a text bug. Also you can look at the weapon entry in xEdit and see that the keyword is missing, and that those perks are checking for that keyword.

**Comment by Pickysaurus** [comment]
This fix cannot be safely applied yet as the weapon has reflection data. 
> Error adding [ \ [00] Starfield.esm \ [40] GRUP Top "WEAP" \ [350] Pacifier "Pacifier" [WEAP:002953F8]] to [ \ [02] StarfieldCommunityPatch - Unlocalised.esm \ [11] GRUP Top "WEAP"]: Source contains Reflection and can not be copied

**Comment by Deebz96** [comment]
Fix will be included in 0.1.8.
