### ISSUE TITLE
The Hunter hairs clipping

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#766]
Before installing the patch, I met the Emissary and the Hunter on board their ship, neither of whom had any problems.

Since installing the patch, I've met the Fighter and Emissary again on leaving the NASA site.

I noticed, when zooming in on the faces during the dialogue, that the Hunter's hair (Aquilus) is visible through the helmet.

I saw that a fix had been made for the visible hair with the Graviplast helmet, perhaps it's this fix that's causing this problem? Maybe it's a base game issue but I know it happen now that the Community Patch is installed, my previous encounter with the Hunter don't show this problem.

Thank you for your early work on the game!

---

## Details 
No details, just the Hunter character is affected as far as I can tell now.

## Game Version
1.8.86.0

## Language
French (FR)

## New Game
No

## Reproduction Steps
It simply needs to find the Hunter and the issue will show.

Maybe it's a base game issue but I know it happen now that the Community Patch is installed, my previous encounter with the Hunter don't show this problem.

**Comment by Deebz96** [comment]
Not caused by the SFCP. This is an intermittent engine-level issue with these Starborn suits. Will require an official fix, or an SFSE fix.
