### ISSUE TITLE
Due in Full Mission 2

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#768]
The quest is bugged. I can not define details, only that this is happening the second time, in two full character games I've played. The internet reveals that this might be happening due to another party, or ship, destroying the target. At this point I can't even say if I am supposed to destroy a ship here, or hunt down an individual NPC on a planet/moon, because the quest description doesn't give it away. I can't even say which location I'm supposed to go, because using the key to auto select the corresponding system does nothing.

---

## Details 
I'm sorry. Can't even pinpoint the exact quest ID or stage.

## Game Version
1.8.88.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Go to Gal Bank in New Atlantis an talk to the guy on the left(I forgot name). He's handing out "debt collector" missions. The second mission is the one bugging out.

**Comment by Constellation-VASCO** [comment]
Again. Forgot to add Shattered Space as DLC prerequisite.

**Comment by Constellation-VASCO** [comment]
Shattered Space isnt released yet? I've attempted to resolve the issue here: https://www.nexusmods.com/starfield/mods/7030

Feedback is needed from users to confirm they dont have the issue again in future playthroughs as it's hard to reproduce before adding to SFCP.

**Comment by Constellation-VASCO** [comment]
Ignore that. I confused it up with the DLCs you'd get when having the game pre ordered.

**Comment by Constellation-VASCO** [comment]
I recal using the console fix over here: https://steamcommunity.com/app/1716740/discussions/0/5904837854428285586/
The ID is identical to yours.

**Comment by Constellation-VASCO** [comment]
We'll wait for feedback from Korodic on his fix for this one.

**Comment by Constellation-VASCO** [comment]
It's hard to pinpoint, since the quest is a one time only. But I've played through the whole string just yesterday and had none of the issues from before. So I guess this is fixed by either you guys or the latest patch.

**Comment by Constellation-VASCO** [comment]
This was bugged for me as well. 2nd quest, "delinquent spacer" in orbit around Planet-A (random) with a marker which was in two different systems. One in an entirely different system that leads to nothing and another around the named planet which also leads to nothing. If I follow the marker which is in the wrong system it shows 9000km or so away and even if I don't move it gets farther and farther away every second and can never be reached.

**Comment by Deebz96** [comment]
This is reportedly fixed officially in 1.14.
