### ISSUE TITLE
CTD when recruiting Lin to join your crew

### ISSUE THREAD

**Issue by Hawk1ns24** [Starfield-Community-Patch/Starfield-Community-Patch#77]
When recruiting Lin to your crew during the mission "Back to Vectera", there is a CTD that occurs the moment the Lin is now available text box appears.  I am currently playing on a Steam install of the game with only the Achievement Enabler mod installed.  The only console command I've used so far this playthrough is to add some Digipicks to my inventory.

Steps to Reproduce:
1. Play through the main story of the game until reaching the "Back to Vectera" quest.
2. Travel to Vectera and complete the objective of fixing the comms building.
3. Speak with Lin after to complete that portion of the quest.
4. Speak with Lin again to recruit her in joining your crew (Crash occurs here).

The issue begins with a short freeze when the confirmation text box appears after the recruitment dialogue and crashes to desktop approximately 2 seconds later.  There was no crash dump generated in the game's install unfortunately.  After a few attempts, I proceeded to the next phase of the quest to save Heller and took him to the Lodge where I was able to recruit him with no issues.  I then proceeded back to Lin's planet to try recruiting her again and the same exact crash occurs.

**Comment by Pickysaurus** [comment]
Cannot replicate this reliably.
