### ISSUE TITLE
Find "Primordial Network" in system xxx

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#782]
Random mission, primarily obtained via the Constellation mission board. You're supposed to find a "Primordial Network" on any of the planets of the system you've been send to. For me right now this is happening the third time. I recall one time it was in the "Gunibuu" system, now it's "Shoza". According to the internet this is a well knowen bug, and I personally used this fix: https://steamcommunity.com/app/1716740/discussions/0/5904837854443222266/

---

## Details 
According to the link provided upside the quest ID is: 001953FB. A fix is to set its stage to 100. The bug is happening because the "Primordial Network" is falsely placed on a moon, though I can not say if it as a moon orbiting the planet that's supposed to have the trait, or any other random planet. Another fix is, finding the moon that has the trait, and finish the quest. The moon is always supposed to be in the same system.

## Game Version
1.8.88.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Accept a Constellation, or general mission board mission, to find a "Primordial Network" and accept the quest. Known systems are: Vega, Gunibuu, and Shoza.

**Comment by Constellation-VASCO** [comment]
Since it's not mentioned in the issue itself: Apparently the bug that occurs is that locating a "Primordial Network" in the target system will not complete the quest properly (from the linked Steam discussion).

**Comment by Constellation-VASCO** [comment]
Bug is still alive and kicking. I've spend a couple of hours to nail the quest, but those random survey quests are tricky to deobfuscate to say the least. "SetStage 22607A 100" or "SetStage 184574 100" is still valid. All I can say is the quest fragment is properly setting the stage and quest objective etc. So my guess is either a wrong keyword or condition on any of the calling instances.

**Comment by Aurelianis** [comment]
This appears to be an issue with a property being incorrectly filled.

MB_SurveyTrait17 "Locate <Alias=PrimaryRef> in <Alias=TargetSystemLocation>" [QUST:001953FB]

Property: PlanetTrait is pointing to PlanetTrait13GaseousFont "Gaseous Font" [KYWD:0029081B] but it should be PlanetTrait17PrimordialNetwork "Primordial Network" [KYWD:0029081A]

Location Alias #4 uses location type PlanetTrait17PrimordialNetwork "Primordial Network" [KYWD:0029081A] so the property and the location alias were not the same, as they should be.

Fix attached (needs testing).
[PrimordialNetworkMBFix.zip](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/files/14409297/PrimordialNetworkMBFix.zip)

**Comment by gir489returns** [comment]
@Aurelianis I ran into this today, but did not save prior to scanning Kumasi I.

**Comment by Aurelianis** [comment]
I have tested and seems to be working fine with the fix I attached

**Comment by Constellation-VASCO** [comment]
Oh that's a goodie @Aurelianis. Thank you. I have it integrated into my master patch. I'll get back to this bug report with feedback if things turn out positively.
