### ISSUE TITLE
Typo in Jessamine Griffin's Subtitles

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#783]
J.G. has a line in which she asks "Need me for something, Boss?"; however the subtitle displays as "Need me for somehting, Boss?"

---

## Game Version
1.8.86.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Start a new game/playthrough, start the Crimson Fleet questline, gain access to the Key and recruit her. After that, spend some time around her in your ship until she says the line i mentioned above.

**Comment by TESWartortle** [comment]
[Issue783.zip](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/files/13799548/Issue783.zip)
