### ISSUE TITLE
Rothicite Extractor

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#784]
The 3rd-stage Rothicite Extractor is mislabeled.

---

## Details 
While other Extractors are labeled "Commercial" on the 2nd stage and "Industrial" on the 3rd stage, the Rothicite one is labeled both "Commercial" on 2nd and 3rd stages. The required materials switch as they should.

## Game Version
1.8.86.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Go to Carinae-III-A and build an Extractor in your Outpost.

**Comment by TESWartortle** [comment]
[Issue784.zip](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/files/13799547/Issue784.zip)
