### ISSUE TITLE
jet packs vanish and appear  

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#790]
when wearing a outfit, jet packs vanish after using them then do not re-appear until you use the jet pack again.  I believe Bethseda did this intentionally and it drives me crazy.  if you look in comments sections of mods dealing with hiding space suits or jet packs you will see post after post of people begging someone to fix this.....its a intentional bug the devs forced on us please be the community hero's and fix this.

---

## Game Version
1.8.86.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
just take off your space suit and use your pack......its despicable.....2023 and this.............no pistols display on your character........no melee display either.............WTF Devs.

**Comment by Constellation-VASCO** [comment]
You even state yourself that Bethesda did this intentionally, which clearly makes this not a bug.

**Comment by Pickysaurus** [comment]
Not a bug
