### ISSUE TITLE
Sam's their 

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#795]
Sam refers to player as their in the scene with Heller. I don't feel this is right, if the player has chosen a gender and narrative branches are in place. 

---

## Game Version
1.8.86.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
just go do the mission.

**Comment by TESWartortle** [comment]
Needs more information. What mission, what scene, what location

**Comment by Pickysaurus** [comment]
Marked invalid due to the lack of info

**Comment by Aurelianis** [comment]
Many games use "their" instead of she or he due to needing more voice lines recorded. This is not a bug and how many games reduce the number of voice lines needed for a game.
