### ISSUE TITLE
Instant space suit depletion

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#800]
Space suits -- it doesn't matter what type and what mods and buffs you have -- INSTANTLY deplete the second you exit a space ship.

---

## Details 
Using pure vanilla means, I had good clothing and a Starborn spacesuit. I even maxed out all of my physical skills. Still in certain environments, I get instant spacesuit depletion. And here's the funny part. I can get frostbite at 10 deg C. In real life that's shirt-and-short weather. Given the amount of talk on Reddit, this is a purely vanilla bug that Bethesda probably has no intention of fixing. I mean, what's the point of grinding to max out your physical skills, earn a Starborn space suit, and find the best clothing if it's all meaningless and you can get afflictions in the most illogical of conditions. To add salt to the wounds, I'm getting near instant afflictions while NPCs are walking around without space suits. 

## Game Version
1.8.86.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Wear any spacesuit. The best or the worst space suit. It doesn't matter. Exit your ship and explore any unsettled planet. Or maybe partly settled. Just not the planets where the main cities are. Watch how quickly you get afflictions (frostbite, etc.) in the most illogical of circumstances. And watch your spacesuit get instantly depleted even if you have max vanilla protection in that very category. For example, you can have 50 + 30 thermal protection and very quickly get frostbite. It's a SPACE suit. Not a bikini. 

If you really want to experience this, go to Londinium. It doesn't matter what spacesuit and buffs you have. The beeping instantly starts and you get frostbite before you walk 100 meters.

**Comment by Constellation-VASCO** [comment]
And let's not forget about Masada (Buried Temple). Near instant frostbite. Remember. SPACE suit. Why should I get near instant frostbite when I've maxed out thermal protection as much as possible?

**Comment by Constellation-VASCO** [comment]
Oh yeah, and the Red Mile. Frostbite? WTH? Oh, and when I'm inside the Red Devils headquarters during the Terramorph quest, Barrett keeps complaining how cold it is? Really? When all the NPCs are walking around WITHOUT spacesuits? I don't believe Todd Howard. Nobody actually tested this game.

**Comment by Constellation-VASCO** [comment]
Did I mention Londinion? (Really, couldn't Bethesda use the real name of the Roman city "Londinium". Anyway, OMFG! Yet again I'm hit with frostbite with SECONDS of landing there. And I'm wearing the Mantis Legendary Armor. WTFG was Bethesda thinking? Oh yeah, it doesn't matter if you're wearing God Tier armor, you're getting hit with frostbite no matter what armor, mods, and buffs you have. And yeah, nobody else in Londinium is bent over with life-threatening damage. Seriously Betheda, WTF?

**Comment by Deebz96** [comment]
Discussed more on #1110

**Comment by Constellation-VASCO** [comment]
I tried searching by # but didn't get any hits. How do you search by #?
