### ISSUE TITLE
Powers From Beyond - Still broken

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#805]
Issue #600 should not be closed. 

---

## Details 
re-open issue 600. Powers from Beyond is still broken. 

## Game Version
1.8.86.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Apply community patch, go to gunibuu II, no temple marker.

**Comment by Aurelianis** [comment]
Powers From Beyond issues have been fixed as of v1.10.31
