### ISSUE TITLE
Stuck during The Empty Nest

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#81]
During The Empty Nest, you need to claim the Artifact. Upon grabbing it, you are sent into the cutscene that always plays when grabbing an artifact, but after the cutscene, the objective still says to grab the artifact. The waypoint still points to the same spot, Sam talks like it's still in place. Possible to bypass by grabbing the artifact, watching the cutscene, and then using SetStage. I'm fairly sure this is just a simple wrong reference luckily.

---

## Details 
The Empty Nest: 000114C9
If I remember correctly, the stage it gets stuck on is 800, while the one it's supposed to go to is 900.

## Game Version
1.7.23.0

## New Game
No

## Reproduction Steps
During The Empty Nest, you need to go into a cave. After reaching the Artifact at the bottom, attack it with your mining laser to dislodge it, and then grab it. The cutscene will play, but the quest won't progress.
https://www.reddit.com/r/Starfield/comments/167fww2/game_breaking_bug_any_fixes/

**Comment by Deebz96** [comment]
Unable to reproduce this one in any playthrough. Possibly a fluke. Will need more specific reproduction steps otherwise.
