### ISSUE TITLE
Akila City Midtown Minerals Ownership

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#812]
Midtown Minerals, an ore shop in the town of Akila has some of the ore items lying around with not correctly working ownership, while others do. Looking at the culprits in xEdit right now, I can see the ownership is indeed correctly set up for all of the items to be owned by the "Freestar Collective" faction(000638E5). So my guess is if the player has a certain level of reputation, some things will be considered free to take, based on the value of the item. But that's just a wild guess. One way to fix this is setting ownership specifically to the shop owner. I think so because there are random items with low value that are never considered owned despite being part of an owned cell.

---

## Details 
cell id: 00098046
trader id: 00214694(ref), 00225482(base)
I noticed flag "unknown 17" has been enabled in the cell by your patch.

## Game Version
1.8.88.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Go to Akila City "Midtown Minerals", review all items.

**Comment by Constellation-VASCO** [comment]
Ok, been fiddling around with this. It turns out no matter which faction you set ownership to will be considered "owner", because there's a general threshold in the game that will consider literally everything in a cell with a value lower of 20, to be free to take by the player. There was a set of books in the back corner which also were "not owned", so initially I believed the threshold would be dynamic based on item type, but those books are actually not set owned.(refid: 001302D5)

The easiest way to test there is using console right from the start menu without loading a save game, which will bring you right to the interior cell front door:

player.moveto 349BEF

**Comment by Constellation-VASCO** [comment]
Found it! In game settings there's a value: "iCrimeStealDontCareValue". Guess what? It's set to 20. So you can probably ignore this bug report and expect another hardcore tweak mod uploaded today...:D

**Comment by Constellation-VASCO** [comment]
Regardless of my useless input I've uploaded the "fix" here:

https://www.nexusmods.com/starfield/mods/8094

**Comment by Deebz96** [comment]
Indeed, I think this one falls out of the scope of the SFCP.
