### ISSUE TITLE
Subtitles typo at Red Mile involving Donovan Rhys

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#815]
Dialogue is between two 'Red Mile Patron's and Donovan Rhys, all seated at a table in the Red Mile building. Dialogue is as follows: 'Patron: Wow. Donavan's a big softie after all. Who knew?'. Typo on "Donavan".

---

## Details 
Language: English
NPC: Donovan Rhys (Ref ID: 002B2BD9)

## Game Version
1.8.88.0

## Language
English (EN)

## New Game
No

## Reproduction Steps
1. Enter Red Mile main building interior.
2. Find dialogue sequence between two Red Mile Patron and Donovan Rhys NPCs who are all seated at a single table. (unsure if event is random)

**Comment by Deebz96** [comment]
Fixed for the next release.
