### ISSUE TITLE
Reload only partial or canceled.

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#819]
Emergency and Trauma Packs cause  reloading to cancel, even though the animation finishes. Use them before during or after reloading and you will only get a partial reload. Other people have this bug too and report med packs don't cause this bug.

---

## Details 
Latest version of the game.

## Game Version
1.8.86.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Shoot at the enemy and reload while using emergency or trauma packs.

**Comment by Deebz96** [comment]
This one may have been fixed officially, I have not been able to replicate it.
