### ISSUE TITLE
 Charybdis III Ghost Grazer Fauna Fix

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#829]
Charybdis III Ghost Grazer Fauna not appearing correctly until a save & reload

---

## Details 
Mod fix located here:
https://www.nexusmods.com/starfield/mods/8214
Mod description:
This mod provides a fix for Ghost Grazer fauna on Charybdis III, where the bird will not appear correctly until the player either on purpose or accidentally lands on the correct biome and cannot find the last fauna. Normally a save and reload is needed for this fauna as it appears to be at the engine level. This bird is the only cloaking animal of flight in the game and apparently the engine has a hard time instantiating both flight and cloaking at the same time as of engine 1.8.88.0. This bird is non-hostile, so I removed the cloaking armor and replaced it with the Glowing Grazer variant as a stop-gap until Bethesda fixes their issue. The bird will immediately show up upon cell load of the correct biome without any other special commands.

## Game Version
1.8.88.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Read description for fix which you can add to the next CP.

**Comment by Deebz96** [comment]
This one appears to have been fixed officially.
