### ISSUE TITLE
The Eye - Vlad Furniture

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#836]
The Eye - Vlad Furniture - Exit to Talk Problematic

---

## Details 
MustExit markers seem to be problematic in a few areas. On approach Vlad already has things to say from proximity before activating conversation. For example, NPCStanding_ReadingBook_MustExit approach Vlad, player has to wait for Vlad to put away his book, then start talking for on approach/proximity type dialog. He then immediately takes the book back out while player is trying to start conversation. Sometimes it loops and takes a few times to actually activate conversation, much like Trade Authority guy in Neon. It's up to you, obviously, but for me changing the respective markers from NPCStanding_ReadingBook_MustExit 11EF81 to NPCStanding_ReadingBook 63D0 and NPCClipboard_ExitToTalk 87016 to NPCClipboard 25EB0F worked wonders.

Refs
00089F62
0015DA88
0015DA89
0015DA8A
0015DA8B
0015DA8C

## Game Version
1.8.88.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
See description.

**Comment by Deebz96** [comment]
This has been corrected by Bethesda as of 1.10.31. Vlad is now much less painful to speak to.
