### ISSUE TITLE
Sam Coe - 00005999 - Missing FLST

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#842]
Sam Coe - 00005999 is missing Response Civilian Form List FLST 00180F0C

---

## Details 
Sam Coe - 00005999 is missing Response Civilian Form List FLST 00180F0C from companioncrimeresponsescript.

## Game Version
1.8.88.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
See description.

**Comment by Pickysaurus** [comment]
Does not appear to be an issue in 1.9.51
![image](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/assets/31670524/65364a6d-37cb-40fa-8a14-3f76fb074a2b)
