### ISSUE TITLE
The Den Vasco Wait Marker

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#843]
Vasco wait marker 0008C2D8 makes his right arm clip through the trashcan pretty badly when he pivots. I moved Y a little over to 35.75.

---

## Details 
Vasco wait marker 0008C2D8 makes his right arm clip through the trashcan pretty badly when he pivots. I moved Y a little over to 35.75.

## Game Version
1.8.88.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
See description

**Comment by Aurelianis** [comment]
Fix: 
[SFCP_Issue_843.zip](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/files/15392748/SFCP_Issue_843.zip)
