### ISSUE TITLE
Abandoned Industrial - Duplicates

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#848]
Duplicate containers Loot_Storage_Cooler_Common "Cooler" CONT: 001F9900

---

## Details 
000EF7B9 & 000EF7BC Loot_Storage_Cooler_Common "Cooler" CONT: 001F9900 are duplicate coordinates. No BGS Reflection on cell. Not a good idea to disable references if not absolutely needed so I moved 000EF7BC to the ground in front of the handtruck to the following coordinates:

X:-6.928970
Y:35.369999
Z:9.950000
Angle
X:0.0
Y:0.0
Z:352.2321

## Game Version
1.8.88.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Description

**Comment by Aurelianis** [comment]
Fix: 
[SFCP_Issue_848.zip](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/files/15392720/SFCP_Issue_848.zip)

**Comment by Constellation-VASCO** [comment]
also raised as #304
