### ISSUE TITLE
Dragonfire unavailable

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#856]
Dragonfire 1 and 2. In the edit window to buy,edit etc you get all panels on left, top and bottom.
The picture doesn't show and the loading icon just keeps on going round.
Worked fine before this update , don't know if any other ships do the same.
Thanks

---

## Game Version
1.9.51.0

## Language
English (EN)

## New Game
No

## Reproduction Steps
reloaded several times

**Comment by Constellation-VASCO** [comment]
also found spacetruk and big rig doing the same.

**Comment by Constellation-VASCO** [comment]
I Apologize it wasn't your problem. A mod I used to paint a module caused the problem. SORRY.
Can you please allow paint to be applied to ... taiyo/slope/cap/fore/aft as it was missed.
Thank You so much

**Comment by Aurelianis** [comment]
Closing since this was a mod conflict.
