### ISSUE TITLE
Vasco not in correct spot on ship

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#86]
Vasco not staying in the landing bay where he should be. Instead sits in the middle of the ship on whatever Ship Hab is considered "second deck" for some habs it is not a issue, but for Armory, Workshop, and a few others, it blocks both Player and Crew pathing.
Also if you only have a single deck, Vasco then rides on the top of the ship.

---

## Game Version
1.7.23.0

## New Game
Yes

## Reproduction Steps
Create second floor hab directly above Landing Bay, on any ship that is not The Frontier. Does not happen if you keep default frontier landing bay, and Frontier hab

**Comment by Constellation-VASCO** [comment]
I purchased the Galileo ship in New Atlantis, which has two decks, and VASCO still rides on top in the take off cutscenes.

**Comment by Constellation-VASCO** [comment]
I have also experienced this - he frequently is in the way in my multilevel ships and is not even there on a single deck ship.

**Comment by Constellation-VASCO** [comment]
I have encountered this bug a few times.

**Comment by Constellation-VASCO** [comment]
Can confirm this one as well. Have found Vasco in odd places on almost every ship. Was blocking the ladder on one of my ships. Just assigned him back to the Lodge.

**Comment by Aurelianis** [comment]
Fixed in v1.10.31.0
"Fixed an issue that could cause Vasco to appear incorrectly in the player's ship."
