### ISSUE TITLE
"The Pale Lady" random encounter

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#861]
Random space encounter - I got the UC Longsword version but apparently there are other versions which can also bug out.

---

## Details 
You see a derelict ship with a creepy sound played upon hail.  Entering the ship all the NPCs appear to be human but response with classic robot lines and also in the robot voice.  The activity marker points you to some audiologs and then nothing else happens.  If you try to kill the NPCs you get a UC bounty, same with destroying the ship as well as every companion hating the action.  You cannot take over the ship, but that is probably as it is meant to be.  Killing one of the NPCs seems to "complete" the "Investigate the ship" activity...
Here are some reddit posts on the topic:
https://www.reddit.com/r/Starfield/comments/17cmc7d/is_it_a_bug_pale_lady_ship_quest_stuck/
https://www.reddit.com/r/Starfield/comments/174hski/finally_got_the_pale_lady_random_encounter_and_it/

## Game Version
1.8.86.0

## Language
English (EN)

## New Game
No

## Reproduction Steps
1) Find a rare random space event and see if it bugs out on you or not

**Comment by Aurelianis** [comment]
Fixed in v 1.9.47.0
"The Pale Lady: Fixed rare case of inaccessible ship crew log data slate making it impossible to complete the encounter."
