### ISSUE TITLE
Lockpicking Gap Disapearance

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#862]
Occasionally while lockpicking - a gap in the ring will stop being displayed, dunno what causes it but I did manage to snag a screenshot at least:

https://steamcommunity.com/sharedfiles/filedetails/?id=3155514345

---

## Details 
Seems to happen after slotting at least one "key" in.  It is a visual bug only as the game still knows there is a gap there even if it doesn't display it - eg that screenshot?  That "key" goes in just fine even tho it looks like it shouldn't.

## Game Version
1.8.86.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Just keep picking locks and it'll happen eventually

**Comment by gir489returns** [comment]
I have run into this several times, it's not that there isn't a gap missing, it's that you used a piece that belongs somewhere else down the chain. I have run the auto solver on every single master/advanced/novice lock I can find, and it always solves it, so this is clearly just the user sucking at doing puzzles.

**Comment by Aurelianis** [comment]
The screenshot is just showing that you used the piece for this particular ring somewhere else.
