### ISSUE TITLE
Earth NASA Start Ramp

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#871]
Last Computer at Artefakt Room - Entries Lookup Failed! UI message
Community Patch 0.1.0 bugged
Community Patch 0.0.7 ok

---

## Details 
https://graslamaland.org/Starfield/CPbug/
there are 3 screenshots
one with the bug - Lookup Failed
one with the terminal were the bug occurs
one with reverted community patch 007 and how it should look like
-
there is a 2nd bug which i could solve with reverting to CP v0.0.7: Resource Benzene (Benzol in german) - also Lookup Failed with version CP v0.1.0

## Game Version
1.9.51.0

## Language
German (DE)

## New Game
Yes

## Reproduction Steps
install CP 0.1.0 - travel to the descibed spot
and
open star map - look for planets with benzene - UI shows LOOKUP  FAILED in UI
german language
--
revert to CP 0.0.7 - problem solved

**Comment by Constellation-VASCO** [comment]
this corpse crashes the game when you open the inventory of the corpse if CP v0.1.0 is installed (NASA Start Ramp near Artefakt Room/ below Aizas corpse
https://graslamaland.org/Starfield/CPbug/20240216225709_1.jpg

**Comment by Pickysaurus** [comment]
As usual you've extracted the BA2 for some reason. Don't do that. Delete the "Strings" folder under Data to fix it
