### ISSUE TITLE
Cut dialogue that is perfectly good.

### ISSUE THREAD

**Issue by JaeDLmods** [Starfield-Community-Patch/Starfield-Community-Patch#872]
I have found a ton of cut lines. These ones are simple enough to restore without issue.

[CutDialogueForSFCP.zip](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/files/14320062/CutDialogueForSFCP.zip)

### Details

check in XEdit, its disabled.

### Game Version

latest

### Language

English (EN)

### Have you recreated this issue on a new game?

Yes, I can recreate this issue.

### Reproduction Steps

check in XEdit, its disabled.

**Comment by JaeDLmods** [comment]
The pig dialogue fix is incomplete. Another line needs to be enabled that I can't find right now.

**Comment by Aurelianis** [comment]
Fixes included in the patch are intended to correct bugs or errors in the base game. Cut content is out of scope for SFCP.
