### ISSUE TITLE
Incoming Hazardous Weather - Status bug

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#882]
Incoming Hazardous Weather - seek shelter immediately. Persistent Status character bug even if you entered interiors or changed location.

---

## Details 
I found a temporary solution by removing spell 281ED2 via console commands. Could also get stuck with 1639ee/281ecf/163fe0.

## Game Version
1.9.67

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
started a new character

**Comment by gir489returns** [comment]
I too have encountered this, however, there is no reproduction steps that I have found, and as such, this tick is not very production or useful to the developers.

**Comment by Aurelianis** [comment]
I created a fix for it here:
https://www.nexusmods.com/starfield/mods/8629

**Comment by gir489returns** [comment]
> I created a fix for it here: https://www.nexusmods.com/starfield/mods/8629

Your fix for this works.

**Comment by Constellation-VASCO** [comment]
No longer an issue with newest patches 1.10.31 -> 1.10.32

**Comment by Pickysaurus** [comment]
Fixed in 1.10.32
