### ISSUE TITLE
Breyson Bayu Companion Response Dialogue Incorrect Conditions

### ISSUE THREAD

**Issue by Aurelianis** [Starfield-Community-Patch/Starfield-Community-Patch#888]
When speaking to Breyson during Absolute Power, he has dialogue to respond to companions but the conditions are incorrect so they never fire.

### Details

All INFOs under [DIAL:0018238B]
00182384
00182385
00182386
00182387

Conditions for GetDistance are set incorrectly and should be:
QuestAlias.GetDistance(PlayerRef [PLYR:00000014]) <= COM_InterjectionDistance [GLOB:0000D8A9]

For 00182386, both conditions are incorrect. The conditions should be:
QuestAlias.GetIsVoiceType(NPCMBarrett [VTYP:00005B85]) = 1 AND
QuestAlias.GetDistance(PlayerRef [PLYR:00000014]) <= COM_InterjectionDistance [GLOB:0000D8A9]

Fix Attached:
[BreysonBayuReponseFixCF06.zip](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/files/14442236/BreysonBayuReponseFixCF06.zip)

### Game Version

1.9.67

### Language

English (EN)

### Have you recreated this issue on a new game?

Yes, I can recreate this issue.

### Reproduction Steps

During Absolute Power, talk to Breyson. Choose "I agree, he deserves everything coming to him."  Breyson then talks about Benjamin Bayu talking about him behind his back. This is where a companion will chime in and Breyson is suppose to respond to them, but the conditions are incorrect so the dialogue doesn't fire.

**Comment by Constellation-VASCO** [comment]
The ESM provided seems to forward the records without actually changing them. I've manually applied the fix based on your notes here.
