### ISSUE TITLE
Combat Skill Tree Inaccessible

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#896]
Using the latest version of the community patch rendered my combat skill tree unusable. Despite having spent more than a dozen skill points on combat before using the community patch, I am now to spend points in tier 1 skills in order to be able to access tier 2+ skills. Disabling the mod in vortex resolved this issue.

---

## Game Version
1.8.86.0

## Language
English (EN)

## New Game
No

## Reproduction Steps
-

**Comment by Pickysaurus** [comment]
Very unlikely to be caused by this mod.
