### ISSUE TITLE
[New Issue] Quest "Missing Ingredient" Will Not Complete

### ISSUE THREAD

**Issue by gir489returns** [Starfield-Community-Patch/Starfield-Community-Patch#897]
After delivering the meat the quest still shows in the mission window.

![image](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/assets/100792176/4b6780a2-626d-4c4b-b7a0-0fc3c3fb9b84)

### Details

https://www.reddit.com/r/Starfield/comments/16o5tek/bug_quest_missing_ingredient_will_not_complete/
https://www.reddit.com/r/Starfield/comments/16o3bag/missing_ingredient_mission_bugged/
https://starfieldwiki.net/wiki/Starfield:Missing_Ingredient
https://afktrack.afkmods.com/index.php?a=issues&i=33777

### Game Version

1.9.71.0

### Language

English (EN)

### Have you recreated this issue on a new game?

Yes, I can recreate this issue.

### Reproduction Steps

Find a planet with settlers that will give you the random mission Missing Ingredient.
Complete it.
Bug appears.

**Comment by Constellation-VASCO** [comment]
temporary solution -> use console command stopquest 12f188. Sometimes it happens with The Boot too. Use stopquest d700d.

**Comment by Deebz96** [comment]
Got this quest tonight, was able to replicate. Simple issue, stage 995 was missing the Complete Quest flag. Fix attached:
[SFCP_897.zip](https://github.com/user-attachments/files/16920694/SFCP_897.zip)
