### ISSUE TITLE
CF03 Idles - Mathis Spamming Idles 00207EFA

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#907]
CF03 Idles - Mathis Spamming Idles 00207EFA timeout or Say Once

---

## Details 
Much like Andreja & Sarah's conversations when you first meet Andreja, Mathis repeats the same Idles over and over at The Lock, but with an extremely short timeout. I threw a Say Once over mine because he's got plenty of idles listed, but that's up to you whether you want to extend the timeout, Say Once or nothing at all. 

CF03_Idles "CF03_Idles" [DIAL:00207EFA]

## Game Version
1.9.71.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Description

**Comment by Aurelianis** [comment]
There are 15 comments for Mathis when you are exploring the Locke. I believe this to be more than enough, so added the Say Once flag to all of them.

Fix: 
[SFCP_Issue_907.zip](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/files/15392586/SFCP_Issue_907.zip)
