### ISSUE TITLE
Slayton Cell 0006A716 - Grav Drive Magnets

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#909]
All MSTT Grav Drive magnets are missing DDHoL.

---

## Details 
All MSTT Grav Drive magnets are missing, well, I put Unknown 4, but whatever CK will actually call these XALG flags. They quite often go flying when a companion or player even gets near them, and actually out of the grav drive cage.

GravMagnet_01 [MSTT:000F23CC]
GravMagnet_02 [MSTT:000F23D0]

## Game Version
1.9.71.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Description

**Comment by Deebz96** [comment]
This does appear to be an issue, but I'll veto this one because these objects are used in real grav drives as well. These physics would come into play when ships are destroyed.
