### ISSUE TITLE
Pit Stop - Cell 00295334 - Contra & Aid Placement

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#910]
Contraband_Any 0003D28B and Chem_Any 0003D28A obstructed

---

## Details 
Contraband_Any 0003D28B and Chem_Any 0003D28A are on the floor. ShipBunkStorage_05 000890D7 is sitting on top of them on the floor. This is ShipBunkStorage that does not open or have a door like a locker so it's not meant to place inside. My only guess is because the contra and aid are not in a layer and the storage is layer Room01 00089233 and they didn't have all layers loaded on placement. I just put them on top of it as there's no reflection on this cell.

I did the following:
Contra:
X: -13.5
Z: 34.6

Aid:
Z: 34.5

## Game Version
1.9.71.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Description

**Comment by Aurelianis** [comment]
Fix: 
[SFCP_Issue_910.zip](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/files/15392392/SFCP_Issue_910.zip)
