### ISSUE TITLE
Particle Beams Meant to Benefit from Lasers Skill

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#911]
As of the most recent patch by Bethesda, there was a line that serves as the most confirmation we will get for Particle Beams being affected by the Lasers skill. 

"Particle Beam weapon kills should now increment Laser Kills in Combat Stats." 

As it appears that particle beams are meant to be counted as lasers by the in-game stats, this suggests that Bethesda intends for particle beams to also benefit from the lasers skill as they still do in the base version of the game.

---

## Details 
I was told to submit this here by Pickysaurus.

## Game Version
1.8.86.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Start a new game unmodded, take the Lasers skill, see particle beam weaponry affected by lasers skill.

**Comment by Deebz96** [comment]
Fixed in SFCP 0.1.4

**Comment by Constellation-VASCO** [comment]
It looks like SFCP 0.1.4 did not fix it.
