### ISSUE TITLE
[New Issue] All UC Security on New Atlantis respond will the same thing.

### ISSUE THREAD

**Issue by gir489returns** [Starfield-Community-Patch/Starfield-Community-Patch#915]
All guards randomly respond with the same thing, as well if you interact with them.

### Details

I picked the Soldier trait. It seems after the 1.10.31 patch, all UC Guards on New Atlantis keep commenting on it and nothing else.

### Game Version

1.10.31

### Language

English (EN)

### Have you recreated this issue on a new game?

Yes, I can recreate this issue.

### Reproduction Steps

https://youtu.be/uNRRFrLJSVU

**Comment by gir489returns** [comment]
This might be related to the change in #898

**Comment by Deebz96** [comment]
Fixed by Spriggit v0.18, in Community Patch version 0.1.2.
