### ISSUE TITLE
Unable to fast travel or land on planets

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#916]
Since the latest Bethesda Update, I can no longer fast travel or land on planets with ships I have captured in space.   I noticed with a new game that when you first enter space from Vectera all the power is taken from the modules on the ship.  I apply power and fight the pirates, take over the last ship and I am unable to fast travel or land on Kreet.  I disable the community patch, start a new game and I can fast travel and land with the pirate ship I took over.  Unfortunately, disabling the patch has no effect on my current playthrough.  I first noticed the problem, when I took over a Crimson Fleet Wraith or Reaper and could not fast travel or land. I made two other attempts with a 1st Calvary Ship and the Dumas and had the same result.   

---

## Game Version
1.10.31

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Take over a hostile ship and attempt to fast travel or land on planet.

**Comment by Deebz96** [comment]
Not able to replicate this one. I was able to land and fast travel correctly with the latest version of the community patch, on the latest version of the game.

I am uncertain if having the engines or grav drive destroyed can prevent you from traveling, but it would make sense if so. Can you confirm this is happening even with these modules being online?

**Comment by gir489returns** [comment]
I had this happen to me a few times, teleporting to New Atlantis and swapping my ship fixed it, but I have no idea how to fix it normally.

**Comment by Deebz96** [comment]
Will need more specific reproduction steps to investigate. Closing this one as a potential fluke.
