### ISSUE TITLE
Environmental Damage / Suit Protection

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#923]
Whenever im outside with a spacesuit in canada weather the suit protection runs out in like a minute. Trying to walk from my ship to red mile and i get frostbite. Any suit. even my best suit with modded thermal has the issue. please for the love of god adjust how long suit protection lasts.

---

## Game Version
1.8.86.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Ive seen over 100 comments and posts about this same issue. All you have to do is walk from ur ship to red mile and your high tech super advance spacesuit will fall apart in the canadian weather.

**Comment by Constellation-VASCO** [comment]
My personal take on this one is that it's outside of the scope of the patch. Although I agree that suit protections are pretty wonky right now, this would be a balancing change. Not a bug fix.

I also think it's pretty likely that Bethesda themselves will address this on their own eventually, when they add survival elements. Assuming they make afflictions a bigger deal with that addition, the current suit protection system would need to be rebalanced to properly support that.

**Comment by Aurelianis** [comment]
Closing as out of scope. SFCP focuses on bug fixes and balance changes are out of scope.
