### ISSUE TITLE
Minerva Secret - Minerva Clement Volii Hotel

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#927]
From what I saw on youtube, it's a real pain in the dark side to get her to reveal her *big* secret. Which tbh, it's composed from some lousy lines of dialogue. Can this process be sped up after renting (ex.) a room for a week?

---

## Details 
No real need, just a thought.

## Game Version
1.10.32

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
No real need, it's there and annoying.

**Comment by Aurelianis** [comment]
Fixes included in the patch are intended to correct bugs or errors in the base game. As this int not a bug or error, it is out of scope for SFCP.
