### ISSUE TITLE
All that money can buy quest entry outdated

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#930]
The outdated entry of SCP overwrites the recent fix by Bethesda. 

---

## Details 
[002C1C9B] Xedit shows the latest update make quest alias Ryleigh "allow dead" to fix a potential quest not starting bug. 

## Game Version
1.10.32

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Just open xEdit to see the record.

**Comment by Deebz96** [comment]
Thank you for the report. This one will be handled as part of this issue: https://www.starfieldpatch.dev/issues/924
