### ISSUE TITLE
Microgun Disappears when holtered

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#935]
When you holster/stow the microgun[000546CD] it disappears and is not displayed on your characters back like all other weapons of its class.

---

## Details 
Microgun[000546CD] is missing a keyword R_BackPackHolster_LowGrip [KYWD:0009FAD6]. You can reference my mod https://www.nexusmods.com/starfield/mods/9000 which provides a temporary fix for this.

## Game Version
1.10.32.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Equip the Microgun and the stow/holster it.

**Comment by Deebz96** [comment]
Checked this one ingame, and saw the gun clipping badly into my boostpack. Other rifles did not have this same issue. This may have been intentional on Bethesda's part.
