### ISSUE TITLE
April 17 update complete F... up

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#939]
After loading "continue" this is a failure to launch into a working game

---

## Details 
white screen with black figures (chairs people etc just floating about ... went back to the October update all is good  .... so there appears to be some issue with this latest April update...

## Game Version
1.10.32 latest stream

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Install SCP April Update .... Total F ..up  uninstall update go back to October update everything works as expected.

**Comment by Deebz96** [comment]
This is not enough information to go on. Can you provide a save file which failed to load?

**Comment by Deebz96** [comment]
Was caused by a conflict with an outdated mod: CoraCoeMultiversalBookHunter
