### ISSUE TITLE
Frequent game crash

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#94]
Game crashes while pilot, in dialogue and while crafting.

---

## Details 
Game crashing while piloting the ship, when I leave the planet, teleport to another system, especially while the game loads.

It also crashes mid dialogue.

It also crashes while I'm using the crafting table or something similar.

Tried almost all internet remedies. No luck.

Please help! Game unplayable.

## Game Version
1.7.23.0

## New Game
No

## Reproduction Steps
You need specific Windows PCs to recreate this. A lot of people are have the same or similar problems. Check Reddit.

**Comment by Constellation-VASCO** [comment]
Issue might relate to auto save.

**Comment by Constellation-VASCO** [comment]
I was having this issue, and it turned out that it was having chrome open in the background that was causing my crashes.

**Comment by Constellation-VASCO** [comment]
The game crashes every 5-10 minutes without any error message
we used every trick available on the internet
but nothing helped so it's unplayable
every new game launch has this

**Comment by Constellation-VASCO** [comment]
Having the same issue here. Frequent crashes, especially on New Atlantis, where it crashes every ~30 secs.. Also tried every solution I found on the internet without any success. This is especially bad because it renders the game completely unplayable. Please help!

**Comment by Constellation-VASCO** [comment]
Correction: Not an autosave issue.

**Comment by Constellation-VASCO** [comment]
I've tried limiting my CPU and turning off autosave, crashes happened less but still seem to be a major issue

**Comment by Constellation-VASCO** [comment]
would add to this one. 

Game was fine for first 2 hours or so, then it crashed the moment i entered the Lodge. I could access it only once i loaded the auto save that occurs when you enter new location.

What i've done so far to fix the problem: amd drivers update, disabling any feature that had to do with resoultion scaling, administrator mode launch.

The lodge is the most crash intensive place, but the crash can be replicated if you fast travel around several times in a row, then it would crash on load of the new location or some moments after. It does not seem to be like a problem with auto save: crash can occur once you have entered the location, game auto saved, you run around for like 20 seconds, it hangs and crashes.

**Comment by Constellation-VASCO** [comment]
This youtube link might help:
https://youtu.be/xuAqL_Xts-0?si=gCZW0AZsozLNBPzU

**Comment by Constellation-VASCO** [comment]
Starfield uses ExecuteIndirect to make the mentioned problem happen many times in a row, making things even worse.

**Comment by Constellation-VASCO** [comment]
https://www.reddit.com/r/pcmasterrace/comments/16eq1rp/comment/k01q3u8/?utm_source=reddit&utm_medium=web2x&context=3

**Comment by Constellation-VASCO** [comment]
************* Preparing the environment for Debugger Extensions Gallery repositories **************
   ExtensionRepository : Implicit
   UseExperimentalFeatureForNugetShare : false
   AllowNugetExeUpdate : false
   AllowNugetMSCredentialProviderInstall : false
   AllowParallelInitializationOfLocalRepositories : true

   -- Configuring repositories
      ----> Repository : LocalInstalled, Enabled: true
      ----> Repository : UserExtensions, Enabled: true

>>>>>>>>>>>>> Preparing the environment for Debugger Extensions Gallery repositories completed, duration 0.000 seconds

************* Waiting for Debugger Extensions Gallery to Initialize **************

>>>>>>>>>>>>> Waiting for Debugger Extensions Gallery to Initialize completed, duration 0.016 seconds
   ----> Repository : UserExtensions, Enabled: true, Packages count: 0
   ----> Repository : LocalInstalled, Enabled: true, Packages count: 36

Microsoft (R) Windows Debugger Version 10.0.25877.1004 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.


Loading Dump File [C:\Program Files (x86)\Steam\steamapps\common\Starfield\Starfield_09-13-13-59.dmp]
User Mini Dump File: Only registers, stack and portions of memory are available

Symbol search path is: srv*
Executable search path is: 
Windows 10 Version 22623 MP (16 procs) Free x64
Product: WinNt, suite: SingleUserTS
Edition build lab: 22621.1.amd64fre.ni_release.220506-1250
Debug session time: Wed Sep 13 19:59:37.000 2023 (UTC + 6:00)
System Uptime: 0 days 0:02:21.295
Process Uptime: 0 days 0:01:21.000
................................................................
................................................................
........................
This dump file has an exception of interest stored in it.
The stored exception information can be accessed via .ecxr.
(4330.23cc): Access violation - code c0000005 (first/second chance not available)

+------------------------------------------------------------------------+
| This target supports Hardware-enforced Stack Protection. A HW based    |
| "Shadow Stack" may be available to assist in debugging and analysis.   |
| See aka.ms/userhsp for more info.                                      |
|                                                                        |
| dps @ssp                                                               |
|                                                                        |
+------------------------------------------------------------------------+

For analysis of this file, run !analyze -v
ntdll!NtGetContextThread+0x14:
00007ffe`6b090b64 c3              ret
0:058> !analyze -v
*******************************************************************************
*                                                                             *
*                        Exception Analysis                                   *
*                                                                             *
*******************************************************************************


KEY_VALUES_STRING: 1

    Key  : AV.Fault
    Value: Read

    Key  : Analysis.CPU.mSec
    Value: 562

    Key  : Analysis.Elapsed.mSec
    Value: 220425

    Key  : Analysis.IO.Other.Mb
    Value: 26

    Key  : Analysis.IO.Read.Mb
    Value: 0

    Key  : Analysis.IO.Write.Mb
    Value: 48

    Key  : Analysis.Init.CPU.mSec
    Value: 93

    Key  : Analysis.Init.Elapsed.mSec
    Value: 90005

    Key  : Analysis.Memory.CommitPeak.Mb
    Value: 196

    Key  : Failure.Bucket
    Value: INVALID_POINTER_READ_STACK_POINTER_MISMATCH_c0000005_VCRUNTIME140.dll!memcpy

    Key  : Failure.Hash
    Value: {59333233-a0bf-fd4e-5798-bbeec4c3131f}

    Key  : Timeline.OS.Boot.DeltaSec
    Value: 141

    Key  : Timeline.Process.Start.DeltaSec
    Value: 81

    Key  : WER.OS.Branch
    Value: ni_release

    Key  : WER.OS.Version
    Value: 10.0.22621.1

    Key  : WER.Process.Version
    Value: 1.7.23.0


FILE_IN_CAB:  Starfield_09-13-13-59.dmp

NTGLOBALFLAG:  0

PROCESS_BAM_CURRENT_THROTTLED: 0

PROCESS_BAM_PREVIOUS_THROTTLED: 0

CONTEXT:  (.ecxr)
rax=0000009febcfeb98 rbx=0000009febcfef30 rcx=0000009febcfeb98
rdx=0000029d34350000 rsi=0000009febcfecf0 rdi=0000000000000001
rip=00007ffe50661404 rsp=0000009febcfbc18 rbp=0000009febcfbd80
 r8=0000000000000001  r9=00007ffe50661404 r10=00007ffe50660000
r11=2000000000000000 r12=0000009febcff600 r13=0000000000000000
r14=000002a166cdf0b0 r15=0000000000000000
iopl=0         nv up ei pl nz na pe nc
cs=0033  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010202
VCRUNTIME140!memcpy+0x114:
00007ffe`50661404 0fb60a          movzx   ecx,byte ptr [rdx] ds:0000029d`34350000=??
Resetting default scope

EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 00007ffe50661404 (VCRUNTIME140!memcpy+0x0000000000000114)
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
NumberParameters: 2
   Parameter[0]: 0000000000000000
   Parameter[1]: 0000029d34350000
Attempt to read from address 0000029d34350000

PROCESS_NAME:  Starfield.exe

READ_ADDRESS:  0000029d34350000 

ERROR_CODE: (NTSTATUS) 0xc0000005 - The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s.

EXCEPTION_CODE_STR:  c0000005

EXCEPTION_PARAMETER1:  0000000000000000

EXCEPTION_PARAMETER2:  0000029d34350000

STACK_TEXT:  
0000009f`ebcfbc18 00007ff6`c36bd257     : 0000009f`ebcfee60 000002a1`66cdf0b0 0000009f`ebcff601 00000000`00008000 : VCRUNTIME140!memcpy+0x114
0000009f`ebcfbc20 00007ff6`c38d9b53     : 0000029d`343403d0 0000009f`ebcfbd80 00000000`00000000 00000000`00000000 : Starfield!Scaleform::Render::Matrix2x4<float>::GetYScale+0xc4dae3
0000009f`ebcfbc50 00007ff6`c3f068ce     : 0000009f`ebcfec01 0000009f`ebcfecf0 00000000`00000000 00000000`00000000 : Starfield!Scaleform::Render::Matrix4x4<float>::SetIdentity+0x216317
0000009f`ebcfbc80 00007ff6`c3f71e17     : 0000029d`3d23e560 0000009f`ebcfec00 0000009f`fffd003d 0000009f`9b4fd18b : Starfield!Scaleform::Render::Matrix4x4<float>::SetIdentity+0x843092
0000009f`ebcfeb90 00007ff6`c2fe86b8     : 000002a5`00000001 0000029d`3d3952e0 0000009f`ebcfecf0 000002a5`8824f568 : Starfield!Scaleform::Render::Matrix4x4<float>::SetIdentity+0x8ae5db
0000009f`ebcfebe0 00007ff6`c2fe85ba     : 00000000`00000001 0000009f`ebcfee60 000002a5`756028e0 0000009f`ebcfecf0 : Starfield!Scaleform::Render::Matrix2x4<float>::GetYScale+0x578f44
0000009f`ebcfec90 00007ff6`c2d26415     : 000002a5`8824f500 000002a5`75602880 000002a5`75602880 0000009f`ebcfef30 : Starfield!Scaleform::Render::Matrix2x4<float>::GetYScale+0x578e46
0000009f`ebcfecd0 00007ff6`c272e5c8     : 00000000`00000002 000002a5`755f6138 000002a5`75602880 000002a5`75602880 : Starfield!Scaleform::Render::Matrix2x4<float>::GetYScale+0x2b6ca1
0000009f`ebcfef10 00007ff6`c2d0f60d     : 000002a5`00000002 000002a5`a8fbb340 000002a5`755f6138 0000009f`ebcff140 : Starfield!ffxFsr2ResourceIsNull+0x13fc8
0000009f`ebcff040 00007ff6`c2c91731     : 00000000`00000000 00000000`00000000 00000000`00000000 000002a5`755d0088 : Starfield!Scaleform::Render::Matrix2x4<float>::GetYScale+0x29fe99
0000009f`ebcff1f0 00007ff6`c2cb1f0d     : 00000000`00000000 000002a1`00000000 00000000`00000000 00000000`00000000 : Starfield!Scaleform::Render::Matrix2x4<float>::GetYScale+0x221fbd
0000009f`ebcff4b0 00007ff6`c2c84cf2     : 000002a1`3d41c3e0 000002a5`755d0000 000002a5`00000000 000002a5`755d0128 : Starfield!Scaleform::Render::Matrix2x4<float>::GetYScale+0x242799
0000009f`ebcff500 00007ff6`c2ca7165     : 000002a5`755f68b8 000002a5`755d0000 00000000`00000000 00007ff6`c68e0bf8 : Starfield!Scaleform::Render::Matrix2x4<float>::GetYScale+0x21557e
0000009f`ebcff540 00007ff6`c2bd1167     : 00000000`00000003 0000009f`ebcff801 00000000`00000001 000002a5`75602bb0 : Starfield!Scaleform::Render::Matrix2x4<float>::GetYScale+0x2379f1
0000009f`ebcff690 00007ff6`c2bc9385     : 000002a5`a9caf880 0000009f`ebcff710 00000000`00000006 000002a5`afd92e40 : Starfield!Scaleform::Render::Matrix2x4<float>::GetYScale+0x1619f3
0000009f`ebcff6e0 00007ff6`c2bd3790     : 000002a5`a9caf880 00007ff6`c8d2a605 0000009f`ebcff7a0 000002a5`9493cd78 : Starfield!Scaleform::Render::Matrix2x4<float>::GetYScale+0x159c11
0000009f`ebcff710 00007ff6`c4328144     : 000002a5`9493cce0 00000000`00000000 0000009f`ebcff7f0 0000009f`ebcff7c0 : Starfield!Scaleform::Render::Matrix2x4<float>::GetYScale+0x16401c
0000009f`ebcff740 00007ff6`c432d816     : 0000009f`ebcff7e0 00007ff6`c8d2a600 0000009f`ebcff830 00007ff6`c8d2a660 : Starfield!Scaleform::Render::Matrix2x4<float>::SetZero+0x18cd04
0000009f`ebcff780 00007ff6`c432d87b     : 0000029d`4d330a00 0000009f`ebcff830 00007ff6`c8d2a698 00007ff6`c40f3b5b : Starfield!Scaleform::Render::Matrix2x4<float>::SetZero+0x1923d6
0000009f`ebcff7c0 00007ff6`c432daeb     : 00007ff6`c8d2a660 0000009f`ebcff870 00007ff6`c8d2a6b8 00007ff6`c27609c2 : Starfield!Scaleform::Render::Matrix2x4<float>::SetZero+0x19243b
0000009f`ebcff7f0 00007ff6`c432b0c0     : 00000000`00000000 00000000`00000001 000002a5`3d6b9700 00000000`00000000 : Starfield!Scaleform::Render::Matrix2x4<float>::SetZero+0x1926ab
0000009f`ebcff880 00007ff6`c4455dfc     : 0000029d`3d86f440 00000000`00000010 00000000`00000000 00000000`00000000 : Starfield!Scaleform::Render::Matrix2x4<float>::SetZero+0x18fc80
0000009f`ebcff940 00007ff6`c4455cf5     : 0000029d`3d86f440 00000000`00000001 00000000`00000001 0000029d`3d86f480 : Starfield!Scaleform::Render::Matrix2x4<float>::SetZero+0x2ba9bc
0000009f`ebcff970 00007ff6`c40baf12     : 0000029d`3d86f440 00007ff6`c8d2a658 00000000`00000000 00007ff6`c586c130 : Starfield!Scaleform::Render::Matrix2x4<float>::SetZero+0x2ba8b5
0000009f`ebcff9d0 00007ff6`c3f8b141     : 00007ff6`c6c3f980 00007ff6`c586c130 00000000`00000000 00007ff6`c8d052c8 : Starfield!Scaleform::Render::Matrix4x4<float>::SetIdentity+0x9f76d6
0000009f`ebcffa00 00007ffe`695026bd     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : Starfield!Scaleform::Render::Matrix4x4<float>::SetIdentity+0x8c7905
0000009f`ebcffa80 00007ffe`6b04a9f8     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : kernel32!BaseThreadInitThunk+0x1d
0000009f`ebcffab0 00000000`00000000     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!RtlUserThreadStart+0x28


FAULTING_SOURCE_LINE:  d:\a01\_work\2\s\src\vctools\crt\vcruntime\src\string\amd64\memcpy.asm

FAULTING_SOURCE_FILE:  d:\a01\_work\2\s\src\vctools\crt\vcruntime\src\string\amd64\memcpy.asm

FAULTING_SOURCE_LINE_NUMBER:  203

SYMBOL_NAME:  VCRUNTIME140!memcpy+114

MODULE_NAME: VCRUNTIME140

IMAGE_NAME:  VCRUNTIME140.dll

STACK_COMMAND:  ~58s; .ecxr ; kb

FAILURE_BUCKET_ID:  INVALID_POINTER_READ_STACK_POINTER_MISMATCH_c0000005_VCRUNTIME140.dll!memcpy

OS_VERSION:  10.0.22621.1

BUILDLAB_STR:  ni_release

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

IMAGE_VERSION:  14.29.30133.0

FAILURE_ID_HASH:  {59333233-a0bf-fd4e-5798-bbeec4c3131f}

Followup:     MachineOwner
---------

**Comment by Pickysaurus** [comment]
There's not enough here to go on. You can try reporting this to Bethesda.
