### ISSUE TITLE
M2F audio change

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#947]
Switching body type from 2 to 1 does not change the audio used when using melee or vaulting.

---

## Details 
I started a Body type 1 character. I switched to body type 2 mid game. Then switched back to body type 1.
The "female" audio is used in melee and vaulting (mounting an obstacle)

## Game Version
1.10.31.0

## New Game
No

## Reproduction Steps
I started a Body type 1 character. I switched to body type 2 mid game. Then switched back to body type 1.
The "female" audio is used in melee and vaulting (mounting an obstacle)

**Comment by Deebz96** [comment]
Voice is linked to pronoun selection.
