### ISSUE TITLE
NG+ "You?" follower has bad/buggy crime faction

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#949]
As far as I can tell, other followers either have a personal crime faction or none, the "You?" follower (player duplicate follower available in a NG+ alt universe) is in the general UC crime faction. This results in clearly unintended behaviour. Your follower will "report" you for stealing from UC NPCs, will confiscate stolen items, and will call security. Security will arrive then immediately leave as they cannot arrest you. 

---

## Details 
Crew_Elite_OtherPlayerMale_NoAppearanceData [NPC_:001A93A5], 
CrimeFactionUC [FACT:0005BD93], 
Mod that includes this fix: https://www.nexusmods.com/starfield/mods/9096

## Game Version
1.10.32.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Have "You?" as your active follower and go somewhere with items owned by someone in the UC crime faction, such as the bedroom of Governor Hurst’s apartment in Cydonia. Try to take or move the items marked as owned/stolen when "You?" can see you doing it.
https://youtu.be/FZ-63wyNyUk

**Comment by Constellation-VASCO** [comment]
I spoke a little too soon about other followers not being in general crime factions, Adoring Fan is also in the UC crime faction (exactly the same happens with him when you steal from a UC NPC as detailed above) and Lyle Brewer is in the Freestar general crime faction. But the vast majority aren't, and tbh I think given the fact that all respond to theft in this half broken way, it can still be considered a bug.

**Comment by Aurelianis** [comment]
I do not believe this is a bug. Beth has in the past made followers part of different crime factions. In Fallout 4 for example, MacCready is part of the Goodneighbor crime faction so if you steal in Goodneighbor he won't like it even though he generally likes it when you steal. You? grew up in the UC so it makes sense to me that You? wouldn't like if if you are stealing from US citizens. I believe this behavior was intended based on Bethesda's previous titles.
