### ISSUE TITLE
Books on the ECS Constant are "steal only"

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#950]
With the latest patch "What if I'm right" and "Essentials of Modern Macroeconomics" from the ECS Constant require you to steal them (previously they were available without stealing them.

---

## Details 
Form ID 00028F11 (modern Macro) and 0007FA34 (What If I'm Right)

## Game Version
1.10.32.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Go to the ECS Constant, you'll see the books are now "steal only"

**Comment by Deebz96** [comment]
This seems like a proper change to me. You are stealing them if you take them.
