### ISSUE TITLE
Bridger weapon perk interaction

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#951]
Neither the ballistics skill nor the heavy weapon skill provide boosts to the damage output of the Bridger grenade launcher. Both include the Bridger in their perk art so I believe we can assume its an oversight.

---

## Details 
The Bridger has two sources of damage, first the projectile itself does some amount of bulk damage and then the explosive does splash damage of a lesser amount. Currently the only perk effecting it is explosives and it effects both, ideally I think the explosive splash would be effected by explosive and the main damage would be effected by heavy weapons and ballistics 

## Game Version
1.8.86.0

## New Game
Yes

## Reproduction Steps
Spawn the bridger weapon or any variant, test damage or verify using in game menu, apply ballistics or heavy weapons perks and test again

**Comment by Constellation-VASCO** [comment]
This is my own fault for not testing more closely before posting this but please note that I had it backwards, the bulk of the damage is explosive splash with a small amount that is not. the rest remains accurate

**Comment by Constellation-VASCO** [comment]
It also does not benefit from the ballistic weapon skill magazines

**Comment by Deebz96** [comment]
I don't necessarily agree with the ballistics keyword being missing, as this is a rocket launcher weapon. However, it should definitely have the WeaponTypeHeavyGun keyword.

The Negotiator also appears to be lacking this keyword.

Both will be fixed in 0.1.8.

**Comment by Deebz96** [comment]
Been reconsidering the ballistic keyword, and I will add it to these weapons as well. These are my reasons.

- It is in the Ballistics perk icon, as you mention.
- It currently does not benefit from rapid reloading without this keyword.
- The Rev-8's turret benefits from Lasers, Demolitions, and Heavy Weapons. This would bring these rocket launchers in line with that weapon.
- The damage of these weapons is still fairly low without the Ballistics keyword.
- At the end of the day, the 40MM XPL rounds are just simply ballistic projectiles.
