### ISSUE TITLE
Particle Beam kills do not increment Laser Kills

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#953]
Patch notes for update 1.10.31 state "Particle Beam weapon kills should now increment Laser Kills in Combat Stats."
This just doesn't happen.

---

## Game Version
1.10.32.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Equip particle beam weapon, kill anything, "Laser Kills" combat stat doesn't increase.

**Comment by Deebz96** [comment]
Addressed in SFCP 0.1.4

**Comment by Constellation-VASCO** [comment]
No, it isn't.
