### ISSUE TITLE
Items can't be picked up

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#955]
Items can't be picked up unless using another item to show the interaction prompt

---

## Details 
I have discovered an issue with picking items up. Some items are missing the prompt to pick them up while others still have it. If you drag an item that has the prompt, you'll be able to pick both items up

## Game Version
1.11.36

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
You go over to an item that should have a prompt and if it doesn't manually drag an item over to the one that is missing the prompt, and it should let you pick it up

**Comment by Constellation-VASCO** [comment]
Also works with bringing bodies to the items

**Comment by Deebz96** [comment]
Do you have StarUI HUD?

**Comment by Constellation-VASCO** [comment]
Is it the hud? I do have it

**Comment by Constellation-VASCO** [comment]
That's the problem. I honestly thought it was the Community patch since I've used the hud before without the problem. I'll remove this
