### ISSUE TITLE
New Atlantis The Well Local Map

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#967]
I noticed the local map for the well wasn't working at all, since I update my mods daily I assumed it was something I had changed recently. I updated SCP yesterday and started a new game this morning, the map was not working as soon as I entered the well. After bisecting all of my mods I have narrowed it down to SCP, with the mod installed the local map will not show at all. When it's uninstalled it works perfectly

---

## Game Version
1.11.36

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Enter The Well in New Atlantis (SCP Installed), attempt to open local map opens planet view and hotkey to switch to local map does not work

**Comment by Aurelianis** [comment]
Confirmed. 

The cell header for The Well [000F4ED4] was modified to inherit gravity from the planet (Unknown 17 flag). Bethesda added new data to the cell headers for the local maps and although this data was forwarded in v0.1.4 of SFCP, it appears it doesn't work properly. We will need to remove [000F4ED4] from SFCP until the CK is released.

Fix: Remove [000F4ED4] from SFCP.
