### ISSUE TITLE
Power from beyond Scan not working

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#97]
My scanner should twitch so that i can follow and find the temple, but it doesn't happen. In other planets and other missions this works perfectly fine.

---

## Details 
I dont know any.

## Game Version
1.10.0

## New Game
No

## Reproduction Steps
I dont know how to recreate it, but i saw other people online having the same issue.

**Comment by Pickysaurus** [comment]
This may have been fixed in 0.0.3
