### ISSUE TITLE
Guards comment on your weapon when it's not visible

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#970]
Security guards occasionally comment on your weapon, but these lines trigger even when your equipped weapon is not visible due to being holstered. While there are situations where you can see your holstered weapon (on the side of your jetpack), this mechanic is very unreliable: sometimes your jetpack disappears in breathable areas, or you may not have a jetpack at all.

---

## Details 
To eliminate these edge cases, we need to add the `IsWeaponOut=2` condition. Interestingly, there is already a similar line with this check ([0015DA33] "I'm going to assume you killed a pirate and took his gun. Otherwise... we're gonna have a problem."). We just need to fix the rest.

![](https://terab1t.ru/sfcp/fix_specific_weapon.png)

Affected lines:

- Is there a type of weapon CombaTech WON'T make?
- How you liking that laser gun? Pew pew!
- Ooooh. Look who's got a Laredo gun. Welcome to civilization, cowpoke.
- Ooooh. Look who's got a Laredo gun. Welcome to civilization, cowgirl.
- Ooooh. Look who's got a Laredo gun. Welcome to civilization, cowboy.
- Oooh. CombaTech Big Bang. Now THAT'S a weapon. 
- Va'ruun weapon, huh? Nasty. 

Affected ID:

- 001569CA
- 001569CB
- 0015DA2E
- 0015DA2F
- 0015DA30
- 0015DA32
- 0015DA4B

## Game Version
1.11.36

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
1. Travel to New Atlantis (or any other city).
2. Equip a CombaTech/Laredo/laser/Va'ruun weapon and make sure it is NOT visible.
3. Try to talk to any generic guard as many times as you can.
4. Observe that guards occasionally comment on your weapon even if they can't see it.

**Comment by Constellation-VASCO** [comment]
An ESM file with a fix: https://drive.google.com/file/d/1EdOR6nURotlgCdvvJs4LMVPfSK0pYjr_/view?usp=sharing

**Comment by Deebz96** [comment]
I'm going to hold off on this one for now, as it makes sense for guards to comment on a weapon you currently have holstered. Even if it may not be rendering, I suppose it's implied that it's visible. Guards will also ask you to put your weapon away if it's currently out, is a bit of a contradiction if they also only say these lines while your weapon is unholstered.
