### ISSUE TITLE
No footstep sound with Sarah's outfit

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#978]
Since release, sarah's outfit does not produce footstep, jumping, or landing sounds when worn by the player, moreover, when the outfit's boots are used on other outfits by mods (for example with Starfield Extended - New outfits) those sounds are also missing.

---

## Details 
Sarah morgan's outfit 00055905

## Game Version
1.11.36

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Wear Sarah Morgan's outfit, or any outfit using the boots from Sarah Morgan's outfit, and take steps or jump.

**Comment by Deebz96** [comment]
This actually affects all four companion outfits. The lower body ARMA records that make up these outfits all have the FSTDefaultComnpanionFootstepSet [FSTS:001EB802] footstep set assigned to them. This set does not come with player sounds.

It seems to be entirely unnecessary for this set to be assigned to these outfits. It's only assigned to five ARMA records used by the companion outfits. Companions are able to use other footstep sets normally, which will happen when you equip any other outfit on them. As far as I can tell, removing the SNDD component from these ARMA records will fix the issue without causing any other problems.
