### ISSUE TITLE
Main quest destination planet not showing up.

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#98]
At the Mission "Into de Unknown" the objective planet [Procyon III] doesn't show up as destination.

---

## Details 
For my walktrough I decided to postpone the Main Quest and complete the Vanguard Missions for the Crimson Fleet spy and the Terrormorph Questline. Those are the secondary missions I made while postponing the main quest, I headed then to The Eye and spoke with Vlad, and the mission order showed as: "[Go To . . . ] and then nothing.
Missions completed until the error: (In order of first to latest)

-One Small Step
-The Old Neighborhood
-The Empty Nest
-A tree Grows in New Atlantis
-Back to Vectera
-Job Gone Wrong
-Out on a Limb
-Tapping the Grid
-Alternating Currents
-Late Bloomer
-Keeping the Peace
-Supra et Ultra
-Grunt Work
-Deep Cover
-Delivering Devils
-Eyewitness
-Friends like these
-The Devils you know
-In Memoriam
-Rook Meets King
-Commitment: Sarah Morgan
-Echoes of the Past
-Breaking the Bank
-The Best there is
-Lost and Found
-Absolute Power
-Eye of the Storm
-Legacy's End
-War Relics
-Hostile Intelligence
-A Legacy Forged
 [Attempted to play "Into the Unknown"]*
-A Break at Dawn
-Search and Seizure

## Game Version
1.7.23.0

## New Game
No

## Reproduction Steps
I've found some people having similar problems with this mission, some regarding to the scanners, and that playing the Crimson Fleet and Vanguard questlines affect "Into the Unknown"

**Comment by Aurelianis** [comment]
Fixed in v1.9.47.0
"Into the Unknown: Fixed a rare issue where a Temple location might not populate when receiving the “Go to” objective."
