### ISSUE TITLE
Photo Mode breaks lighting on ships in space

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#981]
While in a space based area, ex. onboard a ship in orbit—entering photo mode will cause all ship's lighting to turn off until you reload a save or change locations. Rooms without outside lighting (the sun) will literally be pitch black. Mostly seems to only happen while in space but on larger ships even when landed, the furthest rooms from the camera will become and stay dark as well.

---

## Game Version
1.8.86.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
1. Have ship take off and enter space
2. Enter photo mode
3. Witness all lights cut off and ship become pitch black
4. Change zones or reload because the lights will not come back on and you can't take that photo you wanted

**Comment by Aurelianis** [comment]
This is most likely an engine level bug and probably not something that we will be able to fix. I know this issue has been submitted to Bethesda, so here's hoping they fix it.

**Comment by Constellation-VASCO** [comment]
Thank you for the information!

**Comment by Deebz96** [comment]
This was fixed officially.
