### ISSUE TITLE
[New Issue] Environmental damage not healed by meds or doctors if "Environmental Damage Restoration" is set to "Limited Resting"

### ISSUE THREAD

**Issue by CrankyCat** [Starfield-Community-Patch/Starfield-Community-Patch#982]
With "Environmental Damage Restoration" set to "limited resting", resting or healing are the only way to remove the permanent debuff to max health. Meds, aid items, or even visiting a doctor have no effect even after the affliction is removed.

### Details

Environmental damage is generally inflicted along with the related affliction; i.e. burns or frostbite. This limits your maximum health until healed. It used to be healed when you were in a safe space and there is a difficulty setting for that. It seems an unintended (?) consequence of setting "Environmental Damage Restoration" to "limited resting" is to make resting or waiting for a sufficient amount of time the **only** way to heal environmental damage even after the affliction is removed. Visiting a doctor or using aid items won't work even after the affliction is removed.

It's simple to resolve by resting for long enough in your outpost or ship but at least to me it seemed that a physician should be able to remove environmental damage even with the restoration setting. 

### Game Version

1.11.36

### Language

English (EN)

### Have you recreated this issue on a new game?

Yes, I can recreate this issue.

### Reproduction Steps

1. Set "Environmental Damage Restoration" to "limited resting" and set "Environmental Damage & Afflictions" to "Advanced".
2. Go to a location with high ambient damage such as Mars during the day for radiation.
3. Stay outside until suit protection runs out and an affliction occurs along with some noticeable environmental damage to your max health.
4. Go back inside your ship.
5. Use aid items or a physician to remove the affliction. 
6. The environmental damage should remain and limit your max health. Aid items and healing packs shouldn't do anything to increase your max health. Visiting a doctor shouldn't either; although a doctor will acknowledge that you need patching up paying for this won't restore your max health. I see this as the problem as at least a physician should be able to restore it.
7. Go to your own ship bed or outpost bed and rest for 8 hours or however long is sufficient. Health should be restored per the setting.

**Comment by Constellation-VASCO** [comment]
Having this same issue. Only way to remove the orange health bar is to sleep for me.

**Comment by CrankyCat** [comment]
If nothing else I think they should change the description text to point out that rest and waiting are the ONLY way to remove environmental damage if this is the case. At least then it'll be obvious up front instead of unexpected.

**Comment by Deebz96** [comment]
SQ_DoctorScript only tries to heal health, and doesn't account for environmental damage by default. Fix attached.
[SFCP_982.zip](https://github.com/user-attachments/files/16741944/SFCP_982.zip)
