### ISSUE TITLE
Ryujin quest fail

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#991]
Unable to begin "top secrets"

---

## Details 
Upon trying to complete the Ryujin quest line for the 3rd time on a new game plus I've encountered a bug the does not allow me to begin the quest "top Secrets". After speaking with Imogene I head to ularus office and she's in there in her meeting but I'm unable to trigger the quest start no matter what I try.

## Game Version
V1.12.30.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
While mid completion in other quest lines try to begin the Top Secrets quest.

**Comment by Constellation-VASCO** [comment]
Thank you for all that yall do.

**Comment by Deebz96** [comment]
Have not been able to replicate this issue. Not enough information to troubleshoot with.
