### ISSUE TITLE
Sustenance still leading to incorrect sneak damage

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#994]
While the new June update to 1.12.30 removed the extremely high sneak attack damage bonus (34x) with the hydrated status effect, the underlying numbers are still incorrect. 

---

## Details 
Running some tests, the underlying problem seems to be that simply enabling the sustenance gameplay option doubles the base sneak attack damage that is in effect at that time. That is, if you have 2x sneak attack damage with no perks in stealth or concealment when sustenance is completely turned off in the options, turning it to "positive only" immediately doubles that bonus to 4x damage, without drinking anything.  When drinking something on top of that, enabling the hydrated status effect, the calculation for that effect seems to be correct (+15%, leading to 4,3x damage), but still with the wrong base damage bonus (4x instead of 2x).
Turning the sustenance option up to "positive & negative", being dehydrated leads to no sneak attack bonus damage at all (when it should be -15%). Drinking something again leads to the wrong 4,3x bonus.
Now, when adding perks in the stealth skill, we still get the same incorrect doubling of the base sneak attack damage bonus when sustenance is enabled. So with rank 4 in stealth (2.5x sneak damage), we get 5x if we enable sustenance.
However, if we add concealment perks on top of that, the entire sustenance sneak attack damage effect system seems to get disabled. With rank 4 in stealth + rank 1 in concealment, we normally get 3,1x sneak attack bonus when using ranged weapons. Enabling sustenance leads to the exact same number (not double!), and drinking something on top of that also doesn't bring any +15% bonus.

So, there seem to be two problems overall: 
-Enabling sustenance doubles the sneak attack damage bonus, when it should only add +15% when hydrated.
-Concealment perks break the entire sustenance sneak damage system.

## Game Version
1.12.30 (June update)

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
To start, have the sustenance gameplay option turned off. Then use a silenced ranged weapon to shoot another character while in stealth. Note the sneak attack damage bonus (should be 2x with no stealth or concealment perks, and higher according to any perks present).

Then enable the sustenance option by setting it to "positive only", but not drinking anything yet (no hydration effect). Do another sneak attack, the damage will be double the value it was before.

**Comment by Constellation-VASCO** [comment]
Update for this issue with the Hotfix on 14/06/2024 (1.12.32.0): NOT FIXED, same behavior as reported above.

**Comment by Deebz96** [comment]
This system is such a mess lol

Fix attached:
[SFCP_994.zip](https://github.com/user-attachments/files/17141617/SFCP_994.zip)

**Comment by Constellation-VASCO** [comment]
Testing results on the fix by Deebz96:

-With the sneak attack damage bonus granted by the stealth perks, everything now seems to work as it should. The effects of hydration and dehydration seem to be calculated correctly and sneak attack damage reflects this.

-However, adding the concealment perks (further increasing base sneak attack damage) seems to break the system, and I get no hydration or dehydration effects on sneak attack damage at all (it always stays at the base efffect granted by the concealment perk)

-And this problem where concealment perks seem to deactivate the entire system of hydration or dehydration effects on sneak attack damage is also present in the current unmodded game.

**Comment by Constellation-VASCO** [comment]
Note: The remaining problem with concealment sneak attack damage is fixed when adding the fix mentioned for this issue: https://www.starfieldpatch.dev/issues/1171
