### ISSUE TITLE
New Atlantis spaceport floor missing (known bug)

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#995]
Famous bug where some parts of New Atlantis ground near the spaceport disappear after boarding your ship in The Den

---

## Details 
https://www.reddit.com/r/Starfield/comments/16ad6s4/new_atlantis_spaceport_floor_disappear_bug/

## Game Version
1.12.30

## Language
Spanish (ES)

## New Game
Yes

## Reproduction Steps
- Dock in the Den.
- Board the Frontier again from there.
- You spawn in New Atlantis with missing floor textures.

**Comment by Deebz96** [comment]
This was fixed officially.
