### ISSUE TITLE
中文版本的游戏中，船只的价格最高只有五位数

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#996]
在中文版本的游戏中，由于游戏界面或者字体的原因，高级船只应该显示六位数，但游戏中只显示五位数，导致船只无法购买

---

## Game Version
1.12.30

## Language
简体中文 （ZHHANS）

## New Game
Yes

## Reproduction Steps
使用中文版本去购买船只就会出现这种问题

**Comment by Constellation-VASCO** [comment]
贝塞斯达已经修复了这个BUG
bethesda has fixed this BUG

**Comment by Deebz96** [comment]
Fixed officially.
