### ISSUE TITLE
Neon Deluxe Sleepcrate marker location

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#998]
The deluxe sleepcrate map marker location can not be activated because it resides inside the sleepcrate itself. This contradicts other player home locations such as the homes on Akila and Jemison. They can be marked as located WITHOUT having to purchase said properties.

---

## Details 
The marker could be moved just outside the door to the sleepcrate.

## Game Version
1.12.30.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Basic placement by Bethesda. Can be recreated across any and all platforms and saves.

**Comment by Deebz96** [comment]
I would not consider this one to be a bug, as the Well house is the same way. Just one of those things.
